import { Pack } from "./dataA";

export const PACKS_B: Pack[] = [
  {
    id: "feelings", emoji: "😊", title: "Feelings & Emotions", desc: "Say exactly how you feel",
    words: [
      { word: "happy", type: "adjective", meaning: "feeling joy", hindi: "खुश", example: "She looks happy today.", synonym: "glad" },
      { word: "sad", type: "adjective", meaning: "feeling sorrow", hindi: "दुखी", example: "He was sad about the result.", synonym: "unhappy" },
      { word: "angry", type: "adjective", meaning: "feeling anger", hindi: "गुस्सा", example: "Don't be angry with me.", synonym: "mad" },
      { word: "excited", type: "adjective", meaning: "very enthusiastic", hindi: "उत्साहित", example: "I'm excited about the trip.", synonym: "thrilled" },
      { word: "nervous", type: "adjective", meaning: "slightly worried", hindi: "घबराया", example: "I feel nervous before exams.", synonym: "anxious" },
      { word: "calm", type: "adjective", meaning: "peaceful, not excited", hindi: "शांत", example: "Stay calm in the interview.", synonym: "peaceful" },
      { word: "relaxed", type: "adjective", meaning: "free from tension", hindi: "तनावमुक्त", example: "I feel relaxed on Sundays.", synonym: "at ease" },
      { word: "worried", type: "adjective", meaning: "thinking about problems", hindi: "चिंतित", example: "She is worried about her son.", synonym: "concerned" },
      { word: "scared", type: "adjective", meaning: "feeling fear", hindi: "डरा हुआ", example: "He is scared of dogs.", synonym: "frightened" },
      { word: "proud", type: "adjective", meaning: "feeling honor", hindi: "गर्वित", example: "I'm proud of you.", synonym: "honored" },
      { word: "shy", type: "adjective", meaning: "nervous with people", hindi: "शर्मीला", example: "Don't be shy, speak up.", synonym: "timid" },
      { word: "confident", type: "adjective", meaning: "sure of yourself", hindi: "आत्मविश्वासी", example: "She gave a confident answer.", synonym: "sure" },
      { word: "jealous", type: "adjective", meaning: "wanting what others have", hindi: "ईर्ष्यालु", example: "He is jealous of my success.", synonym: "envious" },
      { word: "embarrassed", type: "adjective", meaning: "feeling shame", hindi: "शर्मिंदा", example: "I felt embarrassed in class.", synonym: "ashamed" },
      { word: "disappointed", type: "adjective", meaning: "sad because hopes failed", hindi: "निराश", example: "We were disappointed with the movie.", synonym: "let down" },
      { word: "frustrated", type: "adjective", meaning: "annoyed at being blocked", hindi: "हताश", example: "I'm frustrated with slow internet.", synonym: "annoyed" },
      { word: "confused", type: "adjective", meaning: "unable to understand", hindi: "असमंजस", example: "I'm confused by this question.", synonym: "puzzled" },
      { word: "surprised", type: "adjective", meaning: "feeling surprise", hindi: "हैरान", example: "I was surprised by the gift.", synonym: "astonished" },
      { word: "amazed", type: "adjective", meaning: "greatly surprised", hindi: "अचंभित", example: "I'm amazed by your English.", synonym: "awed" },
      { word: "bored", type: "adjective", meaning: "feeling uninterested", hindi: "ऊबा हुआ", example: "I felt bored in the lecture.", synonym: "uninterested" },
      { word: "tired", type: "adjective", meaning: "needing rest", hindi: "थका", example: "I'm tired after work.", synonym: "weary" },
      { word: "exhausted", type: "adjective", meaning: "extremely tired", hindi: "बुरी तरह थका", example: "I'm exhausted after the match.", synonym: "drained" },
      { word: "energetic", type: "adjective", meaning: "full of energy", hindi: "ऊर्जावान", example: "She is energetic every morning.", synonym: "active" },
      { word: "motivated", type: "adjective", meaning: "eager to do something", hindi: "प्रेरित", example: "I feel motivated to study.", synonym: "inspired" },
      { word: "grateful", type: "adjective", meaning: "feeling thanks", hindi: "आभारी", example: "I'm grateful for your help.", synonym: "thankful" },
      { word: "lonely", type: "adjective", meaning: "sad from being alone", hindi: "अकेला", example: "He feels lonely in the city.", synonym: "alone" },
      { word: "hopeful", type: "adjective", meaning: "feeling hope", hindi: "आशावान", example: "I'm hopeful about the result.", synonym: "optimistic" },
      { word: "upset", type: "adjective", meaning: "unhappy, disturbed", hindi: "परेशान", example: "She is upset about the news.", synonym: "disturbed" },
      { word: "curious", type: "adjective", meaning: "wanting to know", hindi: "जिज्ञासु", example: "I'm curious to learn more.", synonym: "inquisitive" },
      { word: "cheerful", type: "adjective", meaning: "visibly happy", hindi: "हंसमुख", example: "She is always cheerful.", synonym: "joyful" },
    ],
  },
  {
    id: "office", emoji: "💼", title: "Office & Work", desc: "Talk smart at work",
    words: [
      { word: "meeting", type: "noun", meaning: "people gathering to discuss", hindi: "बैठक", example: "The meeting starts at 10.", synonym: "discussion" },
      { word: "colleague", type: "noun", meaning: "person you work with", hindi: "सहकर्मी", example: "My colleague helped me.", synonym: "coworker" },
      { word: "boss", type: "noun", meaning: "person in charge", hindi: "मालिक", example: "My boss approved the leave.", synonym: "manager" },
      { word: "salary", type: "noun", meaning: "monthly pay", hindi: "वेतन", example: "Salary comes on the 1st.", synonym: "pay" },
      { word: "promotion", type: "noun", meaning: "moving to higher rank", hindi: "पदोन्नति", example: "She got a promotion.", synonym: "advancement" },
      { word: "resign", type: "verb", meaning: "quit a job", hindi: "इस्तीफा देना", example: "He will resign next month.", synonym: "quit" },
      { word: "hire", type: "verb", meaning: "give someone a job", hindi: "नौकरी पर रखना", example: "They hired two engineers.", synonym: "employ" },
      { word: "shift", type: "noun", meaning: "work time period", hindi: "पारी", example: "I work the night shift.", synonym: "duty" },
      { word: "overtime", type: "noun", meaning: "extra work hours", hindi: "अतिरिक्त समय", example: "I did overtime yesterday.", synonym: "extra hours" },
      { word: "workload", type: "noun", meaning: "amount of work", hindi: "कार्यभार", example: "My workload is heavy.", synonym: "burden" },
      { word: "task", type: "noun", meaning: "piece of work", hindi: "कार्य", example: "Finish today's tasks.", synonym: "job" },
      { word: "project", type: "noun", meaning: "planned work", hindi: "परियोजना", example: "The project ends Friday.", synonym: "assignment" },
      { word: "report", type: "noun", meaning: "written account", hindi: "रिपोर्ट", example: "Submit the report.", synonym: "summary" },
      { word: "presentation", type: "noun", meaning: "talk to audience", hindi: "प्रस्तुति", example: "Her presentation was great.", synonym: "demo" },
      { word: "client", type: "noun", meaning: "person who buys service", hindi: "ग्राहक", example: "The client is happy.", synonym: "customer" },
      { word: "contract", type: "noun", meaning: "legal work paper", hindi: "अनुबंध", example: "Sign the contract.", synonym: "agreement" },
      { word: "negotiation", type: "noun", meaning: "discussion to agree", hindi: "मोलभाव", example: "Negotiation took two hours.", synonym: "bargaining" },
      { word: "target", type: "noun", meaning: "goal to reach", hindi: "लक्ष्य", example: "We hit the sales target.", synonym: "goal" },
      { word: "feedback", type: "noun", meaning: "opinion for improvement", hindi: "प्रतिक्रिया", example: "Give me honest feedback.", synonym: "review" },
      { word: "appraisal", type: "noun", meaning: "work evaluation", hindi: "मूल्यांकन", example: "Appraisal is in April.", synonym: "evaluation" },
      { word: "internship", type: "noun", meaning: "trainee job period", hindi: "इंटर्नशिप", example: "She started an internship.", synonym: "training" },
      { word: "resume", type: "noun", meaning: "work history paper", hindi: "बायोडाटा", example: "Update your resume.", synonym: "CV" },
      { word: "skill", type: "noun", meaning: "ability to do well", hindi: "कौशल", example: "Learn a new skill.", synonym: "talent" },
      { word: "training", type: "noun", meaning: "learning for a job", hindi: "प्रशिक्षण", example: "Training starts Monday.", synonym: "coaching" },
      { word: "schedule", type: "noun", meaning: "time plan", hindi: "समय सारिणी", example: "Check the schedule.", synonym: "timetable" },
      { word: "career", type: "noun", meaning: "working life", hindi: "करियर", example: "Build a strong career.", synonym: "profession" },
      { word: "professional", type: "adjective", meaning: "work-like, serious", hindi: "व्यावसायिक", example: "Be professional at work.", synonym: "businesslike" },
      { word: "business", type: "noun", meaning: "company, trade", hindi: "व्यवसाय", example: "He runs a small business.", synonym: "company" },
      { word: "workplace", type: "noun", meaning: "place of work", hindi: "कार्यस्थल", example: "A clean workplace helps.", synonym: "office" },
      { word: "vacancy", type: "noun", meaning: "open job position", hindi: "रिक्ति", example: "A vacancy for teachers.", synonym: "opening" },
    ],
  },
  {
    id: "tech", emoji: "💻", title: "Technology & Phone", desc: "Everyday tech words",
    words: [
      { word: "device", type: "noun", meaning: "machine like phone/laptop", hindi: "उपकरण", example: "Charge your device.", synonym: "gadget" },
      { word: "screen", type: "noun", meaning: "display part", hindi: "स्क्रीन", example: "The screen is bright.", synonym: "display" },
      { word: "battery", type: "noun", meaning: "power source", hindi: "बैटरी", example: "My battery is low.", synonym: "cell" },
      { word: "charger", type: "noun", meaning: "thing that charges", hindi: "चार्जर", example: "Bring your charger.", synonym: "adapter" },
      { word: "password", type: "noun", meaning: "secret word", hindi: "पासवर्ड", example: "Change your password.", synonym: "code" },
      { word: "username", type: "noun", meaning: "account name", hindi: "यूज़रनेम", example: "Enter your username.", synonym: "login name" },
      { word: "login", type: "verb", meaning: "enter account", hindi: "लॉगिन", example: "Login with email.", synonym: "sign in" },
      { word: "logout", type: "verb", meaning: "leave account", hindi: "लॉगआउट", example: "Logout before sleeping.", synonym: "sign out" },
      { word: "app", type: "noun", meaning: "phone program", hindi: "ऐप", example: "Install the app.", synonym: "application" },
      { word: "website", type: "noun", meaning: "page on internet", hindi: "वेबसाइट", example: "Visit our website.", synonym: "site" },
      { word: "browser", type: "noun", meaning: "internet program", hindi: "ब्राउज़र", example: "Open Chrome browser.", synonym: "explorer" },
      { word: "download", type: "verb", meaning: "save from internet", hindi: "डाउनलोड", example: "Download the file.", synonym: "save" },
      { word: "upload", type: "verb", meaning: "send to internet", hindi: "अपलोड", example: "Upload your photo.", synonym: "send" },
      { word: "install", type: "verb", meaning: "put software on", hindi: "इंस्टॉल", example: "Install the update.", synonym: "set up" },
      { word: "delete", type: "verb", meaning: "remove", hindi: "हटाना", example: "Delete old messages.", synonym: "erase" },
      { word: "update", type: "verb", meaning: "make newer", hindi: "अपडेट", example: "Update your phone.", synonym: "upgrade" },
      { word: "backup", type: "noun", meaning: "safety copy", hindi: "बैकअप", example: "Take a backup.", synonym: "copy" },
      { word: "virus", type: "noun", meaning: "bad software", hindi: "वायरस", example: "The laptop has a virus.", synonym: "malware" },
      { word: "hacker", type: "noun", meaning: "person who breaks in", hindi: "हैकर", example: "Beware of hackers.", synonym: "intruder" },
      { word: "internet", type: "noun", meaning: "global network", hindi: "इंटरनेट", example: "The internet is slow.", synonym: "web" },
      { word: "wifi", type: "noun", meaning: "wireless internet", hindi: "वाईफ़ाई", example: "What's the wifi password?", synonym: "wireless" },
      { word: "network", type: "noun", meaning: "connected system", hindi: "नेटवर्क", example: "Network is weak here.", synonym: "connection" },
      { word: "signal", type: "noun", meaning: "connection strength", hindi: "सिग्नल", example: "No signal in the lift.", synonym: "reception" },
      { word: "storage", type: "noun", meaning: "space to keep data", hindi: "भंडारण", example: "Storage is full.", synonym: "space" },
      { word: "file", type: "noun", meaning: "digital document", hindi: "फ़ाइल", example: "Open the file.", synonym: "document" },
      { word: "folder", type: "noun", meaning: "place for files", hindi: "फ़ोल्डर", example: "Put it in a folder.", synonym: "directory" },
      { word: "document", type: "noun", meaning: "written digital paper", hindi: "दस्तावेज़", example: "Share the document.", synonym: "paper" },
      { word: "screenshot", type: "noun", meaning: "photo of screen", hindi: "स्क्रीनशॉट", example: "Send a screenshot.", synonym: "capture" },
      { word: "notification", type: "noun", meaning: "phone alert", hindi: "सूचना", example: "Turn off notifications.", synonym: "alert" },
      { word: "software", type: "noun", meaning: "computer programs", hindi: "सॉफ़्टवेयर", example: "Update the software.", synonym: "programs" },
    ],
  },
  {
    id: "health", emoji: "🏥", title: "Health & Doctor", desc: "Explain problems clearly",
    words: [
      { word: "fever", type: "noun", meaning: "high body heat", hindi: "बुखार", example: "I have a fever.", synonym: "temperature" },
      { word: "cough", type: "noun", meaning: "throat sound", hindi: "खांसी", example: "A dry cough.", synonym: "throat" },
      { word: "cold", type: "noun", meaning: "nose/throat sickness", hindi: "ज़ुकाम", example: "I caught a cold.", synonym: "flu" },
      { word: "headache", type: "noun", meaning: "pain in head", hindi: "सिरदर्द", example: "I have a headache.", synonym: "head pain" },
      { word: "stomachache", type: "noun", meaning: "pain in stomach", hindi: "पेट दर्द", example: "A bad stomachache.", synonym: "tummy pain" },
      { word: "pain", type: "noun", meaning: "hurt feeling", hindi: "दर्द", example: "Pain in my knee.", synonym: "ache" },
      { word: "injury", type: "noun", meaning: "body damage", hindi: "चोट", example: "A leg injury.", synonym: "wound" },
      { word: "wound", type: "noun", meaning: "cut in skin", hindi: "घाव", example: "Clean the wound.", synonym: "cut" },
      { word: "medicine", type: "noun", meaning: "drug for illness", hindi: "दवा", example: "Take medicine twice.", synonym: "drug" },
      { word: "tablet", type: "noun", meaning: "pill medicine", hindi: "गोली", example: "One tablet after food.", synonym: "pill" },
      { word: "injection", type: "noun", meaning: "shot with needle", hindi: "टीका", example: "The injection didn't hurt.", synonym: "shot" },
      { word: "doctor", type: "noun", meaning: "medical expert", hindi: "डॉक्टर", example: "See a doctor.", synonym: "physician" },
      { word: "nurse", type: "noun", meaning: "hospital helper", hindi: "नर्स", example: "The nurse is kind.", synonym: "attendant" },
      { word: "hospital", type: "noun", meaning: "sick people place", hindi: "अस्पताल", example: "Go to the hospital.", synonym: "clinic" },
      { word: "clinic", type: "noun", meaning: "small hospital", hindi: "क्लिनिक", example: "The clinic opens at 9.", synonym: "center" },
      { word: "appointment", type: "noun", meaning: "fixed meeting time", hindi: "अपॉइंटमेंट", example: "Book an appointment.", synonym: "booking" },
      { word: "checkup", type: "noun", meaning: "health exam", hindi: "जांच", example: "A full body checkup.", synonym: "examination" },
      { word: "diagnosis", type: "noun", meaning: "finding the illness", hindi: "निदान", example: "The diagnosis was quick.", synonym: "finding" },
      { word: "treatment", type: "noun", meaning: "care to cure", hindi: "इलाज", example: "Start the treatment.", synonym: "therapy" },
      { word: "recovery", type: "noun", meaning: "getting better", hindi: "स्वास्थ्य लाभ", example: "Wish you a fast recovery.", synonym: "healing" },
      { word: "exercise", type: "noun", meaning: "body activity", hindi: "व्यायाम", example: "Exercise daily.", synonym: "workout" },
      { word: "diet", type: "noun", meaning: "food habit", hindi: "आहार", example: "Eat a healthy diet.", synonym: "food" },
      { word: "nutrition", type: "noun", meaning: "good food value", hindi: "पोषण", example: "Fruits give nutrition.", synonym: "nourishment" },
      { word: "hygiene", type: "noun", meaning: "cleanliness", hindi: "स्वच्छता", example: "Maintain good hygiene.", synonym: "cleanliness" },
      { word: "sleep", type: "noun", meaning: "rest at night", hindi: "नींद", example: "Get 8 hours of sleep.", synonym: "rest" },
      { word: "stress", type: "noun", meaning: "mental pressure", hindi: "तनाव", example: "Reduce your stress.", synonym: "pressure" },
      { word: "allergy", type: "noun", meaning: "body reaction", hindi: "एलर्जी", example: "I have a dust allergy.", synonym: "reaction" },
      { word: "disease", type: "noun", meaning: "illness", hindi: "बीमारी", example: "A rare disease.", synonym: "illness" },
      { word: "first aid", type: "noun", meaning: "quick help", hindi: "प्राथमिक उपचार", example: "Learn first aid.", synonym: "emergency help" },
      { word: "dizzy", type: "adjective", meaning: "head spinning", hindi: "चक्कर", example: "I feel dizzy.", synonym: "giddy" },
    ],
  },
  {
    id: "weather", emoji: "🌦️", title: "Weather & Seasons", desc: "Small talk about weather",
    words: [
      { word: "rain", type: "noun", meaning: "water from sky", hindi: "बारिश", example: "Heavy rain today.", synonym: "shower" },
      { word: "drizzle", type: "noun", meaning: "light rain", hindi: "फुहार", example: "A soft drizzle.", synonym: "sprinkle" },
      { word: "storm", type: "noun", meaning: "strong wind + rain", hindi: "तूफान", example: "A storm is coming.", synonym: "tempest" },
      { word: "thunder", type: "noun", meaning: "sky sound", hindi: "गड़गड़ाहट", example: "Loud thunder.", synonym: "roar" },
      { word: "lightning", type: "noun", meaning: "sky flash", hindi: "बिजली", example: "Lightning struck the tree.", synonym: "flash" },
      { word: "wind", type: "noun", meaning: "moving air", hindi: "हवा", example: "Strong wind today.", synonym: "breeze" },
      { word: "breeze", type: "noun", meaning: "gentle wind", hindi: "ठंडी हवा", example: "A cool breeze.", synonym: "air" },
      { word: "cloudy", type: "adjective", meaning: "full of clouds", hindi: "बादल वाला", example: "A cloudy sky.", synonym: "overcast" },
      { word: "sunny", type: "adjective", meaning: "with sun", hindi: "धूप वाला", example: "A sunny morning.", synonym: "bright" },
      { word: "foggy", type: "adjective", meaning: "full of fog", hindi: "धुंध वाला", example: "Foggy roads at night.", synonym: "misty" },
      { word: "humid", type: "adjective", meaning: "wet air", hindi: "नम", example: "Mumbai is humid.", synonym: "muggy" },
      { word: "dry", type: "adjective", meaning: "no water", hindi: "सूखा", example: "A dry season.", synonym: "arid" },
      { word: "wet", type: "adjective", meaning: "with water", hindi: "गीला", example: "Wet floor, be careful.", synonym: "damp" },
      { word: "hot", type: "adjective", meaning: "high heat", hindi: "गर्म", example: "It's too hot.", synonym: "scorching" },
      { word: "cold", type: "adjective", meaning: "low heat", hindi: "ठंडा", example: "Cold water please.", synonym: "chilly" },
      { word: "warm", type: "adjective", meaning: "nice heat", hindi: "गुनगुना", example: "Warm milk at night.", synonym: "mild" },
      { word: "cool", type: "adjective", meaning: "nicely cold", hindi: "ठंडक", example: "Cool evening.", synonym: "fresh" },
      { word: "freeze", type: "verb", meaning: "turn to ice", hindi: "जमना", example: "Water freezes at 0°C.", synonym: "ice up" },
      { word: "ice", type: "noun", meaning: "frozen water", hindi: "बर्फ", example: "Add ice to the drink.", synonym: "frost" },
      { word: "snow", type: "noun", meaning: "white frozen flakes", hindi: "हिम", example: "Snow in the mountains.", synonym: "flakes" },
      { word: "heatwave", type: "noun", meaning: "long very hot time", hindi: "लू", example: "A heatwave this week.", synonym: "hot spell" },
      { word: "monsoon", type: "noun", meaning: "rainy season", hindi: "मानसून", example: "Monsoon starts in June.", synonym: "rains" },
      { word: "summer", type: "noun", meaning: "hot season", hindi: "गर्मी", example: "Summer holidays!", synonym: "hot season" },
      { word: "winter", type: "noun", meaning: "cold season", hindi: "सर्दी", example: "Winter mornings are nice.", synonym: "cold season" },
      { word: "spring", type: "noun", meaning: "flower season", hindi: "वसंत", example: "Spring is colorful.", synonym: "bloom time" },
      { word: "autumn", type: "noun", meaning: "falling leaves season", hindi: "पतझड़", example: "Autumn looks golden.", synonym: "fall" },
      { word: "season", type: "noun", meaning: "time of year", hindi: "ऋतु", example: "Which season do you like?", synonym: "period" },
      { word: "temperature", type: "noun", meaning: "heat level", hindi: "तापमान", example: "The temperature is 30°C.", synonym: "degrees" },
      { word: "forecast", type: "noun", meaning: "weather prediction", hindi: "पूर्वानुमान", example: "Check the forecast.", synonym: "prediction" },
      { word: "rainbow", type: "noun", meaning: "color arc after rain", hindi: "इंद्रधनुष", example: "A beautiful rainbow.", synonym: "arc" },
    ],
  },
];