export type VWord = { word: string; type: string; meaning: string; hindi: string; example: string; synonym: string };
export type Pack = { id: string; emoji: string; title: string; desc: string; words: VWord[] };

export const PACKS_A: Pack[] = [
  {
    id: "daily", emoji: "🗣️", title: "Daily Conversation", desc: "Sound natural with friends",
    words: [
      { word: "genuinely", type: "adverb", meaning: "truly, honestly", hindi: "सच में", example: "I genuinely enjoyed the food.", synonym: "truly" },
      { word: "grab", type: "verb", meaning: "take quickly", hindi: "झट से लेना", example: "Let me grab a coffee.", synonym: "snatch" },
      { word: "catch up", type: "phrasal verb", meaning: "share recent news", hindi: "हालचाल लेना", example: "We should catch up soon!", synonym: "reconnect" },
      { word: "awesome", type: "adjective", meaning: "excellent", hindi: "शानदार", example: "The movie was awesome!", synonym: "amazing" },
      { word: "figure out", type: "phrasal verb", meaning: "solve, understand", hindi: "समझना", example: "I will figure out the route.", synonym: "solve" },
      { word: "hang out", type: "phrasal verb", meaning: "spend relaxed time", hindi: "साथ समय बिताना", example: "Let's hang out on Sunday.", synonym: "chill" },
      { word: "stuff", type: "noun", meaning: "things", hindi: "सामान", example: "I packed my stuff.", synonym: "things" },
      { word: "pretty", type: "adverb", meaning: "quite", hindi: "काफ़ी", example: "It's pretty cold today.", synonym: "quite" },
      { word: "totally", type: "adverb", meaning: "completely", hindi: "पूरी तरह", example: "I totally agree.", synonym: "completely" },
      { word: "honestly", type: "adverb", meaning: "truthfully", hindi: "सच कहूँ तो", example: "Honestly, I don't know.", synonym: "frankly" },
      { word: "basically", type: "adverb", meaning: "in the simplest way", hindi: "मूल रूप से", example: "It's basically the same.", synonym: "essentially" },
      { word: "actually", type: "adverb", meaning: "in fact", hindi: "वास्तव में", example: "Actually, I changed my mind.", synonym: "really" },
      { word: "definitely", type: "adverb", meaning: "certainly", hindi: "पक्का", example: "I'll definitely come.", synonym: "surely" },
      { word: "probably", type: "adverb", meaning: "likely", hindi: "शायद", example: "He'll probably win.", synonym: "perhaps" },
      { word: "seriously", type: "adverb", meaning: "really", hindi: "सच में", example: "Are you seriously leaving?", synonym: "really" },
      { word: "anyway", type: "adverb", meaning: "in any case", hindi: "वैसे भी", example: "Anyway, let's go.", synonym: "regardless" },
      { word: "buddy", type: "noun", meaning: "friend", hindi: "दोस्त", example: "Hey buddy, long time!", synonym: "pal" },
      { word: "folks", type: "noun", meaning: "people, family", hindi: "लोग", example: "My folks live in Pune.", synonym: "people" },
      { word: "wanna", type: "informal", meaning: "want to", hindi: "चाहता हूँ", example: "I wanna learn English.", synonym: "want to" },
      { word: "kinda", type: "informal", meaning: "somewhat", hindi: "थोड़ा", example: "I'm kinda tired.", synonym: "sort of" },
      { word: "gotta", type: "informal", meaning: "have to", hindi: "करना पड़ेगा", example: "I gotta go now.", synonym: "must" },
      { word: "vibes", type: "noun", meaning: "atmosphere", hindi: "माहौल", example: "This cafe has good vibes.", synonym: "mood" },
      { word: "no worries", type: "phrase", meaning: "it's okay", hindi: "कोई बात नहीं", example: "No worries, take your time.", synonym: "it's fine" },
      { word: "my bad", type: "phrase", meaning: "my mistake", hindi: "मेरी ग़लती", example: "My bad, I forgot.", synonym: "sorry" },
      { word: "hit me up", type: "phrase", meaning: "contact me", hindi: "संपर्क करना", example: "Hit me up tonight.", synonym: "call me" },
      { word: "lowkey", type: "adverb", meaning: "secretly", hindi: "चुपके से", example: "I lowkey love this song.", synonym: "secretly" },
      { word: "super", type: "adverb", meaning: "very", hindi: "बहुत", example: "It's super easy.", synonym: "very" },
      { word: "literally", type: "adverb", meaning: "exactly", hindi: "सचमुच", example: "I literally ran home.", synonym: "actually" },
      { word: "guess", type: "verb", meaning: "think without proof", hindi: "अनुमान", example: "I guess you're right.", synonym: "suppose" },
      { word: "meanwhile", type: "adverb", meaning: "at the same time", hindi: "इस बीच", example: "Meanwhile, wait here.", synonym: "in the meantime" },
    ],
  },
  {
    id: "interview", emoji: "👔", title: "Interview Words", desc: "Impress any interviewer",
    words: [
      { word: "persevere", type: "verb", meaning: "keep going despite difficulty", hindi: "लगे रहना", example: "She persevered and passed.", synonym: "persist" },
      { word: "punctual", type: "adjective", meaning: "on time", hindi: "समय का पाबंद", example: "He is always punctual.", synonym: "prompt" },
      { word: "collaborate", type: "verb", meaning: "work together", hindi: "सहयोग करना", example: "We collaborate daily.", synonym: "cooperate" },
      { word: "initiative", type: "noun", meaning: "first step, leadership", hindi: "पहल", example: "She took the initiative.", synonym: "drive" },
      { word: "diligent", type: "adjective", meaning: "hardworking", hindi: "परिश्रमी", example: "A diligent worker wins.", synonym: "hardworking" },
      { word: "adaptable", type: "adjective", meaning: "adjusts easily", hindi: "अनुकूलनीय", example: "I'm adaptable to change.", synonym: "flexible" },
      { word: "proactive", type: "adjective", meaning: "acts before problems", hindi: "सक्रिय", example: "Be proactive at work.", synonym: "initiating" },
      { word: "reliable", type: "adjective", meaning: "trustworthy", hindi: "भरोसेमंद", example: "She is reliable.", synonym: "dependable" },
      { word: "efficient", type: "adjective", meaning: "fast with no waste", hindi: "कुशल", example: "This method is efficient.", synonym: "productive" },
      { word: "versatile", type: "adjective", meaning: "skilled in many things", hindi: "बहुमुखी", example: "He is a versatile player.", synonym: "all-round" },
      { word: "meticulous", type: "adjective", meaning: "very careful with detail", hindi: "बारीक", example: "Meticulous planning helps.", synonym: "thorough" },
      { word: "innovative", type: "adjective", meaning: "new ideas", hindi: "नवोन्मेषी", example: "An innovative solution.", synonym: "creative" },
      { word: "articulate", type: "adjective", meaning: "speaks clearly", hindi: "स्पष्ट वक्ता", example: "She is articulate.", synonym: "eloquent" },
      { word: "strategic", type: "adjective", meaning: "planned for long term", hindi: "रणनीतिक", example: "A strategic decision.", synonym: "planned" },
      { word: "analytical", type: "adjective", meaning: "logical examination", hindi: "विश्लेषणात्मक", example: "Strong analytical skills.", synonym: "logical" },
      { word: "leadership", type: "noun", meaning: "leading others", hindi: "नेतृत्व", example: "Show leadership.", synonym: "guidance" },
      { word: "teamwork", type: "noun", meaning: "group effort", hindi: "टीम वर्क", example: "Teamwork wins games.", synonym: "cooperation" },
      { word: "deadline", type: "noun", meaning: "last time to finish", hindi: "समय सीमा", example: "Meet the deadline.", synonym: "time limit" },
      { word: "portfolio", type: "noun", meaning: "work collection", hindi: "कार्य संग्रह", example: "Show your portfolio.", synonym: "showcase" },
      { word: "accomplishment", type: "noun", meaning: "success", hindi: "उपलब्धि", example: "A big accomplishment.", synonym: "achievement" },
      { word: "challenge", type: "noun", meaning: "difficult task", hindi: "चुनौती", example: "I love a challenge.", synonym: "test" },
      { word: "opportunity", type: "noun", meaning: "good chance", hindi: "अवसर", example: "A golden opportunity.", synonym: "chance" },
      { word: "responsibility", type: "noun", meaning: "duty", hindi: "ज़िम्मेदारी", example: "Take responsibility.", synonym: "duty" },
      { word: "growth", type: "noun", meaning: "development", hindi: "विकास", example: "Focus on growth.", synonym: "progress" },
      { word: "contribute", type: "verb", meaning: "give, add value", hindi: "योगदान", example: "Contribute ideas.", synonym: "add" },
      { word: "implement", type: "verb", meaning: "put into action", hindi: "लागू करना", example: "Implement the plan.", synonym: "execute" },
      { word: "achieve", type: "verb", meaning: "reach a goal", hindi: "हासिल करना", example: "Achieve your targets.", synonym: "attain" },
      { word: "develop", type: "verb", meaning: "improve over time", hindi: "विकसित करना", example: "Develop new skills.", synonym: "build" },
      { word: "manage", type: "verb", meaning: "handle, control", hindi: "प्रबंधन", example: "Manage your time.", synonym: "handle" },
      { word: "coordinate", type: "verb", meaning: "organize together", hindi: "समन्वय", example: "Coordinate the event.", synonym: "organize" },
    ],
  },
  {
    id: "exam", emoji: "📝", title: "Exam & Academic", desc: "Words that appear in tests",
    words: [
      { word: "analyze", type: "verb", meaning: "examine in detail", hindi: "विश्लेषण", example: "Analyze the data.", synonym: "examine" },
      { word: "concise", type: "adjective", meaning: "short and clear", hindi: "संक्षिप्त", example: "Write a concise answer.", synonym: "brief" },
      { word: "evaluate", type: "verb", meaning: "judge quality", hindi: "मूल्यांकन", example: "Evaluate the results.", synonym: "assess" },
      { word: "hypothesis", type: "noun", meaning: "idea to test", hindi: "परिकल्पना", example: "Prove the hypothesis.", synonym: "theory" },
      { word: "comprehend", type: "verb", meaning: "understand fully", hindi: "समझना", example: "Comprehend the passage.", synonym: "grasp" },
      { word: "interpret", type: "verb", meaning: "explain meaning", hindi: "व्याख्या", example: "Interpret the graph.", synonym: "explain" },
      { word: "demonstrate", type: "verb", meaning: "show clearly", hindi: "प्रदर्शित", example: "Demonstrate the method.", synonym: "show" },
      { word: "significant", type: "adjective", meaning: "important", hindi: "महत्वपूर्ण", example: "A significant change.", synonym: "notable" },
      { word: "relevant", type: "adjective", meaning: "connected to topic", hindi: "प्रासंगिक", example: "Give relevant examples.", synonym: "related" },
      { word: "coherent", type: "adjective", meaning: "logical, clear", hindi: "सुसंगत", example: "A coherent essay.", synonym: "logical" },
      { word: "empirical", type: "adjective", meaning: "from observation", hindi: "प्रायोगिक", example: "Empirical evidence.", synonym: "observed" },
      { word: "theoretical", type: "adjective", meaning: "from theory", hindi: "सैद्धांतिक", example: "Theoretical knowledge.", synonym: "academic" },
      { word: "methodology", type: "noun", meaning: "system of methods", hindi: "कार्यप्रणाली", example: "Explain your methodology.", synonym: "approach" },
      { word: "conclusion", type: "noun", meaning: "final part", hindi: "निष्कर्ष", example: "Write a conclusion.", synonym: "ending" },
      { word: "premise", type: "noun", meaning: "base assumption", hindi: "आधार", example: "The premise is true.", synonym: "assumption" },
      { word: "correlation", type: "noun", meaning: "mutual relation", hindi: "सहसंबंध", example: "Correlation between X and Y.", synonym: "link" },
      { word: "implication", type: "noun", meaning: "possible result", hindi: "निहितार्थ", example: "Think of the implications.", synonym: "consequence" },
      { word: "context", type: "noun", meaning: "situation around", hindi: "संदर्भ", example: "Understand the context.", synonym: "background" },
      { word: "paradigm", type: "noun", meaning: "typical model", hindi: "प्रतिमान", example: "A new paradigm.", synonym: "model" },
      { word: "synthesize", type: "verb", meaning: "combine parts", hindi: "संश्लेषण", example: "Synthesize the ideas.", synonym: "combine" },
      { word: "critique", type: "verb", meaning: "judge carefully", hindi: "आलोचना", example: "Critique the article.", synonym: "review" },
      { word: "substantiate", type: "verb", meaning: "support with proof", hindi: "पुष्टि", example: "Substantiate your claim.", synonym: "prove" },
      { word: "extrapolate", type: "verb", meaning: "extend beyond known", hindi: "अनुमानित", example: "Extrapolate the trend.", synonym: "infer" },
      { word: "corroborate", type: "verb", meaning: "confirm", hindi: "समर्थन", example: "Evidence corroborates it.", synonym: "confirm" },
      { word: "contradict", type: "verb", meaning: "say opposite", hindi: "खंडन", example: "Don't contradict yourself.", synonym: "oppose" },
      { word: "delineate", type: "verb", meaning: "describe exactly", hindi: "चित्रण", example: "Delineate the process.", synonym: "outline" },
      { word: "elucidate", type: "verb", meaning: "make clear", hindi: "स्पष्ट करना", example: "Elucidate the concept.", synonym: "clarify" },
      { word: "postulate", type: "verb", meaning: "assume true", hindi: "मान लेना", example: "Postulate a cause.", synonym: "assume" },
      { word: "refute", type: "verb", meaning: "prove wrong", hindi: "खंडन करना", example: "Refute the argument.", synonym: "disprove" },
      { word: "infer", type: "verb", meaning: "conclude from proof", hindi: "अनुमान लगाना", example: "Infer the meaning.", synonym: "deduce" },
    ],
  },
  {
    id: "food", emoji: "🍕", title: "Food & Restaurant", desc: "Order & describe food like a pro",
    words: [
      { word: "delicious", type: "adjective", meaning: "very tasty", hindi: "स्वादिष्ट", example: "The curry is delicious.", synonym: "tasty" },
      { word: "spicy", type: "adjective", meaning: "hot with spices", hindi: "तीखा", example: "I love spicy food.", synonym: "hot" },
      { word: "bland", type: "adjective", meaning: "no taste", hindi: "फीका", example: "The soup is bland.", synonym: "tasteless" },
      { word: "sour", type: "adjective", meaning: "acidic taste", hindi: "खट्टा", example: "Lemons are sour.", synonym: "tangy" },
      { word: "bitter", type: "adjective", meaning: "sharp bad taste", hindi: "कड़वा", example: "Karela is bitter.", synonym: "acerbic" },
      { word: "salty", type: "adjective", meaning: "taste of salt", hindi: "नमकीन", example: "The chips are salty.", synonym: "briny" },
      { word: "savory", type: "adjective", meaning: "not sweet", hindi: "नमकीन पकवान", example: "A savory snack.", synonym: "spicy" },
      { word: "crispy", type: "adjective", meaning: "crunchy", hindi: "कुरकुरा", example: "Crispy onions.", synonym: "crunchy" },
      { word: "juicy", type: "adjective", meaning: "full of liquid", hindi: "रसीला", example: "A juicy mango.", synonym: "succulent" },
      { word: "tender", type: "adjective", meaning: "soft, easy to cut", hindi: "नरम", example: "Tender chicken.", synonym: "soft" },
      { word: "stale", type: "adjective", meaning: "not fresh", hindi: "बासी", example: "Stale bread.", synonym: "old" },
      { word: "fresh", type: "adjective", meaning: "just made", hindi: "ताज़ा", example: "Fresh vegetables.", synonym: "new" },
      { word: "homemade", type: "adjective", meaning: "made at home", hindi: "घर का बना", example: "Homemade food is best.", synonym: "home-cooked" },
      { word: "takeaway", type: "noun", meaning: "food to go", hindi: "पैक कराकर ले जाना", example: "Order a takeaway.", synonym: "to-go" },
      { word: "leftovers", type: "noun", meaning: "remaining food", hindi: "बचा हुआ खाना", example: "Eat the leftovers.", synonym: "remains" },
      { word: "recipe", type: "noun", meaning: "cooking method", hindi: "रेसिपी", example: "Share the recipe.", synonym: "method" },
      { word: "ingredient", type: "noun", meaning: "item in a dish", hindi: "सामग्री", example: "Fresh ingredients.", synonym: "component" },
      { word: "cuisine", type: "noun", meaning: "style of cooking", hindi: "व्यंजन शैली", example: "Indian cuisine.", synonym: "cooking" },
      { word: "portion", type: "noun", meaning: "amount served", hindi: "हिस्सा", example: "A small portion.", synonym: "serving" },
      { word: "snack", type: "noun", meaning: "small meal", hindi: "नाश्ता", example: "A light snack.", synonym: "bite" },
      { word: "dessert", type: "noun", meaning: "sweet after meal", hindi: "मिठाई", example: "Gulab jamun for dessert.", synonym: "sweet" },
      { word: "beverage", type: "noun", meaning: "drink", hindi: "पेय", example: "A cold beverage.", synonym: "drink" },
      { word: "appetite", type: "noun", meaning: "hunger", hindi: "भूख", example: "Good appetite!", synonym: "hunger" },
      { word: "craving", type: "noun", meaning: "strong desire", hindi: "तलब", example: "A craving for pizza.", synonym: "longing" },
      { word: "mouth-watering", type: "adjective", meaning: "looks delicious", hindi: "मुँह में पानी लाने वाला", example: "Mouth-watering biryani.", synonym: "appetizing" },
      { word: "flavor", type: "noun", meaning: "taste", hindi: "स्वाद", example: "Rich flavor.", synonym: "taste" },
      { word: "seasoning", type: "noun", meaning: "salt/spices added", hindi: "मसाला", example: "Add seasoning.", synonym: "spices" },
      { word: "boil", type: "verb", meaning: "cook in hot water", hindi: "उबालना", example: "Boil the milk.", synonym: "cook" },
      { word: "fry", type: "verb", meaning: "cook in oil", hindi: "तलना", example: "Fry the onions.", synonym: "sauté" },
      { word: "roast", type: "verb", meaning: "cook with dry heat", hindi: "भूनना", example: "Roast the papad.", synonym: "bake" },
    ],
  },
  {
    id: "travel", emoji: "✈️", title: "Travel & Airport", desc: "Confident at stations & airports",
    words: [
      { word: "journey", type: "noun", meaning: "act of traveling", hindi: "यात्रा", example: "A long journey.", synonym: "trip" },
      { word: "destination", type: "noun", meaning: "place you go to", hindi: "मंज़िल", example: "Our destination is Goa.", synonym: "goal" },
      { word: "itinerary", type: "noun", meaning: "travel plan", hindi: "यात्रा योजना", example: "Check the itinerary.", synonym: "schedule" },
      { word: "luggage", type: "noun", meaning: "bags you carry", hindi: "सामान", example: "Heavy luggage.", synonym: "baggage" },
      { word: "passport", type: "noun", meaning: "travel ID", hindi: "पासपोर्ट", example: "Keep your passport safe.", synonym: "ID" },
      { word: "visa", type: "noun", meaning: "entry permission", hindi: "वीज़ा", example: "Apply for a visa.", synonym: "permit" },
      { word: "customs", type: "noun", meaning: "airport check", hindi: "सीमा शुल्क", example: "Clear customs.", synonym: "check" },
      { word: "boarding", type: "noun", meaning: "getting on", hindi: "सवार होना", example: "Boarding starts now.", synonym: "entry" },
      { word: "departure", type: "noun", meaning: "leaving", hindi: "प्रस्थान", example: "Departure at 6 PM.", synonym: "leaving" },
      { word: "arrival", type: "noun", meaning: "reaching", hindi: "आगमन", example: "Arrival hall.", synonym: "coming" },
      { word: "delay", type: "noun", meaning: "late", hindi: "देरी", example: "A flight delay.", synonym: "hold-up" },
      { word: "cancel", type: "verb", meaning: "stop plan", hindi: "रद्द", example: "Cancel the ticket.", synonym: "call off" },
      { word: "reserve", type: "verb", meaning: "book", hindi: "आरक्षित", example: "Reserve a seat.", synonym: "book" },
      { word: "fare", type: "noun", meaning: "ticket price", hindi: "किराया", example: "Bus fare is high.", synonym: "price" },
      { word: "refund", type: "noun", meaning: "money back", hindi: "वापसी", example: "Get a refund.", synonym: "return" },
      { word: "sightseeing", type: "noun", meaning: "visiting places", hindi: "सैर-सपाटा", example: "Go sightseeing.", synonym: "touring" },
      { word: "landmark", type: "noun", meaning: "famous place", hindi: "प्रसिद्ध स्थल", example: "A historic landmark.", synonym: "monument" },
      { word: "souvenir", type: "noun", meaning: "gift from trip", hindi: "स्मृति चिन्ह", example: "Buy a souvenir.", synonym: "keepsake" },
      { word: "abroad", type: "adverb", meaning: "in another country", hindi: "विदेश", example: "Study abroad.", synonym: "overseas" },
      { word: "commute", type: "verb", meaning: "daily travel", hindi: "आना-जाना", example: "I commute by train.", synonym: "travel" },
      { word: "transfer", type: "verb", meaning: "change vehicle", hindi: "बदलना", example: "Transfer at Dadar.", synonym: "switch" },
      { word: "accommodation", type: "noun", meaning: "place to stay", hindi: "रहने की जगह", example: "Book accommodation.", synonym: "lodging" },
      { word: "explore", type: "verb", meaning: "discover", hindi: "खोजना", example: "Explore the city.", synonym: "discover" },
      { word: "guide", type: "noun", meaning: "person who shows", hindi: "गाइड", example: "Hire a guide.", synonym: "leader" },
      { word: "map", type: "noun", meaning: "area diagram", hindi: "नक्शा", example: "Open the map.", synonym: "chart" },
      { word: "route", type: "noun", meaning: "way to go", hindi: "मार्ग", example: "The fastest route.", synonym: "path" },
      { word: "platform", type: "noun", meaning: "train stop area", hindi: "प्लेटफ़ॉर्म", example: "Platform number 4.", synonym: "stand" },
      { word: "ticket", type: "noun", meaning: "travel pass", hindi: "टिकट", example: "Buy a ticket.", synonym: "pass" },
      { word: "window seat", type: "noun", meaning: "seat by window", hindi: "खिड़की वाली सीट", example: "I prefer a window seat.", synonym: "side seat" },
      { word: "aisle seat", type: "noun", meaning: "seat by walkway", hindi: "गलियारे वाली सीट", example: "An aisle seat please.", synonym: "walkway seat" },
    ],
  },
];