import { Pack } from "./dataA";

export const PACKS_C: Pack[] = [
  {
    id: "shopping", emoji: "🛍️", title: "Shopping & Money", desc: "Bargain like a pro",
    words: [
      { word: "shop", type: "verb", meaning: "buy things", hindi: "खरीदारी", example: "We shop on Sundays.", synonym: "buy" },
      { word: "market", type: "noun", meaning: "place to buy", hindi: "बाज़ार", example: "The market is busy.", synonym: "bazaar" },
      { word: "mall", type: "noun", meaning: "big shopping center", hindi: "मॉल", example: "New mall in town.", synonym: "center" },
      { word: "store", type: "noun", meaning: "place that sells", hindi: "दुकान", example: "A grocery store.", synonym: "shop" },
      { word: "price", type: "noun", meaning: "money needed", hindi: "कीमत", example: "The price is high.", synonym: "cost" },
      { word: "cheap", type: "adjective", meaning: "low price", hindi: "सस्ता", example: "A cheap phone.", synonym: "inexpensive" },
      { word: "expensive", type: "adjective", meaning: "high price", hindi: "महंगा", example: "This watch is expensive.", synonym: "costly" },
      { word: "discount", type: "noun", meaning: "price cut", hindi: "छूट", example: "50% discount today!", synonym: "reduction" },
      { word: "offer", type: "noun", meaning: "special deal", hindi: "ऑफर", example: "A buy-1-get-1 offer.", synonym: "deal" },
      { word: "sale", type: "noun", meaning: "selling at low price", hindi: "बिक्री", example: "The Diwali sale is on.", synonym: "clearance" },
      { word: "bargain", type: "verb", meaning: "argue for lower price", hindi: "मोलभाव", example: "Bargain at the market.", synonym: "haggle" },
      { word: "bill", type: "noun", meaning: "paper of total cost", hindi: "बिल", example: "Pay the bill.", synonym: "invoice" },
      { word: "receipt", type: "noun", meaning: "proof of payment", hindi: "रसीद", example: "Keep the receipt.", synonym: "proof" },
      { word: "cash", type: "noun", meaning: "paper money", hindi: "नकद", example: "Pay by cash.", synonym: "money" },
      { word: "card", type: "noun", meaning: "plastic payment", hindi: "कार्ड", example: "Swipe the card.", synonym: "plastic" },
      { word: "change", type: "noun", meaning: "money back", hindi: "चिल्लर", example: "Keep the change.", synonym: "coins" },
      { word: "refund", type: "noun", meaning: "money returned", hindi: "वापसी", example: "Ask for a refund.", synonym: "return" },
      { word: "exchange", type: "verb", meaning: "swap items", hindi: "अदला-बदली", example: "Exchange the size.", synonym: "swap" },
      { word: "return", type: "verb", meaning: "give back", hindi: "लौटाना", example: "Return the shirt.", synonym: "give back" },
      { word: "size", type: "noun", meaning: "how big", hindi: "आकार", example: "My size is M.", synonym: "measure" },
      { word: "color", type: "noun", meaning: "shade", hindi: "रंग", example: "I like this color.", synonym: "shade" },
      { word: "brand", type: "noun", meaning: "company name", hindi: "ब्रांड", example: "A famous brand.", synonym: "label" },
      { word: "quality", type: "noun", meaning: "how good", hindi: "गुणवत्ता", example: "Good quality cloth.", synonym: "standard" },
      { word: "quantity", type: "noun", meaning: "how much", hindi: "मात्रा", example: "A small quantity.", synonym: "amount" },
      { word: "budget", type: "noun", meaning: "money plan", hindi: "बजट", example: "Stay in budget.", synonym: "plan" },
      { word: "save", type: "verb", meaning: "keep money", hindi: "बचाना", example: "Save every month.", synonym: "store" },
      { word: "spend", type: "verb", meaning: "use money", hindi: "खर्च करना", example: "Don't spend it all.", synonym: "pay" },
      { word: "earn", type: "verb", meaning: "get money by work", hindi: "कमाना", example: "Earn with skill.", synonym: "make" },
      { word: "loan", type: "noun", meaning: "borrowed money", hindi: "ऋण", example: "A small bank loan.", synonym: "borrow" },
      { word: "debt", type: "noun", meaning: "money you owe", hindi: "कर्ज़", example: "Clear your debt.", synonym: "owing" },
    ],
  },
  {
    id: "sports", emoji: "🏏", title: "Sports & Fitness", desc: "Talk about games & gym",
    words: [
      { word: "player", type: "noun", meaning: "person who plays", hindi: "खिलाड़ी", example: "A great player.", synonym: "athlete" },
      { word: "team", type: "noun", meaning: "group playing together", hindi: "टीम", example: "Our team won.", synonym: "side" },
      { word: "match", type: "noun", meaning: "game event", hindi: "मैच", example: "The match is tonight.", synonym: "game" },
      { word: "score", type: "noun", meaning: "points made", hindi: "स्कोर", example: "The score is 2-1.", synonym: "points" },
      { word: "win", type: "verb", meaning: "be the winner", hindi: "जीतना", example: "We will win.", synonym: "triumph" },
      { word: "lose", type: "verb", meaning: "not win", hindi: "हारना", example: "Never lose hope.", synonym: "fail" },
      { word: "draw", type: "noun", meaning: "equal result", hindi: "बराबरी", example: "The match was a draw.", synonym: "tie" },
      { word: "champion", type: "noun", meaning: "winner", hindi: "विजेता", example: "The world champion.", synonym: "winner" },
      { word: "trophy", type: "noun", meaning: "prize cup", hindi: "ट्रॉफी", example: "Lift the trophy.", synonym: "cup" },
      { word: "tournament", type: "noun", meaning: "many matches", hindi: "टूर्नामेंट", example: "A cricket tournament.", synonym: "competition" },
      { word: "league", type: "noun", meaning: "group of teams", hindi: "लीग", example: "The football league.", synonym: "series" },
      { word: "coach", type: "noun", meaning: "trainer", hindi: "कोच", example: "The coach is strict.", synonym: "trainer" },
      { word: "referee", type: "noun", meaning: "rule judge", hindi: "रेफरी", example: "Ask the referee.", synonym: "umpire" },
      { word: "stadium", type: "noun", meaning: "big sports place", hindi: "स्टेडियम", example: "A full stadium.", synonym: "arena" },
      { word: "field", type: "noun", meaning: "grass play area", hindi: "मैदान", example: "Run on the field.", synonym: "ground" },
      { word: "court", type: "noun", meaning: "play area for tennis", hindi: "कोर्ट", example: "A tennis court.", synonym: "area" },
      { word: "goal", type: "noun", meaning: "score in football", hindi: "गोल", example: "He scored a goal.", synonym: "score" },
      { word: "point", type: "noun", meaning: "one score unit", hindi: "अंक", example: "We need one point.", synonym: "mark" },
      { word: "practice", type: "verb", meaning: "train regularly", hindi: "अभ्यास", example: "Practice every day.", synonym: "train" },
      { word: "gym", type: "noun", meaning: "exercise place", hindi: "जिम", example: "Go to the gym.", synonym: "fitness center" },
      { word: "workout", type: "noun", meaning: "exercise session", hindi: "कसरत", example: "A morning workout.", synonym: "exercise" },
      { word: "warm-up", type: "noun", meaning: "light start exercise", hindi: "वार्म-अप", example: "Do a warm-up first.", synonym: "stretch" },
      { word: "stretch", type: "verb", meaning: "extend body", hindi: "खिंचाव", example: "Stretch your arms.", synonym: "extend" },
      { word: "fitness", type: "noun", meaning: "body health", hindi: "फिटनेस", example: "Focus on fitness.", synonym: "health" },
      { word: "strength", type: "noun", meaning: "body power", hindi: "ताकत", example: "Build your strength.", synonym: "power" },
      { word: "stamina", type: "noun", meaning: "lasting energy", hindi: "सहनशक्ति", example: "Running builds stamina.", synonym: "endurance" },
      { word: "speed", type: "noun", meaning: "how fast", hindi: "गति", example: "He runs with speed.", synonym: "pace" },
      { word: "medal", type: "noun", meaning: "prize disc", hindi: "पदक", example: "She won a gold medal.", synonym: "award" },
      { word: "opponent", type: "noun", meaning: "other side player", hindi: "प्रतिद्वंद्वी", example: "Respect your opponent.", synonym: "rival" },
      { word: "fan", type: "noun", meaning: "supporter", hindi: "प्रशंसक", example: "I'm a big cricket fan.", synonym: "supporter" },
    ],
  },
  {
    id: "movies", emoji: "🎬", title: "Movies & Music", desc: "Discuss films & songs",
    words: [
      { word: "movie", type: "noun", meaning: "film", hindi: "फिल्म", example: "Let's watch a movie.", synonym: "film" },
      { word: "actor", type: "noun", meaning: "man who acts", hindi: "अभिनेता", example: "A famous actor.", synonym: "star" },
      { word: "actress", type: "noun", meaning: "woman who acts", hindi: "अभिनेत्री", example: "A talented actress.", synonym: "star" },
      { word: "director", type: "noun", meaning: "film maker", hindi: "निर्देशक", example: "The director won an award.", synonym: "maker" },
      { word: "scene", type: "noun", meaning: "part of a film", hindi: "दृश्य", example: "A funny scene.", synonym: "part" },
      { word: "story", type: "noun", meaning: "tale", hindi: "कहानी", example: "A lovely story.", synonym: "tale" },
      { word: "plot", type: "noun", meaning: "story plan", hindi: "कथानक", example: "The plot is strong.", synonym: "storyline" },
      { word: "hero", type: "noun", meaning: "main good man", hindi: "नायक", example: "The hero saves all.", synonym: "lead" },
      { word: "villain", type: "noun", meaning: "bad person", hindi: "खलनायक", example: "The villain loses.", synonym: "baddie" },
      { word: "comedy", type: "noun", meaning: "funny film", hindi: "कॉमेडी", example: "I love comedy.", synonym: "humor" },
      { word: "tragedy", type: "noun", meaning: "sad story", hindi: "दुखांत", example: "A deep tragedy.", synonym: "sad story" },
      { word: "drama", type: "noun", meaning: "serious story", hindi: "ड्रामा", example: "A family drama.", synonym: "play" },
      { word: "song", type: "noun", meaning: "music with words", hindi: "गाना", example: "A sweet song.", synonym: "track" },
      { word: "singer", type: "noun", meaning: "person who sings", hindi: "गायक", example: "A playback singer.", synonym: "vocalist" },
      { word: "album", type: "noun", meaning: "song collection", hindi: "एल्बम", example: "A new music album.", synonym: "record" },
      { word: "tune", type: "noun", meaning: "melody", hindi: "धुन", example: "A catchy tune.", synonym: "melody" },
      { word: "melody", type: "noun", meaning: "pleasant sound", hindi: "मधुर धुन", example: "A soft melody.", synonym: "harmony" },
      { word: "lyric", type: "noun", meaning: "song words", hindi: "बोल", example: "Beautiful lyrics.", synonym: "words" },
      { word: "band", type: "noun", meaning: "music group", hindi: "बैंड", example: "A rock band.", synonym: "group" },
      { word: "concert", type: "noun", meaning: "live music show", hindi: "कंसर्ट", example: "A night concert.", synonym: "show" },
      { word: "stage", type: "noun", meaning: "performance place", hindi: "मंच", example: "Dance on stage.", synonym: "platform" },
      { word: "dance", type: "verb", meaning: "move to music", hindi: "नाचना", example: "Dance to the beat.", synonym: "move" },
      { word: "rhythm", type: "noun", meaning: "music pattern", hindi: "लय", example: "A fast rhythm.", synonym: "beat" },
      { word: "beat", type: "noun", meaning: "music pulse", hindi: "ताल", example: "Feel the beat.", synonym: "pulse" },
      { word: "voice", type: "noun", meaning: "sound of person", hindi: "आवाज़", example: "A golden voice.", synonym: "tone" },
      { word: "instrument", type: "noun", meaning: "music tool", hindi: "वाद्ययंत्र", example: "Play an instrument.", synonym: "tool" },
      { word: "guitar", type: "noun", meaning: "string instrument", hindi: "गिटार", example: "He plays guitar.", synonym: "strings" },
      { word: "piano", type: "noun", meaning: "key instrument", hindi: "पियानो", example: "Learn the piano.", synonym: "keys" },
      { word: "ticket", type: "noun", meaning: "entry pass", hindi: "टिकट", example: "Book two tickets.", synonym: "pass" },
      { word: "interval", type: "noun", meaning: "break in movie", hindi: "अंतराल", example: "Tea at interval.", synonym: "intermission" },
    ],
  },
  {
    id: "family", emoji: "🏠", title: "Home & Family", desc: "Talk about your people",
    words: [
      { word: "family", type: "noun", meaning: "your people", hindi: "परिवार", example: "I love my family.", synonym: "relatives" },
      { word: "mother", type: "noun", meaning: "female parent", hindi: "माँ", example: "My mother cooks well.", synonym: "mom" },
      { word: "father", type: "noun", meaning: "male parent", hindi: "पिता", example: "My father works hard.", synonym: "dad" },
      { word: "brother", type: "noun", meaning: "male sibling", hindi: "भाई", example: "My brother studies.", synonym: "bhai" },
      { word: "sister", type: "noun", meaning: "female sibling", hindi: "बहन", example: "My sister sings well.", synonym: "behen" },
      { word: "son", type: "noun", meaning: "male child", hindi: "बेटा", example: "Their son is tall.", synonym: "boy" },
      { word: "daughter", type: "noun", meaning: "female child", hindi: "बेटी", example: "Their daughter is a doctor.", synonym: "girl" },
      { word: "uncle", type: "noun", meaning: "father's brother", hindi: "चाचा/मामा", example: "My uncle lives in Delhi.", synonym: "relative" },
      { word: "aunt", type: "noun", meaning: "father's sister", hindi: "चाची/मामी", example: "My aunt makes great food.", synonym: "relative" },
      { word: "cousin", type: "noun", meaning: "uncle's child", hindi: "चचेरा/ममेरा भाई", example: "My cousin is my friend.", synonym: "relative" },
      { word: "nephew", type: "noun", meaning: "brother's son", hindi: "भतीजा", example: "My nephew is cute.", synonym: "relative" },
      { word: "niece", type: "noun", meaning: "brother's daughter", hindi: "भतीजी", example: "My niece draws well.", synonym: "relative" },
      { word: "grandfather", type: "noun", meaning: "father's father", hindi: "दादा/नाना", example: "My grandfather tells stories.", synonym: "grandpa" },
      { word: "grandmother", type: "noun", meaning: "father's mother", hindi: "दादी/नानी", example: "My grandmother sings to me.", synonym: "grandma" },
      { word: "husband", type: "noun", meaning: "married man", hindi: "पति", example: "Her husband is a teacher.", synonym: "spouse" },
      { word: "wife", type: "noun", meaning: "married woman", hindi: "पत्नी", example: "His wife is a nurse.", synonym: "spouse" },
      { word: "parent", type: "noun", meaning: "mother or father", hindi: "अभिभावक", example: "My parents support me.", synonym: "guardian" },
      { word: "child", type: "noun", meaning: "young person", hindi: "बच्चा", example: "The child is sleeping.", synonym: "kid" },
      { word: "kids", type: "noun", meaning: "children", hindi: "बच्चे", example: "The kids are playing.", synonym: "children" },
      { word: "home", type: "noun", meaning: "where you live", hindi: "घर", example: "Home is where love is.", synonym: "house" },
      { word: "room", type: "noun", meaning: "part of house", hindi: "कमरा", example: "A clean room.", synonym: "space" },
      { word: "kitchen", type: "noun", meaning: "cooking room", hindi: "रसोई", example: "Cook in the kitchen.", synonym: "cooking area" },
      { word: "bedroom", type: "noun", meaning: "sleeping room", hindi: "शयनकक्ष", example: "Two bedrooms.", synonym: "sleeping room" },
      { word: "bathroom", type: "noun", meaning: "washing room", hindi: "बाथरूम", example: "Clean the bathroom.", synonym: "washroom" },
      { word: "garden", type: "noun", meaning: "plant area", hindi: "बगीचा", example: "Flowers in the garden.", synonym: "yard" },
      { word: "furniture", type: "noun", meaning: "tables, chairs", hindi: "फर्नीचर", example: "New furniture.", synonym: "fixtures" },
      { word: "neighbor", type: "noun", meaning: "person near home", hindi: "पड़ोसी", example: "A helpful neighbor.", synonym: "next-door" },
      { word: "guest", type: "noun", meaning: "visitor", hindi: "मेहमान", example: "We have guests today.", synonym: "visitor" },
      { word: "relative", type: "noun", meaning: "family member", hindi: "रिश्तेदार", example: "Relatives came for Diwali.", synonym: "kin" },
      { word: "household", type: "noun", meaning: "home and people", hindi: "गृहस्थी", example: "Household work is tiring.", synonym: "home" },
    ],
  },
  {
    id: "festivals", emoji: "🎉", title: "Festivals & Culture", desc: "Celebrate in English",
    words: [
      { word: "festival", type: "noun", meaning: "celebration day", hindi: "त्योहार", example: "Diwali is my favorite festival.", synonym: "celebration" },
      { word: "celebration", type: "noun", meaning: "party for event", hindi: "जश्न", example: "A big celebration.", synonym: "party" },
      { word: "ceremony", type: "noun", meaning: "formal event", hindi: "समारोह", example: "A wedding ceremony.", synonym: "function" },
      { word: "tradition", type: "noun", meaning: "old custom", hindi: "परंपरा", example: "Follow the tradition.", synonym: "custom" },
      { word: "custom", type: "noun", meaning: "usual practice", hindi: "रीति", example: "A local custom.", synonym: "habit" },
      { word: "ritual", type: "noun", meaning: "religious act", hindi: "अनुष्ठान", example: "Morning rituals.", synonym: "rite" },
      { word: "culture", type: "noun", meaning: "way of life", hindi: "संस्कृति", example: "Indian culture is rich.", synonym: "heritage" },
      { word: "prayer", type: "noun", meaning: "talk to God", hindi: "प्रार्थना", example: "Say a prayer.", synonym: "worship" },
      { word: "temple", type: "noun", meaning: "Hindu worship place", hindi: "मंदिर", example: "Visit the temple.", synonym: "shrine" },
      { word: "gift", type: "noun", meaning: "present", hindi: "उपहार", example: "A lovely gift.", synonym: "present" },
      { word: "decoration", type: "noun", meaning: "making pretty", hindi: "सजावट", example: "Beautiful decoration.", synonym: "ornament" },
      { word: "firework", type: "noun", meaning: "light burst in sky", hindi: "आतिशबाज़ी", example: "Fireworks at night.", synonym: "crackers" },
      { word: "costume", type: "noun", meaning: "special dress", hindi: "पोशाक", example: "A traditional costume.", synonym: "outfit" },
      { word: "parade", type: "noun", meaning: "walking show", hindi: "शोभायात्रा", example: "A street parade.", synonym: "procession" },
      { word: "fair", type: "noun", meaning: "fun market event", hindi: "मेला", example: "A village fair.", synonym: "mela" },
      { word: "holiday", type: "noun", meaning: "day off", hindi: "छुट्टी", example: "A long holiday.", synonym: "vacation" },
      { word: "feast", type: "noun", meaning: "big meal", hindi: "भोज", example: "A festival feast.", synonym: "banquet" },
      { word: "fast", type: "verb", meaning: "not eating", hindi: "व्रत", example: "She fasts on Mondays.", synonym: "vrata" },
      { word: "blessing", type: "noun", meaning: "good wish", hindi: "आशीर्वाद", example: "Take elders' blessings.", synonym: "wish" },
      { word: "gathering", type: "noun", meaning: "people meeting", hindi: "इकट्ठा", example: "A family gathering.", synonym: "meeting" },
      { word: "community", type: "noun", meaning: "group of people", hindi: "समुदाय", example: "A strong community.", synonym: "society" },
      { word: "heritage", type: "noun", meaning: "old valuable things", hindi: "विरासत", example: "Protect our heritage.", synonym: "legacy" },
      { word: "art", type: "noun", meaning: "creative work", hindi: "कला", example: "Folk art is lovely.", synonym: "craft" },
      { word: "craft", type: "noun", meaning: "handmade skill", hindi: "शिल्प", example: "Buy local crafts.", synonym: "handwork" },
      { word: "folk", type: "adjective", meaning: "of common people", hindi: "लोक", example: "Folk songs are sweet.", synonym: "traditional" },
      { word: "legend", type: "noun", meaning: "old famous story", hindi: "किंवदंती", example: "A village legend.", synonym: "myth" },
      { word: "history", type: "noun", meaning: "past events", hindi: "इतिहास", example: "Learn our history.", synonym: "past" },
      { word: "symbol", type: "noun", meaning: "sign of idea", hindi: "प्रतीक", example: "A diya is a symbol of light.", synonym: "sign" },
      { word: "flag", type: "noun", meaning: "country cloth", hindi: "झंडा", example: "Hoist the flag.", synonym: "banner" },
      { word: "sweet", type: "noun", meaning: "festival food", hindi: "मिठाई", example: "Share sweets.", synonym: "dessert" },
    ],
  },
];