import { Pack } from "./dataA";

export const PACKS_C: Pack[] = [
  {
    id: "shopping", emoji: "🛍️", title: "Shopping & Money", desc: "Bargain like a pro",
    words: [
      { word: "shop", type: "verb", meaning: "buy things", hindi: "खरीदारी", example: "We shop on Sundays.", synonym: "buy", antonym: "sell" },
      { word: "market", type: "noun", meaning: "place to buy", hindi: "बाज़ार", example: "The market is busy.", synonym: "bazaar", antonym: "" },
      { word: "mall", type: "noun", meaning: "big shopping center", hindi: "मॉल", example: "New mall in town.", synonym: "center", antonym: "" },
      { word: "store", type: "noun", meaning: "place that sells", hindi: "दुकान", example: "A grocery store.", synonym: "shop", antonym: "" },
      { word: "price", type: "noun", meaning: "money needed", hindi: "कीमत", example: "The price is high.", synonym: "cost", antonym: "" },
      { word: "cheap", type: "adjective", meaning: "low price", hindi: "सस्ता", example: "A cheap phone.", synonym: "inexpensive", antonym: "expensive" },
      { word: "expensive", type: "adjective", meaning: "high price", hindi: "महंगा", example: "This watch is expensive.", synonym: "costly", antonym: "cheap" },
      { word: "discount", type: "noun", meaning: "price cut", hindi: "छूट", example: "50% discount today!", synonym: "reduction", antonym: "markup" },
      { word: "offer", type: "noun", meaning: "special deal", hindi: "ऑफर", example: "A buy-1-get-1 offer.", synonym: "deal", antonym: "" },
      { word: "sale", type: "noun", meaning: "selling at low price", hindi: "बिक्री", example: "The Diwali sale is on.", synonym: "clearance", antonym: "" },
      { word: "bargain", type: "verb", meaning: "argue for lower price", hindi: "मोलभाव", example: "Bargain at the market.", synonym: "haggle", antonym: "overpay" },
      { word: "bill", type: "noun", meaning: "paper of total cost", hindi: "बिल", example: "Pay the bill.", synonym: "invoice", antonym: "" },
      { word: "receipt", type: "noun", meaning: "proof of payment", hindi: "रसीद", example: "Keep the receipt.", synonym: "proof", antonym: "" },
      { word: "cash", type: "noun", meaning: "paper money", hindi: "नकद", example: "Pay by cash.", synonym: "money", antonym: "credit" },
      { word: "card", type: "noun", meaning: "plastic payment", hindi: "कार्ड", example: "Swipe the card.", synonym: "plastic", antonym: "cash" },
      { word: "change", type: "noun", meaning: "money back", hindi: "चिल्लर", example: "Keep the change.", synonym: "coins", antonym: "exact amount" },
      { word: "refund", type: "noun", meaning: "money returned", hindi: "वापसी", example: "Ask for a refund.", synonym: "return", antonym: "charge" },
      { word: "exchange", type: "verb", meaning: "swap items", hindi: "अदला-बदली", example: "Exchange the size.", synonym: "swap", antonym: "keep" },
      { word: "return", type: "verb", meaning: "give back", hindi: "लौटाना", example: "Return the shirt.", synonym: "give back", antonym: "keep" },
      { word: "size", type: "noun", meaning: "how big", hindi: "आकार", example: "My size is M.", synonym: "measure", antonym: "" },
      { word: "color", type: "noun", meaning: "shade", hindi: "रंग", example: "I like this color.", synonym: "shade", antonym: "" },
      { word: "brand", type: "noun", meaning: "company name", hindi: "ब्रांड", example: "A famous brand.", synonym: "label", antonym: "generic" },
      { word: "quality", type: "noun", meaning: "how good", hindi: "गुणवत्ता", example: "Good quality cloth.", synonym: "standard", antonym: "" },
      { word: "quantity", type: "noun", meaning: "how much", hindi: "मात्रा", example: "A small quantity.", synonym: "amount", antonym: "" },
      { word: "budget", type: "noun", meaning: "money plan", hindi: "बजट", example: "Stay in budget.", synonym: "plan", antonym: "" },
      { word: "save", type: "verb", meaning: "keep money", hindi: "बचाना", example: "Save every month.", synonym: "store", antonym: "spend" },
      { word: "spend", type: "verb", meaning: "use money", hindi: "खर्च करना", example: "Don't spend it all.", synonym: "pay", antonym: "save" },
      { word: "earn", type: "verb", meaning: "get money by work", hindi: "कमाना", example: "Earn with skill.", synonym: "make", antonym: "lose" },
      { word: "loan", type: "noun", meaning: "borrowed money", hindi: "ऋण", example: "A small bank loan.", synonym: "borrow", antonym: "" },
      { word: "debt", type: "noun", meaning: "money you owe", hindi: "कर्ज़", example: "Clear your debt.", synonym: "owing", antonym: "credit" },
    ],
  },
  {
    id: "sports", emoji: "🏏", title: "Sports & Fitness", desc: "Talk about games & gym",
    words: [
      { word: "player", type: "noun", meaning: "person who plays", hindi: "खिलाड़ी", example: "A great player.", synonym: "athlete", antonym: "spectator" },
      { word: "team", type: "noun", meaning: "group playing together", hindi: "टीम", example: "Our team won.", synonym: "side", antonym: "individual" },
      { word: "match", type: "noun", meaning: "game event", hindi: "मैच", example: "The match is tonight.", synonym: "game", antonym: "practice" },
      { word: "score", type: "noun", meaning: "points made", hindi: "स्कोर", example: "The score is 2-1.", synonym: "points", antonym: "" },
      { word: "win", type: "verb", meaning: "be the winner", hindi: "जीतना", example: "We will win.", synonym: "triumph", antonym: "lose" },
      { word: "lose", type: "verb", meaning: "not win", hindi: "हारना", example: "Never lose hope.", synonym: "fail", antonym: "win" },
      { word: "draw", type: "noun", meaning: "equal result", hindi: "बराबरी", example: "The match was a draw.", synonym: "tie", antonym: "win" },
      { word: "champion", type: "noun", meaning: "winner", hindi: "विजेता", example: "The world champion.", synonym: "winner", antonym: "loser" },
      { word: "trophy", type: "noun", meaning: "prize cup", hindi: "ट्रॉफी", example: "Lift the trophy.", synonym: "cup", antonym: "" },
      { word: "tournament", type: "noun", meaning: "many matches", hindi: "टूर्नामेंट", example: "A cricket tournament.", synonym: "competition", antonym: "" },
      { word: "league", type: "noun", meaning: "group of teams", hindi: "लीग", example: "The football league.", synonym: "series", antonym: "" },
      { word: "coach", type: "noun", meaning: "trainer", hindi: "कोच", example: "The coach is strict.", synonym: "trainer", antonym: "player" },
      { word: "referee", type: "noun", meaning: "rule judge", hindi: "रेफरी", example: "Ask the referee.", synonym: "umpire", antonym: "player" },
      { word: "stadium", type: "noun", meaning: "big sports place", hindi: "स्टेडियम", example: "A full stadium.", synonym: "arena", antonym: "" },
      { word: "field", type: "noun", meaning: "grass play area", hindi: "मैदान", example: "Run on the field.", synonym: "ground", antonym: "" },
      { word: "court", type: "noun", meaning: "play area for tennis", hindi: "कोर्ट", example: "A tennis court.", synonym: "area", antonym: "" },
      { word: "goal", type: "noun", meaning: "score in football", hindi: "गोल", example: "He scored a goal.", synonym: "score", antonym: "" },
      { word: "point", type: "noun", meaning: "one score unit", hindi: "अंक", example: "We need one point.", synonym: "mark", antonym: "" },
      { word: "practice", type: "verb", meaning: "train regularly", hindi: "अभ्यास", example: "Practice every day.", synonym: "train", antonym: "perform" },
      { word: "gym", type: "noun", meaning: "exercise place", hindi: "जिम", example: "Go to the gym.", synonym: "fitness center", antonym: "" },
      { word: "workout", type: "noun", meaning: "exercise session", hindi: "कसरत", example: "A morning workout.", synonym: "exercise", antonym: "rest" },
      { word: "warm-up", type: "noun", meaning: "light start exercise", hindi: "वार्म-अप", example: "Do a warm-up first.", synonym: "stretch", antonym: "cool-down" },
      { word: "stretch", type: "verb", meaning: "extend body", hindi: "खिंचाव", example: "Stretch your arms.", synonym: "extend", antonym: "contract" },
      { word: "fitness", type: "noun", meaning: "body health", hindi: "फिटनेस", example: "Focus on fitness.", synonym: "health", antonym: "illness" },
      { word: "strength", type: "noun", meaning: "body power", hindi: "ताकत", example: "Build your strength.", synonym: "power", antonym: "weakness" },
      { word: "stamina", type: "noun", meaning: "lasting energy", hindi: "सहनशक्ति", example: "Running builds stamina.", synonym: "endurance", antonym: "weakness" },
      { word: "speed", type: "noun", meaning: "how fast", hindi: "गति", example: "He runs with speed.", synonym: "pace", antonym: "slowness" },
      { word: "medal", type: "noun", meaning: "prize disc", hindi: "पदक", example: "She won a gold medal.", synonym: "award", antonym: "" },
      { word: "opponent", type: "noun", meaning: "other side player", hindi: "प्रतिद्वंद्वी", example: "Respect your opponent.", synonym: "rival", antonym: "teammate" },
      { word: "fan", type: "noun", meaning: "supporter", hindi: "प्रशंसक", example: "I'm a big cricket fan.", synonym: "supporter", antonym: "hater" },
    ],
  },
  {
    id: "movies", emoji: "🎬", title: "Movies & Music", desc: "Discuss films & songs",
    words: [
      { word: "movie", type: "noun", meaning: "film", hindi: "फिल्म", example: "Let's watch a movie.", synonym: "film", antonym: "" },
      { word: "actor", type: "noun", meaning: "man who acts", hindi: "अभिनेता", example: "A famous actor.", synonym: "star", antonym: "audience" },
      { word: "actress", type: "noun", meaning: "woman who acts", hindi: "अभिनेत्री", example: "A talented actress.", synonym: "star", antonym: "audience" },
      { word: "director", type: "noun", meaning: "film maker", hindi: "निर्देशक", example: "The director won an award.", synonym: "maker", antonym: "" },
      { word: "scene", type: "noun", meaning: "part of a film", hindi: "दृश्य", example: "A funny scene.", synonym: "part", antonym: "" },
      { word: "story", type: "noun", meaning: "tale", hindi: "कहानी", example: "A lovely story.", synonym: "tale", antonym: "" },
      { word: "plot", type: "noun", meaning: "story plan", hindi: "कथानक", example: "The plot is strong.", synonym: "storyline", antonym: "" },
      { word: "hero", type: "noun", meaning: "main good man", hindi: "नायक", example: "The hero saves all.", synonym: "lead", antonym: "villain" },
      { word: "villain", type: "noun", meaning: "bad person", hindi: "खलनायक", example: "The villain loses.", synonym: "baddie", antonym: "hero" },
      { word: "comedy", type: "noun", meaning: "funny film", hindi: "कॉमेडी", example: "I love comedy.", synonym: "humor", antonym: "tragedy" },
      { word: "tragedy", type: "noun", meaning: "sad story", hindi: "दुखांत", example: "A deep tragedy.", synonym: "sad story", antonym: "comedy" },
      { word: "drama", type: "noun", meaning: "serious story", hindi: "ड्रामा", example: "A family drama.", synonym: "play", antonym: "comedy" },
      { word: "song", type: "noun", meaning: "music with words", hindi: "गाना", example: "A sweet song.", synonym: "track", antonym: "" },
      { word: "singer", type: "noun", meaning: "person who sings", hindi: "गायक", example: "A playback singer.", synonym: "vocalist", antonym: "listener" },
      { word: "album", type: "noun", meaning: "song collection", hindi: "एल्बम", example: "A new music album.", synonym: "record", antonym: "" },
      { word: "tune", type: "noun", meaning: "melody", hindi: "धुन", example: "A catchy tune.", synonym: "melody", antonym: "noise" },
      { word: "melody", type: "noun", meaning: "pleasant sound", hindi: "मधुर धुन", example: "A soft melody.", synonym: "harmony", antonym: "discord" },
      { word: "lyric", type: "noun", meaning: "song words", hindi: "बोल", example: "Beautiful lyrics.", synonym: "words", antonym: "music" },
      { word: "band", type: "noun", meaning: "music group", hindi: "बैंड", example: "A rock band.", synonym: "group", antonym: "soloist" },
      { word: "concert", type: "noun", meaning: "live music show", hindi: "कंसर्ट", example: "A night concert.", synonym: "show", antonym: "" },
      { word: "stage", type: "noun", meaning: "performance place", hindi: "मंच", example: "Dance on stage.", synonym: "platform", antonym: "backstage" },
      { word: "dance", type: "verb", meaning: "move to music", hindi: "नाचना", example: "Dance to the beat.", synonym: "move", antonym: "stand still" },
      { word: "rhythm", type: "noun", meaning: "music pattern", hindi: "लय", example: "A fast rhythm.", synonym: "beat", antonym: "arhythm" },
      { word: "beat", type: "noun", meaning: "music pulse", hindi: "ताल", example: "Feel the beat.", synonym: "pulse", antonym: "" },
      { word: "voice", type: "noun", meaning: "sound of person", hindi: "आवाज़", example: "A golden voice.", synonym: "tone", antonym: "silence" },
      { word: "instrument", type: "noun", meaning: "music tool", hindi: "वाद्ययंत्र", example: "Play an instrument.", synonym: "tool", antonym: "voice" },
      { word: "guitar", type: "noun", meaning: "string instrument", hindi: "गिटार", example: "He plays guitar.", synonym: "strings", antonym: "" },
      { word: "piano", type: "noun", meaning: "key instrument", hindi: "पियानो", example: "Learn the piano.", synonym: "keys", antonym: "" },
      { word: "ticket", type: "noun", meaning: "entry pass", hindi: "टिकट", example: "Book two tickets.", synonym: "pass", antonym: "" },
      { word: "interval", type: "noun", meaning: "break in movie", hindi: "अंतराल", example: "Tea at interval.", synonym: "intermission", antonym: "continuation" },
    ],
  },
  {
    id: "family", emoji: "🏠", title: "Home & Family", desc: "Talk about your people",
    words: [
      { word: "family", type: "noun", meaning: "your people", hindi: "परिवार", example: "I love my family.", synonym: "relatives", antonym: "strangers" },
      { word: "mother", type: "noun", meaning: "female parent", hindi: "माँ", example: "My mother cooks well.", synonym: "mom", antonym: "father" },
      { word: "father", type: "noun", meaning: "male parent", hindi: "पिता", example: "My father works hard.", synonym: "dad", antonym: "mother" },
      { word: "brother", type: "noun", meaning: "male sibling", hindi: "भाई", example: "My brother studies.", synonym: "bhai", antonym: "sister" },
      { word: "sister", type: "noun", meaning: "female sibling", hindi: "बहन", example: "My sister sings well.", synonym: "behen", antonym: "brother" },
      { word: "son", type: "noun", meaning: "male child", hindi: "बेटा", example: "Their son is tall.", synonym: "boy", antonym: "daughter" },
      { word: "daughter", type: "noun", meaning: "female child", hindi: "बेटी", example: "Their daughter is a doctor.", synonym: "girl", antonym: "son" },
      { word: "uncle", type: "noun", meaning: "father's brother", hindi: "चाचा/मामा", example: "My uncle lives in Delhi.", synonym: "relative", antonym: "aunt" },
      { word: "aunt", type: "noun", meaning: "father's sister", hindi: "चाची/मामी", example: "My aunt makes great food.", synonym: "relative", antonym: "uncle" },
      { word: "cousin", type: "noun", meaning: "uncle's child", hindi: "चचेरा/ममेरा भाई", example: "My cousin is my friend.", synonym: "relative", antonym: "" },
      { word: "nephew", type: "noun", meaning: "brother's son", hindi: "भतीजा", example: "My nephew is cute.", synonym: "relative", antonym: "niece" },
      { word: "niece", type: "noun", meaning: "brother's daughter", hindi: "भतीजी", example: "My niece draws well.", synonym: "relative", antonym: "nephew" },
      { word: "grandfather", type: "noun", meaning: "father's father", hindi: "दादा/नाना", example: "My grandfather tells stories.", synonym: "grandpa", antonym: "grandmother" },
      { word: "grandmother", type: "noun", meaning: "father's mother", hindi: "दादी/नानी", example: "My grandmother sings to me.", synonym: "grandma", antonym: "grandfather" },
      { word: "husband", type: "noun", meaning: "married man", hindi: "पति", example: "Her husband is a teacher.", synonym: "spouse", antonym: "wife" },
      { word: "wife", type: "noun", meaning: "married woman", hindi: "पत्नी", example: "His wife is a nurse.", synonym: "spouse", antonym: "husband" },
      { word: "parent", type: "noun", meaning: "mother or father", hindi: "अभिभावक", example: "My parents support me.", synonym: "guardian", antonym: "child" },
      { word: "child", type: "noun", meaning: "young person", hindi: "बच्चा", example: "The child is sleeping.", synonym: "kid", antonym: "parent" },
      { word: "kids", type: "noun", meaning: "children", hindi: "बच्चे", example: "The kids are playing.", synonym: "children", antonym: "adults" },
      { word: "home", type: "noun", meaning: "where you live", hindi: "घर", example: "Home is where love is.", synonym: "house", antonym: "outside" },
      { word: "room", type: "noun", meaning: "part of house", hindi: "कमरा", example: "A clean room.", synonym: "space", antonym: "" },
      { word: "kitchen", type: "noun", meaning: "cooking room", hindi: "रसोई", example: "Cook in the kitchen.", synonym: "cooking area", antonym: "" },
      { word: "bedroom", type: "noun", meaning: "sleeping room", hindi: "शयनकक्ष", example: "Two bedrooms.", synonym: "sleeping room", antonym: "" },
      { word: "bathroom", type: "noun", meaning: "washing room", hindi: "बाथरूम", example: "Clean the bathroom.", synonym: "washroom", antonym: "" },
      { word: "garden", type: "noun", meaning: "plant area", hindi: "बगीचा", example: "Flowers in the garden.", synonym: "yard", antonym: "house" },
      { word: "furniture", type: "noun", meaning: "tables, chairs", hindi: "फर्नीचर", example: "New furniture.", synonym: "fixtures", antonym: "" },
      { word: "neighbor", type: "noun", meaning: "person near home", hindi: "पड़ोसी", example: "A helpful neighbor.", synonym: "next-door", antonym: "stranger" },
      { word: "guest", type: "noun", meaning: "visitor", hindi: "मेहमान", example: "We have guests today.", synonym: "visitor", antonym: "host" },
      { word: "relative", type: "noun", meaning: "family member", hindi: "रिश्तेदार", example: "Relatives came for Diwali.", synonym: "kin", antonym: "stranger" },
      { word: "household", type: "noun", meaning: "home and people", hindi: "गृहस्थी", example: "Household work is tiring.", synonym: "home", antonym: "" },
    ],
  },
  {
    id: "festivals", emoji: "🎉", title: "Festivals & Culture", desc: "Celebrate in English",
    words: [
      { word: "festival", type: "noun", meaning: "celebration day", hindi: "त्योहार", example: "Diwali is my favorite festival.", synonym: "celebration", antonym: "mourning" },
      { word: "celebration", type: "noun", meaning: "party for event", hindi: "जश्न", example: "A big celebration.", synonym: "party", antonym: "funeral" },
      { word: "ceremony", type: "noun", meaning: "formal event", hindi: "समारोह", example: "A wedding ceremony.", synonym: "function", antonym: "informality" },
      { word: "tradition", type: "noun", meaning: "old custom", hindi: "परंपरा", example: "Follow the tradition.", synonym: "custom", antonym: "innovation" },
      { word: "custom", type: "noun", meaning: "usual practice", hindi: "रीति", example: "A local custom.", synonym: "habit", antonym: "departure" },
      { word: "ritual", type: "noun", meaning: "religious act", hindi: "अनुष्ठान", example: "Morning rituals.", synonym: "rite", antonym: "secular act" },
      { word: "culture", type: "noun", meaning: "way of life", hindi: "संस्कृति", example: "Indian culture is rich.", synonym: "heritage", antonym: "nature" },
      { word: "prayer", type: "noun", meaning: "talk to God", hindi: "प्रार्थना", example: "Say a prayer.", synonym: "worship", antonym: "curse" },
      { word: "temple", type: "noun", meaning: "Hindu worship place", hindi: "मंदिर", example: "Visit the temple.", synonym: "shrine", antonym: "" },
      { word: "gift", type: "noun", meaning: "present", hindi: "उपहार", example: "A lovely gift.", synonym: "present", antonym: "penalty" },
      { word: "decoration", type: "noun", meaning: "making pretty", hindi: "सजावट", example: "Beautiful decoration.", synonym: "ornament", antonym: "eyesore" },
      { word: "firework", type: "noun", meaning: "light burst in sky", hindi: "आतिशबाज़ी", example: "Fireworks at night.", synonym: "crackers", antonym: "" },
      { word: "costume", type: "noun", meaning: "special dress", hindi: "पोशाक", example: "A traditional costume.", synonym: "outfit", antonym: "uniform" },
      { word: "parade", type: "noun", meaning: "walking show", hindi: "शोभायात्रा", example: "A street parade.", synonym: "procession", antonym: "standstill" },
      { word: "fair", type: "noun", meaning: "fun market event", hindi: "मेला", example: "A village fair.", synonym: "mela", antonym: "" },
      { word: "holiday", type: "noun", meaning: "day off", hindi: "छुट्टी", example: "A long holiday.", synonym: "vacation", antonym: "workday" },
      { word: "feast", type: "noun", meaning: "big meal", hindi: "भोज", example: "A festival feast.", synonym: "banquet", antonym: "fast" },
      { word: "fast", type: "verb", meaning: "not eating", hindi: "व्रत", example: "She fasts on Mondays.", synonym: "vrata", antonym: "eat" },
      { word: "blessing", type: "noun", meaning: "good wish", hindi: "आशीर्वाद", example: "Take elders' blessings.", synonym: "wish", antonym: "curse" },
      { word: "gathering", type: "noun", meaning: "people meeting", hindi: "इकट्ठा", example: "A family gathering.", synonym: "meeting", antonym: "isolation" },
      { word: "community", type: "noun", meaning: "group of people", hindi: "समुदाय", example: "A strong community.", synonym: "society", antonym: "individual" },
      { word: "heritage", type: "noun", meaning: "old valuable things", hindi: "विरासत", example: "Protect our heritage.", synonym: "legacy", antonym: "novelty" },
      { word: "art", type: "noun", meaning: "creative work", hindi: "कला", example: "Folk art is lovely.", synonym: "craft", antonym: "science" },
      { word: "craft", type: "noun", meaning: "handmade skill", hindi: "शिल्प", example: "Buy local crafts.", synonym: "handwork", antonym: "machine work" },
      { word: "folk", type: "adjective", meaning: "of common people", hindi: "लोक", example: "Folk songs are sweet.", synonym: "traditional", antonym: "modern" },
      { word: "legend", type: "noun", meaning: "old famous story", hindi: "किंवदंती", example: "A village legend.", synonym: "myth", antonym: "fact" },
      { word: "history", type: "noun", meaning: "past events", hindi: "इतिहास", example: "Learn our history.", synonym: "past", antonym: "future" },
      { word: "symbol", type: "noun", meaning: "sign of idea", hindi: "प्रतीक", example: "A diya is a symbol of light.", synonym: "sign", antonym: "" },
      { word: "flag", type: "noun", meaning: "country cloth", hindi: "झंडा", example: "Hoist the flag.", synonym: "banner", antonym: "" },
      { word: "sweet", type: "noun", meaning: "festival food", hindi: "मिठाई", example: "Share sweets.", synonym: "dessert", antonym: "salty" },
    ],
  },
];