import { Pack } from "./dataA";

export const PACKS_D: Pack[] = [
  {
    id: "nature", emoji: "🌍", title: "Environment & Nature", desc: "Talk about the world around you",
    words: [
      { word: "nature", type: "noun", meaning: "the natural world", hindi: "प्रकृति", example: "Nature is beautiful.", synonym: "outdoors", antonym: "city" },
      { word: "tree", type: "noun", meaning: "tall plant", hindi: "पेड़", example: "A big tree gives shade.", synonym: "plant", antonym: "" },
      { word: "forest", type: "noun", meaning: "many trees together", hindi: "जंगल", example: "The forest is green.", synonym: "woods", antonym: "desert" },
      { word: "river", type: "noun", meaning: "flowing water", hindi: "नदी", example: "The river is long.", synonym: "stream", antonym: "" },
      { word: "mountain", type: "noun", meaning: "very high land", hindi: "पर्वत", example: "Climb the mountain.", synonym: "hill", antonym: "valley" },
      { word: "ocean", type: "noun", meaning: "the biggest sea", hindi: "महासागर", example: "The ocean is deep.", synonym: "sea", antonym: "land" },
      { word: "lake", type: "noun", meaning: "still water body", hindi: "झील", example: "A quiet lake.", synonym: "pond", antonym: "" },
      { word: "sky", type: "noun", meaning: "space above us", hindi: "आकाश", example: "The sky is blue.", synonym: "heavens", antonym: "ground" },
      { word: "star", type: "noun", meaning: "light at night", hindi: "तारा", example: "Stars shine at night.", synonym: "sparkle", antonym: "" },
      { word: "moon", type: "noun", meaning: "night light", hindi: "चाँद", example: "The moon is full.", synonym: "lunar", antonym: "sun" },
      { word: "sun", type: "noun", meaning: "day light", hindi: "सूरज", example: "The sun rises early.", synonym: "solar", antonym: "moon" },
      { word: "planet", type: "noun", meaning: "world in space", hindi: "ग्रह", example: "Earth is a planet.", synonym: "world", antonym: "" },
      { word: "earth", type: "noun", meaning: "our world", hindi: "पृथ्वी", example: "Protect the earth.", synonym: "world", antonym: "" },
      { word: "soil", type: "noun", meaning: "ground for plants", hindi: "मिट्टी", example: "Rich soil grows crops.", synonym: "ground", antonym: "" },
      { word: "plant", type: "noun", meaning: "green life", hindi: "पौधा", example: "Water the plant.", synonym: "greenery", antonym: "" },
      { word: "flower", type: "noun", meaning: "pretty part of plant", hindi: "फूल", example: "A red flower.", synonym: "bloom", antonym: "" },
      { word: "leaf", type: "noun", meaning: "green part of tree", hindi: "पत्ता", example: "A green leaf.", synonym: "foliage", antonym: "" },
      { word: "grass", type: "noun", meaning: "green ground cover", hindi: "घास", example: "Soft grass.", synonym: "lawn", antonym: "" },
      { word: "animal", type: "noun", meaning: "living creature", hindi: "जानवर", example: "Animals need care.", synonym: "creature", antonym: "plant" },
      { word: "bird", type: "noun", meaning: "flying creature", hindi: "पक्षी", example: "A singing bird.", synonym: "feathered", antonym: "" },
      { word: "insect", type: "noun", meaning: "small bug", hindi: "कीड़ा", example: "A tiny insect.", synonym: "bug", antonym: "" },
      { word: "wildlife", type: "noun", meaning: "wild animals", hindi: "वन्यजीव", example: "Protect wildlife.", synonym: "fauna", antonym: "pets" },
      { word: "pollution", type: "noun", meaning: "making dirty", hindi: "प्रदूषण", example: "Air pollution is rising.", synonym: "contamination", antonym: "purity" },
      { word: "recycle", type: "verb", meaning: "reuse material", hindi: "पुनर्चक्रिकरण", example: "Recycle plastic.", synonym: "reuse", antonym: "waste" },
      { word: "plastic", type: "noun", meaning: "synthetic material", hindi: "प्लास्टिक", example: "Avoid plastic bags.", synonym: "synthetic", antonym: "natural material" },
      { word: "climate", type: "noun", meaning: "weather over time", hindi: "जलवायु", example: "Climate is changing.", synonym: "weather", antonym: "" },
      { word: "environment", type: "noun", meaning: "nature around us", hindi: "पर्यावरण", example: "Keep the environment clean.", synonym: "surroundings", antonym: "" },
      { word: "protect", type: "verb", meaning: "keep safe", hindi: "सुरक्षित रखना", example: "Protect the trees.", synonym: "guard", antonym: "harm" },
      { word: "conserve", type: "verb", meaning: "save for later", hindi: "संरक्षित करना", example: "Conserve water.", synonym: "save", antonym: "waste" },
      { word: "green", type: "adjective", meaning: "color of plants", hindi: "हरा", example: "A green field.", synonym: "verdant", antonym: "" },
    ],
  },
  {
    id: "news", emoji: "📰", title: "News & Media", desc: "Understand & discuss the news",
    words: [
      { word: "news", type: "noun", meaning: "new information", hindi: "समाचार", example: "Watch the news.", synonym: "updates", antonym: "history" },
      { word: "newspaper", type: "noun", meaning: "printed news", hindi: "अखबार", example: "Read the newspaper.", synonym: "daily", antonym: "" },
      { word: "headline", type: "noun", meaning: "big title", hindi: "सुर्खी", example: "A shocking headline.", synonym: "title", antonym: "" },
      { word: "article", type: "noun", meaning: "written piece", hindi: "लेख", example: "An interesting article.", synonym: "story", antonym: "" },
      { word: "journalist", type: "noun", meaning: "news writer", hindi: "पत्रकार", example: "A brave journalist.", synonym: "reporter", antonym: "" },
      { word: "reporter", type: "noun", meaning: "person who reports", hindi: "संवाददाता", example: "The reporter is live.", synonym: "correspondent", antonym: "" },
      { word: "editor", type: "noun", meaning: "person who checks news", hindi: "संपादक", example: "The editor approved it.", synonym: "chief", antonym: "" },
      { word: "channel", type: "noun", meaning: "TV station", hindi: "चैनल", example: "A news channel.", synonym: "station", antonym: "" },
      { word: "broadcast", type: "verb", meaning: "show on TV", hindi: "प्रसारण", example: "They broadcast the match.", synonym: "air", antonym: "keep secret" },
      { word: "live", type: "adjective", meaning: "happening now", hindi: "लाइव", example: "A live report.", synonym: "real-time", antonym: "recorded" },
      { word: "breaking news", type: "phrase", meaning: "very fresh news", hindi: "ताज़ा खबर", example: "Breaking news just in!", synonym: "flash", antonym: "old news" },
      { word: "interview", type: "noun", meaning: "question-answer talk", hindi: "साक्षात्कार", example: "A TV interview.", synonym: "talk", antonym: "" },
      { word: "source", type: "noun", meaning: "where info comes", hindi: "स्रोत", example: "A trusted source.", synonym: "origin", antonym: "" },
      { word: "information", type: "noun", meaning: "facts given", hindi: "जानकारी", example: "Useful information.", synonym: "data", antonym: "ignorance" },
      { word: "fact", type: "noun", meaning: "true thing", hindi: "तथ्य", example: "Check the facts.", synonym: "truth", antonym: "fiction" },
      { word: "opinion", type: "noun", meaning: "personal view", hindi: "राय", example: "That's my opinion.", synonym: "view", antonym: "fact" },
      { word: "rumor", type: "noun", meaning: "unverified talk", hindi: "अफवाह", example: "Don't spread rumors.", synonym: "gossip", antonym: "fact" },
      { word: "fake news", type: "phrase", meaning: "false news", hindi: "झूठी खबर", example: "Beware of fake news.", synonym: "hoax", antonym: "truth" },
      { word: "truth", type: "noun", meaning: "what is real", hindi: "सच", example: "Tell the truth.", synonym: "reality", antonym: "lie" },
      { word: "evidence", type: "noun", meaning: "proof", hindi: "सबूत", example: "Strong evidence.", synonym: "proof", antonym: "conjecture" },
      { word: "announce", type: "verb", meaning: "make public", hindi: "घोषणा", example: "Announce the result.", synonym: "declare", antonym: "hide" },
      { word: "update", type: "noun", meaning: "latest info", hindi: "अपडेट", example: "Give me an update.", synonym: "refresh", antonym: "" },
      { word: "coverage", type: "noun", meaning: "news reporting", hindi: "कवरेज", example: "Full match coverage.", synonym: "reporting", antonym: "" },
      { word: "media", type: "noun", meaning: "news industry", hindi: "मीडिया", example: "The media is powerful.", synonym: "press", antonym: "" },
      { word: "social media", type: "phrase", meaning: "online platforms", hindi: "सोशल मीडिया", example: "Share on social media.", synonym: "networks", antonym: "print media" },
      { word: "viral", type: "adjective", meaning: "spreading fast online", hindi: "वायरल", example: "The video went viral.", synonym: "trending", antonym: "unknown" },
      { word: "trend", type: "noun", meaning: "popular thing", hindi: "रुझान", example: "A new trend.", synonym: "fashion", antonym: "" },
      { word: "audience", type: "noun", meaning: "watching people", hindi: "दर्शक", example: "A huge audience.", synonym: "viewers", antonym: "" },
      { word: "publish", type: "verb", meaning: "release publicly", hindi: "प्रकाशित", example: "Publish the story.", synonym: "release", antonym: "withhold" },
      { word: "press", type: "noun", meaning: "news people", hindi: "प्रेस", example: "The press conference.", synonym: "media", antonym: "" },
    ],
  },
  {
    id: "college", emoji: "🎓", title: "College Life", desc: "Every word a student needs",
    words: [
      { word: "college", type: "noun", meaning: "higher study place", hindi: "कॉलेज", example: "I go to college by bus.", synonym: "institute", antonym: "" },
      { word: "university", type: "noun", meaning: "big college", hindi: "विश्वविद्यालय", example: "A famous university.", synonym: "varsity", antonym: "" },
      { word: "campus", type: "noun", meaning: "college area", hindi: "कैंपस", example: "A green campus.", synonym: "grounds", antonym: "" },
      { word: "classroom", type: "noun", meaning: "teaching room", hindi: "कक्षा", example: "A smart classroom.", synonym: "room", antonym: "" },
      { word: "lecture", type: "noun", meaning: "teaching talk", hindi: "व्याख्यान", example: "The lecture was long.", synonym: "class", antonym: "" },
      { word: "professor", type: "noun", meaning: "senior teacher", hindi: "प्रोफेसर", example: "The professor is kind.", synonym: "teacher", antonym: "student" },
      { word: "student", type: "noun", meaning: "person who studies", hindi: "विद्यार्थी", example: "A hardworking student.", synonym: "learner", antonym: "teacher" },
      { word: "classmate", type: "noun", meaning: "same class friend", hindi: "सहपाठी", example: "My classmate helps me.", synonym: "peer", antonym: "" },
      { word: "senior", type: "noun", meaning: "older student", hindi: "वरिष्ठ", example: "Ask your senior.", synonym: "elder", antonym: "junior" },
      { word: "junior", type: "noun", meaning: "younger student", hindi: "कनिष्ठ", example: "Guide your juniors.", synonym: "younger", antonym: "senior" },
      { word: "assignment", type: "noun", meaning: "given task", hindi: "असाइनमेंट", example: "Submit the assignment.", synonym: "task", antonym: "" },
      { word: "homework", type: "noun", meaning: "home task", hindi: "गृहकार्य", example: "Finish your homework.", synonym: "study work", antonym: "" },
      { word: "notes", type: "noun", meaning: "written points", hindi: "नोट्स", example: "Share your notes.", synonym: "points", antonym: "" },
      { word: "textbook", type: "noun", meaning: "study book", hindi: "पाठ्यपुस्तक", example: "Open the textbook.", synonym: "book", antonym: "" },
      { word: "library", type: "noun", meaning: "book place", hindi: "पुस्तकालय", example: "Study in the library.", synonym: "book house", antonym: "" },
      { word: "exam", type: "noun", meaning: "big test", hindi: "परीक्षा", example: "Exams start next week.", synonym: "test", antonym: "" },
      { word: "test", type: "noun", meaning: "small exam", hindi: "टेस्ट", example: "A surprise test.", synonym: "quiz", antonym: "" },
      { word: "grade", type: "noun", meaning: "score level", hindi: "ग्रेड", example: "I got a good grade.", synonym: "level", antonym: "" },
      { word: "marks", type: "noun", meaning: "score points", hindi: "अंक", example: "Full marks in English!", synonym: "score", antonym: "" },
      { word: "result", type: "noun", meaning: "final outcome", hindi: "परिणाम", example: "The result is out.", synonym: "outcome", antonym: "" },
      { word: "degree", type: "noun", meaning: "college certificate", hindi: "डिग्री", example: "A science degree.", synonym: "qualification", antonym: "" },
      { word: "diploma", type: "noun", meaning: "course certificate", hindi: "डिप्लोमा", example: "A computer diploma.", synonym: "certificate", antonym: "" },
      { word: "course", type: "noun", meaning: "study program", hindi: "कोर्स", example: "A coding course.", synonym: "program", antonym: "" },
      { word: "subject", type: "noun", meaning: "study topic", hindi: "विषय", example: "My favorite subject.", synonym: "topic", antonym: "" },
      { word: "semester", type: "noun", meaning: "half year term", hindi: "सेमेस्टर", example: "Third semester starts.", synonym: "term", antonym: "" },
      { word: "attendance", type: "noun", meaning: "being present", hindi: "उपस्थिति", example: "Attendance is important.", synonym: "presence", antonym: "absence" },
      { word: "canteen", type: "noun", meaning: "college eatery", hindi: "कैंटीन", example: "Eat at the canteen.", synonym: "cafeteria", antonym: "" },
      { word: "hostel", type: "noun", meaning: "student home", hindi: "हॉस्टल", example: "I live in a hostel.", synonym: "dorm", antonym: "" },
      { word: "scholarship", type: "noun", meaning: "study money award", hindi: "छात्रवृत्ति", example: "She won a scholarship.", synonym: "grant", antonym: "debt" },
      { word: "admission", type: "noun", meaning: "entry to college", hindi: "प्रवेश", example: "Admission opens in June.", synonym: "entry", antonym: "rejection" },
    ],
  },
  {
    id: "friends", emoji: "🤝", title: "Friendship & Relations", desc: "Words for your people",
    words: [
      { word: "friend", type: "noun", meaning: "person you like", hindi: "दोस्त", example: "He is my best friend.", synonym: "pal", antonym: "enemy" },
      { word: "friendship", type: "noun", meaning: "being friends", hindi: "दोस्ती", example: "A strong friendship.", synonym: "bond", antonym: "enmity" },
      { word: "best friend", type: "noun", meaning: "closest friend", hindi: "जिगरी दोस्त", example: "She is my best friend.", synonym: "close pal", antonym: "enemy" },
      { word: "trust", type: "verb", meaning: "believe in", hindi: "भरोसा", example: "Trust your friends.", synonym: "believe", antonym: "distrust" },
      { word: "respect", type: "verb", meaning: "honor someone", hindi: "सम्मान", example: "Respect everyone.", synonym: "honor", antonym: "disrespect" },
      { word: "support", type: "verb", meaning: "help someone", hindi: "समर्थन", example: "Support your team.", synonym: "back", antonym: "oppose" },
      { word: "care", type: "verb", meaning: "feel concern", hindi: "परवाह", example: "I care about you.", synonym: "concern", antonym: "neglect" },
      { word: "share", type: "verb", meaning: "give a part", hindi: "साझा", example: "Share your tiffin.", synonym: "divide", antonym: "hoard" },
      { word: "help", type: "verb", meaning: "make easier", hindi: "मदद", example: "Help your friends.", synonym: "assist", antonym: "hinder" },
      { word: "advice", type: "noun", meaning: "suggestion", hindi: "सलाह", example: "Good advice matters.", synonym: "guidance", antonym: "" },
      { word: "promise", type: "verb", meaning: "say you will do", hindi: "वादा", example: "Promise me.", synonym: "pledge", antonym: "break" },
      { word: "honest", type: "adjective", meaning: "truthful", hindi: "ईमानदार", example: "Be honest always.", synonym: "truthful", antonym: "dishonest" },
      { word: "loyal", type: "adjective", meaning: "always faithful", hindi: "वफादार", example: "A loyal friend.", synonym: "faithful", antonym: "disloyal" },
      { word: "kind", type: "adjective", meaning: "nice to others", hindi: "दयालु", example: "She is kind.", synonym: "gentle", antonym: "cruel" },
      { word: "funny", type: "adjective", meaning: "makes laugh", hindi: "मज़ेदार", example: "A funny story.", synonym: "humorous", antonym: "serious" },
      { word: "reliable", type: "adjective", meaning: "can be trusted", hindi: "भरोसेमंद", example: "A reliable friend.", synonym: "dependable", antonym: "unreliable" },
      { word: "understanding", type: "adjective", meaning: "gets your feelings", hindi: "समझदार", example: "An understanding mother.", synonym: "empathetic", antonym: "intolerant" },
      { word: "patience", type: "noun", meaning: "calm waiting", hindi: "धैर्य", example: "Have patience.", synonym: "calm", antonym: "impatience" },
      { word: "forgive", type: "verb", meaning: "stop being angry", hindi: "माफ करना", example: "Forgive and forget.", synonym: "pardon", antonym: "blame" },
      { word: "apologize", type: "verb", meaning: "say sorry", hindi: "माफी मांगना", example: "Apologize to her.", synonym: "say sorry", antonym: "deny" },
      { word: "argue", type: "verb", meaning: "disagree with words", hindi: "बहस", example: "Don't argue loudly.", synonym: "debate", antonym: "agree" },
      { word: "celebrate", type: "verb", meaning: "enjoy an event", hindi: "मनाना", example: "Celebrate your birthday.", synonym: "party", antonym: "mourn" },
      { word: "together", type: "adverb", meaning: "with each other", hindi: "साथ", example: "We study together.", synonym: "jointly", antonym: "alone" },
      { word: "memory", type: "noun", meaning: "thing remembered", hindi: "याद", example: "A sweet memory.", synonym: "recollection", antonym: "" },
      { word: "relationship", type: "noun", meaning: "connection between people", hindi: "रिश्ता", example: "A strong relationship.", synonym: "bond", antonym: "" },
      { word: "partner", type: "noun", meaning: "person you work with", hindi: "साथी", example: "My project partner.", synonym: "companion", antonym: "rival" },
      { word: "companion", type: "noun", meaning: "person with you", hindi: "संगी", example: "A travel companion.", synonym: "friend", antonym: "stranger" },
      { word: "bond", type: "noun", meaning: "strong connection", hindi: "बंधन", example: "A family bond.", synonym: "tie", antonym: "" },
      { word: "cheerful", type: "adjective", meaning: "happy and positive", hindi: "हंसमुख", example: "A cheerful friend.", synonym: "happy", antonym: "sad" },
      { word: "generous", type: "adjective", meaning: "gives freely", hindi: "उदार", example: "A generous host.", synonym: "giving", antonym: "selfish" },
    ],
  },
  {
    id: "dreams", emoji: "🌙", title: "Dreams & Goals", desc: "Talk about your future",
    words: [
      { word: "dream", type: "noun", meaning: "big wish", hindi: "सपना", example: "My dream is to travel.", synonym: "vision", antonym: "reality" },
      { word: "goal", type: "noun", meaning: "thing to achieve", hindi: "लक्ष्य", example: "Set a daily goal.", synonym: "target", antonym: "" },
      { word: "plan", type: "noun", meaning: "method for future", hindi: "योजना", example: "Make a plan.", synonym: "strategy", antonym: "" },
      { word: "wish", type: "noun", meaning: "want", hindi: "इच्छा", example: "Make a wish.", synonym: "desire", antonym: "" },
      { word: "hope", type: "noun", meaning: "good feeling about future", hindi: "उम्मीद", example: "Never lose hope.", synonym: "optimism", antonym: "despair" },
      { word: "ambition", type: "noun", meaning: "strong drive to succeed", hindi: "महत्वाकांक्षा", example: "A big ambition.", synonym: "drive", antonym: "apathy" },
      { word: "target", type: "noun", meaning: "aim", hindi: "निशाना", example: "Hit the target.", synonym: "goal", antonym: "" },
      { word: "future", type: "noun", meaning: "time ahead", hindi: "भविष्य", example: "Plan your future.", synonym: "tomorrow", antonym: "past" },
      { word: "success", type: "noun", meaning: "winning", hindi: "सफलता", example: "Success takes effort.", synonym: "achievement", antonym: "failure" },
      { word: "failure", type: "noun", meaning: "not succeeding", hindi: "विफलता", example: "Failure teaches us.", synonym: "defeat", antonym: "success" },
      { word: "effort", type: "noun", meaning: "hard try", hindi: "प्रयास", example: "Put in effort.", synonym: "attempt", antonym: "laziness" },
      { word: "hard work", type: "noun", meaning: "working hard", hindi: "मेहनत", example: "Hard work pays.", synonym: "labor", antonym: "laziness" },
      { word: "discipline", type: "noun", meaning: "self control", hindi: "अनुशासन", example: "Discipline is power.", synonym: "control", antonym: "chaos" },
      { word: "habit", type: "noun", meaning: "regular action", hindi: "आदत", example: "Build good habits.", synonym: "routine", antonym: "" },
      { word: "routine", type: "noun", meaning: "fixed daily plan", hindi: "दिनचर्या", example: "A morning routine.", synonym: "schedule", antonym: "spontaneity" },
      { word: "focus", type: "verb", meaning: "give full attention", hindi: "ध्यान", example: "Focus on studies.", synonym: "concentrate", antonym: "distract" },
      { word: "improve", type: "verb", meaning: "get better", hindi: "सुधारना", example: "Improve your English.", synonym: "better", antonym: "worsen" },
      { word: "learn", type: "verb", meaning: "get knowledge", hindi: "सीखना", example: "Learn something new.", synonym: "study", antonym: "forget" },
      { word: "grow", type: "verb", meaning: "get bigger/better", hindi: "बढ़ना", example: "Grow every day.", synonym: "develop", antonym: "shrink" },
      { word: "achieve", type: "verb", meaning: "reach a goal", hindi: "हासिल करना", example: "Achieve your dreams.", synonym: "attain", antonym: "fail" },
      { word: "inspire", type: "verb", meaning: "give motivation", hindi: "प्रेरित करना", example: "You inspire me.", synonym: "motivate", antonym: "discourage" },
      { word: "motivation", type: "noun", meaning: "reason to act", hindi: "प्रेरणा", example: "Find your motivation.", synonym: "drive", antonym: "apathy" },
      { word: "confidence", type: "noun", meaning: "self belief", hindi: "आत्मविश्वास", example: "Speak with confidence.", synonym: "belief", antonym: "doubt" },
      { word: "courage", type: "noun", meaning: "bravery", hindi: "साहस", example: "Have courage.", synonym: "bravery", antonym: "cowardice" },
      { word: "risk", type: "noun", meaning: "chance of loss", hindi: "जोखिम", example: "Take a smart risk.", synonym: "gamble", antonym: "safety" },
      { word: "chance", type: "noun", meaning: "opportunity", hindi: "मौका", example: "Take the chance.", synonym: "opportunity", antonym: "" },
      { word: "journey", type: "noun", meaning: "long travel", hindi: "यात्रा", example: "The journey of life.", synonym: "path", antonym: "" },
      { word: "milestone", type: "noun", meaning: "big achievement point", hindi: "पड़ाव", example: "A career milestone.", synonym: "marker", antonym: "" },
      { word: "reward", type: "noun", meaning: "thing given for good work", hindi: "इनाम", example: "Effort brings reward.", synonym: "prize", antonym: "punishment" },
      { word: "victory", type: "noun", meaning: "winning", hindi: "विजय", example: "A sweet victory.", synonym: "triumph", antonym: "defeat" },
    ],
  },
];