// 🔥 ZERO-COST QUIZ BANK: curated by us, served before any AI call.
export interface LocalQuizQ { q: string; options: string[]; correct: number; explain: string; }

export const LOCAL_QUIZ: Record<string, LocalQuizQ[]> = {
  "WD-1": [
    { q: "Which tag creates the MOST important heading on a page?", options: ["<head>", "<h6>", "<h1>", "<header>"], correct: 2, explain: "h1 = top-level heading; header is a semantic container, head is metadata." },
    { q: "Space INSIDE an element (between content and border) is called?", options: ["margin", "padding", "gap", "outline"], correct: 1, explain: "Padding = inside space, margin = outside space." },
    { q: "In Flexbox, which property aligns items along the MAIN axis?", options: ["align-items", "justify-content", "place-self", "flex-wrap"], correct: 1, explain: "justify-content = main axis; align-items = cross axis." },
    { q: "Which is a SEMANTIC HTML tag?", options: ["<div>", "<span>", "<nav>", "<b>"], correct: 2, explain: "nav describes its purpose (navigation) to browsers & screen readers." },
  ],
  "WD-2": [
    { q: "Tailwind CSS is best described as?", options: ["Component library", "Utility-first CSS framework", "CSS preprocessor", "JS framework"], correct: 1, explain: "Tailwind = small single-purpose utility classes composed in HTML." },
    { q: "Which class applies padding-4 only on medium screens and up?", options: ["p-md-4", "md:p-4", "md-p-4", "p-4:md"], correct: 1, explain: "Breakpoint prefix + colon: md:p-4 (mobile-first)." },
    { q: "Mobile-first means:", options: ["Styles written for desktop first", "Base styles target mobile, prefixes add larger screens", "Only mobile works", "Use px everywhere"], correct: 1, explain: "Base = mobile; sm:/md:/lg: progressively enhance." },
    { q: "Class to stack flex children vertically?", options: ["flex-row", "flex-col", "col-flex", "vertical"], correct: 1, explain: "flex-col sets flex-direction: column." },
  ],
  "WD-3": [
    { q: "Which array method adds an item to the END?", options: ["shift()", "pop()", "push()", "unshift()"], correct: 2, explain: "push adds to end; pop removes from end." },
    { q: "typeof null returns?", options: ["'null'", "'undefined'", "'object'", "'number'"], correct: 2, explain: "Historic JS quirk: typeof null === 'object'." },
    { q: "localStorage stores values as?", options: ["objects", "strings", "numbers", "blobs"], correct: 1, explain: "Everything is stringified; parse when reading." },
    { q: "Which method returns a NEW transformed array?", options: ["forEach", "map", "sort", "splice"], correct: 1, explain: "map returns new array; forEach returns undefined." },
  ],
  "WD-4": [
    { q: "fetch() immediately returns?", options: ["JSON data", "A Promise", "A string", "An array"], correct: 1, explain: "fetch returns a Promise of a Response." },
    { q: "Which keyword pauses an async function until a Promise settles?", options: ["wait", "await", "hold", "yield"], correct: 1, explain: "await unwraps a Promise inside async functions." },
    { q: "HTTP status code for 'Not Found'?", options: ["200", "301", "404", "500"], correct: 2, explain: "404 = resource missing; 500 = server error." },
    { q: "try/catch is used to?", options: ["Loop faster", "Handle runtime errors", "Define variables", "Style errors"], correct: 1, explain: "catch receives thrown errors so app doesn't crash." },
  ],
  "WD-5": [
    { q: "Which hook stores local state in a component?", options: ["useEffect", "useState", "useRef", "useMemo"], correct: 1, explain: "useState returns [value, setter]." },
    { q: "useEffect with an EMPTY dependency array runs:", options: ["Every render", "Once after first render", "Never", "Only on unmount"], correct: 1, explain: "[] = mount-only effect." },
    { q: "Props are:", options: ["Mutable state", "Read-only inputs from parent", "Global variables", "Hooks"], correct: 1, explain: "Never mutate props; lift state up instead." },
    { q: "Keys in lists help React:", options: ["Style items", "Identify items across renders", "Sort items", "Fetch items"], correct: 1, explain: "Stable keys = correct reconciliation, no buggy re-renders." },
  ],
  "WD-6": [
    { q: "In Next.js App Router, components are by default:", options: ["Client Components", "Server Components", "Static HTML only", "Workers"], correct: 1, explain: "Server Components render on server; add 'use client' for interactivity." },
    { q: "Which file creates the route /blog/[slug]?", options: ["app/blog/slug/page.tsx", "app/blog/[slug]/page.tsx", "pages/blog/[slug].js only", "routes/blog.ts"], correct: 1, explain: "Folder name in brackets = dynamic segment." },
    { q: "'use client' at top of a file means:", options: ["File runs only in terminal", "File opts into client-side rendering/interactivity", "File is private", "File skips build"], correct: 1, explain: "Marks the boundary where client JS bundle starts." },
    { q: "Per-page SEO title/description is set via:", options: ["<title> in layout only", "export const metadata", "document.title in useEffect always", "next/head in every page"], correct: 1, explain: "App Router: export metadata object from page/layout." },
  ],
  "WD-7": [
    { q: "Supabase is built on top of which database?", options: ["MySQL", "MongoDB", "PostgreSQL", "SQLite"], correct: 2, explain: "Supabase = hosted Postgres + auth + storage + realtime." },
    { q: "RLS stands for:", options: ["Realtime Live Sync", "Row Level Security", "Remote Login Service", "Read Limit System"], correct: 1, explain: "RLS policies enforce per-row access in the DB itself." },
    { q: "Secret keys (service role) must live in:", options: ["Client code", "localStorage", "Server environment variables", "GitHub README"], correct: 2, explain: "Anything shipped to browser is public. Server env only." },
    { q: "Which SDK call adds a new row?", options: [".select()", ".insert()", ".update()", ".delete()"], correct: 1, explain: "insert() creates rows; update() modifies existing." },
  ],
  "WD-8": [
    { q: "Which command sends local commits to GitHub?", options: ["git commit", "git push", "git pull", "git add"], correct: 1, explain: "push uploads commits; pull downloads." },
    { q: "Create AND switch to a new branch in one command:", options: ["git branch new", "git checkout -b new", "git merge new", "git init new"], correct: 1, explain: "checkout -b (or git switch -c) creates + switches." },
    { q: "Vercel environment secrets are configured in:", options: ["package.json", "Vercel dashboard Environment Variables", "index.html", ".git folder"], correct: 1, explain: "Dashboard env vars inject at build/runtime, never in repo." },
    { q: "CI/CD means:", options: ["Code Inspection / Code Delivery", "Continuous Integration / Continuous Deployment", "Central Index / Cache Data", "Compiled Input / Compiled Output"], correct: 1, explain: "Automated test/build on push + automated deploy." },
  ],
  "PY-1": [
    { q: "Python me comment kis symbol se likhte hain?", options: ["//", "#", "/*", "<!--"], correct: 1, explain: "# single-line comment hai; // aur /* C/JS style hain." },
    { q: "len([1, 2, 3]) ka output?", options: ["2", "3", "4", "Error"], correct: 1, explain: "len() list ke items count karta hai = 3." },
    { q: "Kaunsa type immutable hai?", options: ["list", "dict", "tuple", "set"], correct: 2, explain: "Tuple banne ke baad change nahi hota." },
    { q: "f-string ka sahi syntax?", options: ["f'{name}'", "'f{name}'", "{name}.f()", "format[f]"], correct: 0, explain: "f'...' ke andar {var} direct interpolate hota hai." },
  ],
  "PY-2": [
    { q: "Class ka constructor kaunsa method hai?", options: ["__start__", "__init__", "construct()", "new()"], correct: 1, explain: "__init__ object ban-te hi call hota hai." },
    { q: "'self' kya hota hai?", options: ["Global variable", "Current object ka reference", "Parent class", "Module name"], correct: 1, explain: "self = jis object pe method call hua." },
    { q: "Custom exception banane ke liye?", options: ["class MyErr(Exception)", "def MyErr()", "raise class", "error MyErr"], correct: 0, explain: "Exception class ko inherit karo." },
    { q: "finally block kab chalta hai?", options: ["Sirf error pe", "Sirf success pe", "Hamesha", "Kabhi nahi"], correct: 2, explain: "finally try/except ke baad hamesha execute hota hai." },
  ],
  "PY-3": [
    { q: "Pandas me row+column label se select karne ka?", options: ["iloc", "loc", "select", "pick"], correct: 1, explain: "loc = labels, iloc = positions." },
    { q: "df.head(5) kya karta hai?", options: ["Last 5 rows", "First 5 rows", "Random 5", "Delete 5"], correct: 1, explain: "head() top rows dikhata hai." },
    { q: "Missing values drop karne ka method?", options: ["dropna()", "remove()", "clean()", "delnull()"], correct: 0, explain: "dropna() NaN rows/cols hatata hai." },
    { q: "Group-wise average ke liye?", options: ["df.group().mean()", "df.groupby('col').mean()", "df.avg('col')", "df.mean(by='col')"], correct: 1, explain: "groupby + agg function standard pattern hai." },
  ],
  "PY-4": [
    { q: "Matplotlib me chart dikhane ka command?", options: ["plt.show()", "plt.render()", "show(chart)", "plt.drawnow()"], correct: 0, explain: "plt.show() figure render karta hai." },
    { q: "Categorical comparison ke liye best chart?", options: ["Line", "Bar", "Pie only", "Scatter"], correct: 1, explain: "Bar chart categories compare karta hai clearly." },
    { q: "Do numeric variables ka relation dekhne ke liye?", options: ["Scatter", "Bar", "Pie", "Histogram"], correct: 0, explain: "Scatter correlation dikhata hai." },
    { q: "Seaborn kis ke upar bana hai?", options: ["NumPy only", "Matplotlib", "Pandas only", "Plotly"], correct: 1, explain: "Seaborn = Matplotlib ka high-level wrapper." },
  ],
  "PY-5": [
    { q: "Sirf matching rows ke liye join?", options: ["LEFT JOIN", "INNER JOIN", "FULL JOIN", "CROSS JOIN"], correct: 1, explain: "INNER = dono tables me match." },
    { q: "Rows count karne ka aggregate?", options: ["SUM()", "COUNT()", "TOTAL()", "NUM()"], correct: 1, explain: "COUNT(*) rows ginta hai." },
    { q: "WHERE aur HAVING me farq?", options: ["Same hai", "HAVING groups pe, WHERE rows pe", "WHERE groups pe", "HAVING sirf dates pe"], correct: 1, explain: "HAVING aggregate conditions ke liye." },
    { q: "Unique values ke liye keyword?", options: ["UNIQUE", "DISTINCT", "ONLY", "SOLE"], correct: 1, explain: "SELECT DISTINCT col duplicates hatata hai." },
  ],
  "PY-6": [
    { q: "Train/test split kyu karte hain?", options: ["Speed ke liye", "Unseen data pe evaluate karne ke liye", "Memory bachane", "Plot ke liye"], correct: 1, explain: "Test set = unseen data proxy." },
    { q: "Overfitting ka sign?", options: ["Train acc low, test acc high", "Train acc high, test acc low", "Dono low", "Dono same"], correct: 1, explain: "Model train data rat-ta hai, generalize nahi." },
    { q: "Classification metric kaunsa?", options: ["RMSE", "Accuracy", "R²", "MAE"], correct: 1, explain: "Accuracy classification ke liye; baaki regression metrics." },
    { q: "scikit-learn me model train karne ka method?", options: ["fit()", "train()", "learn()", "run()"], correct: 0, explain: "model.fit(X, y) standard API hai." },
  ],
  "CY-1": [
    { q: "DNS ka kaam kya hai?", options: ["IP → MAC", "Domain → IP", "HTTP → HTTPS", "Port → IP"], correct: 1, explain: "DNS domain names ko IP addresses me resolve karta hai." },
    { q: "HTTPS ka 'S' kisliye?", options: ["Speed", "TLS encryption", "SEO", "Session"], correct: 1, explain: "TLS/SSL encryption traffic secure karta hai." },
    { q: "Default HTTP port?", options: ["443", "80", "22", "8080"], correct: 1, explain: "80 = HTTP, 443 = HTTPS, 22 = SSH." },
    { q: "IP address kaunsa layer deta hai?", options: ["Application", "Network", "Physical", "Session"], correct: 1, explain: "Network layer addressing handle karti hai." },
  ],
  "CY-2": [
    { q: "File ke permissions dekhne ka command?", options: ["ls -l", "cat -p", "chmod view", "perm"], correct: 0, explain: "ls -l long listing me rwx permissions dikhata hai." },
    { q: "Root user ka UID?", options: ["1", "0", "1000", "999"], correct: 1, explain: "root ka UID 0 hota hai." },
    { q: "File dhundne ka powerful tool?", options: ["search", "find", "locateonly", "grep -f"], correct: 1, explain: "find path-based search karta hai." },
    { q: "Text pattern search karne ka command?", options: ["grep", "seek", "match", "scan"], correct: 0, explain: "grep regex se lines match karta hai." },
  ],
  "CY-3": [
    { q: "' OR 1=1 -- kis attack me dikhta hai?", options: ["XSS", "SQLi", "CSRF", "DDoS"], correct: 1, explain: "Yeh classic SQL injection payload hai." },
    { q: "Stored XSS kahan save hota hai?", options: ["Browser me", "Server/DB me", "Proxy me", "DNS me"], correct: 1, explain: "Stored XSS server pe persist hota hai — sabse dangerous." },
    { q: "CSRF token kisliye?", options: ["Encryption", "Request authenticity", "Speed", "Caching"], correct: 1, explain: "CSRF token forged requests rokta hai." },
    { q: "SQLi se bachne ka best tareeka?", options: ["Input length limit", "Parameterized queries", "CSS filter", "HTTP only"], correct: 1, explain: "Parameterized/prepared queries injection khatam karti hain." },
  ],
  "CY-4": [
    { q: "nmap -sV kya karta hai?", options: ["OS scan", "Service/version detect", "Stealth only", "UDP only"], correct: 1, explain: "-sV service versions detect karta hai." },
    { q: "Subdomain enumeration ka tool?", options: ["subfinder", "ping", "traceroute", "whois only"], correct: 0, explain: "subfinder/assetfinder subdomains enumerate karte hain." },
    { q: "Recon ka pehla rule?", options: ["Turant attack", "Scope + permission verify", "Social media pe post", "Tools buy"], correct: 1, explain: "Bina scope/permission recon bhi illegal ho sakta hai." },
    { q: "robots.txt kisliye useful hai?", options: ["Passwords", "Hidden paths hint", "Encryption keys", "DNS records"], correct: 1, explain: "robots.txt aksar internal paths reveal karta hai." },
  ],
  "CY-5": [
    { q: "SIEM ka main kaam?", options: ["Firewall banana", "Logs collect + correlate", "Backups", "DNS serve"], correct: 1, explain: "SIEM logs aggregate karke alerts/correlation deta hai." },
    { q: "Wireshark me sirf HTTP dekhne ka filter?", options: ["http", "tcp==80", "show http", "filter.http()"], correct: 0, explain: "Display filter 'http' HTTP traffic dikhata hai." },
    { q: "Incident response ka pehla step?", options: ["Erase logs", "Identification/detection", "Reinstall OS", "Notify media"], correct: 1, explain: "Pehle detect/identify, phir contain/eradicate/recover." },
    { q: "Blue team ka role?", options: ["Attack karna", "Defend + monitor", "Bug sell", "Pentest only"], correct: 1, explain: "Blue team defense, monitoring, response karta hai." },
  ],
  "CY-6": [
    { q: "Bug report me sabse zaroori cheez?", options: ["Lambi story", "Clear reproduction steps", "Screenshots only", "Tool list"], correct: 1, explain: "Repro steps ke bina report reject hoti hai." },
    { q: "VDP vs Bug Bounty farq?", options: ["Same hai", "VDP = points/hall of fame, bounty = cash", "VDP cash deta hai", "Bounty free hota hai"], correct: 1, explain: "VDP recognition deta hai, bounty program cash." },
    { q: "Responsible disclosure ka matlab?", options: ["Turant tweet", "Vendor ko time dena fix ke liye", "Exploit sell karna", "Silent rehna"], correct: 1, explain: "Vendor ko fix window dena ethical disclosure hai." },
    { q: "Write-up publish karne se pehle?", options: ["Hamesha turant", "Program policy check karo", "Kabhi nahi", "Sirf friends ko"], correct: 1, explain: "Kuch programs disclosure timeline/policy rakhte hain." },
  ],
    "DSA-1": [
    { q: "Nested loop (n × n) ki time complexity?", options: ["O(n)", "O(n log n)", "O(n²)", "O(2ⁿ)"], correct: 2, explain: "Outer n × inner n = n² operations." },
    { q: "Binary search ki time complexity?", options: ["O(n)", "O(log n)", "O(n²)", "O(1)"], correct: 1, explain: "Har step me search space half hota hai." },
    { q: "ArrayList ka random access time?", options: ["O(n)", "O(1)", "O(log n)", "O(n²)"], correct: 1, explain: "Array-backed hai, index se direct access." },
    { q: "Space complexity kya measure karti hai?", options: ["Time", "Extra memory used", "Lines of code", "CPU usage"], correct: 1, explain: "Input ke alawa extra space jo algorithm use karta hai." },
  ],
  "DSA-2": [
    { q: "Two Sum ka optimal approach?", options: ["Nested loops O(n²)", "HashMap O(n)", "Sorting O(n log n)", "Recursion"], correct: 1, explain: "HashMap me complements store karo — O(n) time." },
    { q: "Sliding window kab use hota hai?", options: ["Sorted array pe", "Contiguous subarray problems", "Linked list pe", "Tree traversal"], correct: 1, explain: "Fixed/variable size window jab contiguous range chahiye." },
    { q: "3Sum me duplicates skip karne ka best way?", options: ["HashSet use karo", "Sort + skip same values", "Map me store", "Impossible hai"], correct: 1, explain: "Sort karo aur same values ko skip karo pointers me." },
    { q: "Kadane's algorithm kiske liye?", options: ["Shortest path", "Max subarray sum", "Sorting", "Tree height"], correct: 1, explain: "O(n) me max contiguous subarray sum find karta hai." },
  ],
  "DSA-3": [
    { q: "Linked list cycle detect karne ka best method?", options: ["HashSet", "Floyd's slow/fast pointers", "Reverse list", "Count nodes"], correct: 1, explain: "Slow/fast pointers — O(1) space, O(n) time." },
    { q: "Stack ka LIFO principle matlab?", options: ["First in first out", "Last in first out", "Random access", "Priority based"], correct: 1, explain: "Jo last push hua wohi pehle pop hota hai." },
    { q: "Queue me dequeue kis end se hota hai?", options: ["Back/rear", "Front", "Middle", "Random"], correct: 1, explain: "FIFO — front se nikalta hai, rear se add hota hai." },
    { q: "Monotonic stack kab useful hai?", options: ["Sorting", "Next greater/smaller element", "Tree traversal", "Graph BFS"], correct: 1, explain: "Next greater/smaller element O(n) me find karne ke liye." },
  ],
  "DSA-4": [
    { q: "HashMap collision resolution ka tareeka?", options: ["Delete key", "Chaining ya open addressing", "Sort karo", "Error throw"], correct: 1, explain: "Linked list (chaining) ya probing (open addressing)." },
    { q: "Min-heap me root element?", options: ["Maximum", "Minimum", "Random", "Median"], correct: 1, explain: "Min-heap me root hamesha minimum element hota hai." },
    { q: "Greedy algorithm kab fail hota hai?", options: ["Kabhi nahi", "Jab local optimal != global optimal", "Always fails", "Sirf graphs me"], correct: 1, explain: "Greedy tabhi kaam karta hai jab locally optimal choice globally bhi optimal ho." },
    { q: "Top-K largest elements efficiently nikalne ke liye?", options: ["Sort O(n log n)", "Min-heap of size K — O(n log K)", "Bubble sort", "Linear scan"], correct: 1, explain: "K-size min-heap rakho, har element compare karo — O(n log K)." },
  ],
  "DSA-5": [
    { q: "BST me left child parent se?", options: ["Bada hota hai", "Chhota hota hai", "Equal hota hai", "Random"], correct: 1, explain: "BST property: left < parent < right." },
    { q: "Inorder traversal BST pe kya deta hai?", options: ["Reverse order", "Sorted order", "Random order", "Level order"], correct: 1, explain: "Inorder (L-Root-R) BST pe sorted sequence deta hai." },
    { q: "Tree ki height find karne ka approach?", options: ["BFS only", "Recursion — max(left, right) + 1", "Count nodes", "Sort karo"], correct: 1, explain: "Recursive: height = max(leftHeight, rightHeight) + 1." },
    { q: "LCA (Lowest Common Ancestor) kya hai?", options: ["Root node", "Deepest node jo dono ka ancestor", "Leaf node", "Parent of root"], correct: 1, explain: "Woh deepest node jiske subtree me dono target nodes hain." },
  ],
  "DSA-6": [
    { q: "BFS kis data structure use karta hai?", options: ["Stack", "Queue", "Heap", "Array"], correct: 1, explain: "BFS level-by-level chalta hai — queue FIFO perfect fit hai." },
    { q: "DFS kis data structure use karta hai (iterative)?", options: ["Queue", "Stack", "Heap", "HashMap"], correct: 1, explain: "DFS depth-first jaata hai — stack LIFO use hota hai." },
    { q: "Dijkstra negative weights handle kar sakta hai?", options: ["Haan, always", "Nahi — Bellman-Ford chahiye", "Kabhi kabhi", "Sirf directed me"], correct: 1, explain: "Dijkstra greedy hai — negative edges pe galat answer de sakta hai." },
    { q: "Topological sort kis graph pe possible hai?", options: ["Undirected", "Directed Acyclic Graph (DAG)", "Cyclic graph", "Complete graph"], correct: 1, explain: "Topological sort sirf DAG pe possible hai (cycles allowed nahi)." },
  ],
  "DSA-7": [
    { q: "DP problem identify karne ka pehla signal?", options: ["Sorting chahiye", "Overlapping subproblems + optimal substructure", "Graph hai", "String hai"], correct: 1, explain: "Agar subproblems repeat ho rahe hain aur optimal solution sub-solutions se banta hai → DP." },
    { q: "Memoization ka matlab?", options: ["Bottom-up", "Top-down + caching", "Greedy choice", "Brute force"], correct: 1, explain: "Recursive calls ke results cache karo — duplicate compute bachao." },
    { q: "0/1 Knapsack ki time complexity?", options: ["O(n)", "O(n × W) where W = capacity", "O(2ⁿ)", "O(n log n)"], correct: 1, explain: "Pseudo-polynomial: items × capacity states." },
    { q: "LCS (Longest Common Subsequence) approach?", options: ["Greedy", "2D DP table", "Sorting", "Hashing"], correct: 1, explain: "2D table jaha dp[i][j] = LCS of prefixes i,j." },
  ],
  "DSA-8": [
    { q: "Mock interview me sabse pehle kya karo?", options: ["Code likho", "Problem clarify + approach explain", "Ask for answer", "Jump to solution"], correct: 1, explain: "Clarify karo, edge cases pucho, approach discuss karo — phir code." },
    { q: "Stuck ho to interviewer se kya pucho?", options: ["Give me answer", "Hint or direction for X approach?", "I quit", "Next question"], correct: 1, explain: "Specific hint maango — shows problem-solving maturity." },
    { q: "System design interview freshers se expect kya?", options: ["Full production system", "High-level components + tradeoffs", "Code only", "No expectations"], correct: 1, explain: "Freshers se high-level understanding + basic tradeoffs expected hain." },
    { q: "Resume me DSA projects kaise dikhao?", options: ["Sirf problem count", "Links + patterns covered + impact", "Certificates only", "Mat dikhao"], correct: 1, explain: "Public repo + blog + patterns = proof of depth." },
  ],
    "APP-1": [
    { q: "React Native me UI banane ke liye kya use hota hai?", options: ["HTML tags", "React components (View, Text)", "XML", "jQuery"], correct: 1, explain: "React Native me View, Text, Image jaise components hote hain — HTML nahi." },
    { q: "Expo ka main advantage kya hai?", options: ["Faster performance", "No native setup required", "Cheaper hosting", "Better animations"], correct: 1, explain: "Expo se bina Xcode/Android Studio ke apps develop kar sakte ho." },
    { q: "React Native me styling ke liye kya use hota hai?", options: ["CSS files", "StyleSheet.create()", "SCSS", "LESS"], correct: 1, explain: "StyleSheet.create() se optimized styles bante hain." },
    { q: "Expo Go app kya karta hai?", options: ["Build karta hai", "Phone pe app test karne deta hai", "Deploy karta hai", "Code compile karta hai"], correct: 1, explain: "Expo Go se development build phone pe instantly test hoti hai." },
  ],
  "APP-2": [
    { q: "React Native me multi-screen navigation ke liye kya use hota hai?", options: ["<a> tags", "React Navigation / Expo Router", "window.location", "Link from Next.js"], correct: 1, explain: "React Navigation ya Expo Router se screens navigate hoti hain." },
    { q: "Bottom tab navigation ke liye kaunsa component?", options: ["StackNavigator", "Tab.Navigator", "DrawerNavigator", "ModalStack"], correct: 1, explain: "Tab.Navigator se bottom tabs bante hain." },
    { q: "Expo Router me file-based routing matlab?", options: ["Manual route config", "Folder structure se routes bante hain", "Database se routes", "API se routes"], correct: 1, explain: "app/ folder me files automatically routes ban jati hain." },
    { q: "Stack navigation me back button kaise add hota hai?", options: ["Manual button chahiye", "Automatically header me aata hai", "URL parameter se", "Gesture se only"], correct: 1, explain: "Stack navigator automatically back button header me dikhata hai." },
  ],
  "APP-3": [
    { q: "Long lists render karne ke liye best component?", options: ["ScrollView", "FlatList", "map() function", "View + map"], correct: 1, explain: "FlatList lazy rendering karta hai — sirf visible items render hote hain." },
    { q: "FlatList me 'keyExtractor' ka kaam?", options: ["Styling", "Unique key dena har item ko", "Data fetch karna", "Animation"], correct: 1, explain: "keyExtractor se har item ko unique ID milti hai — React reconciliation ke liye." },
    { q: "Pull-to-refresh implement karne ke liye?", options: ["ScrollView only", "RefreshControl component", "Gesture handler", "Swipe gesture"], correct: 1, explain: "RefreshControl component ScrollView/FlatList me wrap karte hain." },
    { q: "NativeWind kya hai?", options: ["Native module", "Tailwind CSS for React Native", "Animation library", "State manager"], correct: 1, explain: "NativeWind se Tailwind classes React Native me use kar sakte ho." },
  ],
  "APP-4": [
    { q: "React Native me data persist karne ke liye (localStorage equivalent)?", options: ["localStorage", "AsyncStorage", "cookies", "sessionStorage"], correct: 1, explain: "AsyncStorage mobile ka localStorage hai — key-value pairs." },
    { q: "API call karne ke liye React Native me kya use hota hai?", options: ["XMLHttpRequest only", "fetch() ya axios", "jQuery.ajax", "WebSocket only"], correct: 1, explain: "fetch() built-in hai, axios popular alternative hai." },
    { q: "Global state management ke liye simple solution?", options: ["Redux only", "Context API", "localStorage", "Props drilling"], correct: 1, explain: "Context API se prop drilling avoid hoti hai — simple cases ke liye perfect." },
    { q: "AsyncStorage.getItem() kya return karta hai?", options: ["Direct value", "Promise", "Callback", "Sync value"], correct: 1, explain: "AsyncStorage async hai — Promise return karta hai, await karna padta hai." },
  ],
  "APP-5": [
    { q: "Camera access ke liye pehle kya chahiye?", options: ["API key", "User permission", "Internet", "GPS"], correct: 1, explain: "Camera, location, notifications — sab ke liye user permission chahiye." },
    { q: "Expo me camera use karne ke liye component?", options: ["<Camera>", "expo-camera ka <Camera>", "<Webcam>", "<Video>"], correct: 1, explain: "expo-camera package se <Camera> component import hota hai." },
    { q: "Push notifications schedule karne ke liye?", options: ["setTimeout", "expo-notifications package", "Alert.alert", "console.log"], correct: 1, explain: "expo-notifications se local + push notifications schedule hote hain." },
    { q: "GPS location get karne ka method?", options: ["navigator.geolocation", "Location.getCurrentPositionAsync()", "window.location", "GPS.get()"], correct: 1, explain: "expo-location me getCurrentPositionAsync() use hota hai." },
  ],
  "APP-6": [
    { q: "Supabase realtime subscriptions ke liye kya use hota hai?", options: ["WebSockets manually", ".on('postgres_changes') method", "Polling", "REST API"], correct: 1, explain: "Supabase ka .on('postgres_changes') se realtime updates milte hain." },
    { q: "EAS Build kya karta hai?", options: ["Code compile locally", "Cloud pe APK/IPA build karta hai", "Deploy karta hai", "Test karta hai"], correct: 1, explain: "EAS Build cloud pe Android APK aur iOS IPA build karta hai." },
    { q: "Play Store pe app submit karne ke liye kya chahiye?", options: ["Free account", "Google Play Developer account ($25 one-time)", "Monthly subscription", "Nothing"], correct: 1, explain: "Google Play Developer account $25 one-time fee hai." },
    { q: "React Native app ko production me le jaane ka best way?", options: ["Direct upload", "EAS Build + EAS Submit", "Manual APK", "GitHub only"], correct: 1, explain: "EAS Build se APK banao, EAS Submit se Play Store pe upload karo." },
  ],
    "DO-1": [
    { q: "Linux me file permissions 755 matlab?", options: ["rwxr-xr-x", "rw-r--r--", "rwxrwxrwx", "r--r--r--"], correct: 0, explain: "7=rwx (owner), 5=r-x (group), 5=r-x (others)." },
    { q: "Bash script ko executable banane ka command?", options: ["chmod +x script.sh", "chown script.sh", "run script.sh", "exec script.sh"], correct: 0, explain: "chmod +x se execute permission milti hai." },
    { q: "Current directory dekhne ka command?", options: ["cd", "pwd", "ls", "dir"], correct: 1, explain: "pwd = print working directory." },
    { q: "Cron job kya karta hai?", options: ["Manual task", "Scheduled recurring task", "One-time task", "Background process only"], correct: 1, explain: "Cron se tasks time-based schedule hote hain." },
  ],
  "DO-2": [
    { q: "CI/CD me 'CI' ka matlab?", options: ["Code Integration", "Continuous Integration", "Central Index", "Compiled Input"], correct: 1, explain: "Continuous Integration = auto build+test on every push." },
    { q: "Git rebase ka main use?", options: ["Merge commits banane", "Linear history banane", "Delete branches", "Undo commits"], correct: 1, explain: "Rebase commits ko linear history me rewrite karta hai." },
    { q: "GitHub Actions workflow kis file me hota hai?", options: [".github/workflows/*.yml", "package.json", "Dockerfile", "README"], correct: 0, explain: "Workflows .github/workflows/ me YAML files hote hain." },
    { q: "Secrets (API keys) CI me kahan rakhte hain?", options: ["Code me hardcode", "GitHub Secrets / env vars", "README", "Public repo"], correct: 1, explain: "Secrets encrypted env vars me inject hote hain — code me kabhi nahi." },
  ],
  "DO-3": [
    { q: "Docker image vs container?", options: ["Same cheez", "Image = blueprint, container = running instance", "Container = blueprint", "Image = running"], correct: 1, explain: "Image static template hai; container uska running instance." },
    { q: "Dockerfile me 'FROM' kya karta hai?", options: ["File copy", "Base image set karta hai", "Port expose", "Command run"], correct: 1, explain: "FROM base image define karta hai jispe build hota hai." },
    { q: "Multi-stage build ka fayda?", options: ["Faster runtime", "Smaller final image", "More layers", "Better logs"], correct: 1, explain: "Build tools final image me nahi jaate — image chhoti hoti hai." },
    { q: "docker-compose kisliye?", options: ["Single container", "Multi-container apps define karne", "Image build", "Network delete"], correct: 1, explain: "compose se app+db jaise multiple services ek saath chalte hain." },
  ],
  "DO-4": [
    { q: "Kubernetes me sabse chhota unit?", options: ["Node", "Pod", "Cluster", "Service"], correct: 1, explain: "Pod = smallest deployable unit (1+ containers)." },
    { q: "Deployment ka kaam?", options: ["Network routing", "Replicas manage + rollout", "Storage", "Logging"], correct: 1, explain: "Deployment desired replicas + rolling updates handle karta hai." },
    { q: "Service kya provide karta hai?", options: ["Stable network endpoint to Pods", "Storage volume", "Secrets", "CPU limits"], correct: 0, explain: "Service Pods ko stable IP/DNS deta hai (Pods ephemeral hain)." },
    { q: "ConfigMap vs Secret?", options: ["Same", "Secret encrypted sensitive data ke liye", "ConfigMap encrypted", "Secret public data"], correct: 1, explain: "Secret base64/encrypted sensitive data; ConfigMap normal config." },
  ],
  "DO-5": [
    { q: "AWS me serverless compute kaunsa?", options: ["EC2", "Lambda", "S3", "RDS"], correct: 1, explain: "Lambda = serverless functions, pay-per-invocation." },
    { q: "S3 kisliye use hota hai?", options: ["Compute", "Object storage", "Database", "Networking"], correct: 1, explain: "S3 = scalable object storage (files, images, backups)." },
    { q: "IAM ka kaam?", options: ["Storage", "Identity + access control", "Compute", "Monitoring"], correct: 1, explain: "IAM users/roles/permissions manage karta hai." },
    { q: "Least privilege principle matlab?", options: ["Sabko full access", "Sirf zaroori minimum permissions", "No access", "Root access always"], correct: 1, explain: "Har identity ko sirf utna access jo kaam ke liye chahiye." },
  ],
  "DO-6": [
    { q: "Infrastructure as Code (IaC) ka fayda?", options: ["Manual clicks", "Version-controlled reproducible infra", "Slower setup", "No documentation"], correct: 1, explain: "IaC se infra code me hota hai — repeatable + reviewable." },
    { q: "Terraform state file kya store karta hai?", options: ["App code", "Current infra mapping", "Logs", "Secrets only"], correct: 1, explain: "State = Terraform ka record of what it created." },
    { q: "Prometheus kya karta hai?", options: ["Deploys apps", "Metrics collect + alert", "Stores files", "Manages DNS"], correct: 1, explain: "Prometheus time-series metrics scrape karta hai + alerts." },
    { q: "Grafana ka role?", options: ["Collect metrics", "Visualize dashboards", "Provision infra", "Run containers"], correct: 1, explain: "Grafana Prometheus data ko dashboards me dikhata hai." },
  ],
};