export type SItem = { wrong: string; right: string; why: string; hindi: string };
export type Pack = { id: string; emoji: string; title: string; desc: string; items: SItem[] };

export const PACKS_A: Pack[] = [
  {
    id: "mistakes", emoji: "⚠️", title: "Daily Mistakes", desc: "Fix the most common Indian-English errors",
    items: [
      { wrong: "I am having a doubt.", right: "I have a doubt.", why: "'have' is stative — no -ing form", hindi: "मुझे एक शंका है।" },
      { wrong: "I am agree.", right: "I agree.", why: "'agree' is a verb, not adjective", hindi: "मैं सहमत हूँ।" },
      { wrong: "I didn't went there.", right: "I didn't go there.", why: "after 'didn't', use base verb", hindi: "मैं वहाँ नहीं गया।" },
      { wrong: "I am boring.", right: "I am bored.", why: "-ed for feelings, -ing for things", hindi: "मैं ऊब रहा हूँ।" },
      { wrong: "Myself Rahul.", right: "I am Rahul.", why: "never start with 'myself'", hindi: "मैं राहुल हूँ।" },
      { wrong: "He is more taller.", right: "He is taller.", why: "don't double the comparative", hindi: "वह ज़्यादा लंबा है।" },
      { wrong: "I am knowing him.", right: "I know him.", why: "'know' is stative — no -ing", hindi: "मैं उसे जानता हूँ।" },
      { wrong: "She don't like tea.", right: "She doesn't like tea.", why: "she/he/it takes 'doesn't'", hindi: "उसे चाय पसंद नहीं।" },
      { wrong: "I have 20 years.", right: "I am 20 years old.", why: "age uses 'am/is/are', not 'have'", hindi: "मैं 20 साल का हूँ।" },
      { wrong: "He is my cousin brother.", right: "He is my cousin.", why: "'brother' is redundant in English", hindi: "वह मेरा चचेरा भाई है।" },
      { wrong: "I will revert back.", right: "I will reply.", why: "'revert back' repeats itself", hindi: "मैं जवाब दूँगा।" },
      { wrong: "Do one thing.", right: "Please do this.", why: "sounds rude in English", hindi: "कृपया यह करें।" },
      { wrong: "He is elder than me.", right: "He is older than me.", why: "'elder' is only for family, no 'than'", hindi: "वह मुझसे बड़ा है।" },
      { wrong: "I prefer tea than coffee.", right: "I prefer tea to coffee.", why: "'prefer' uses 'to', not 'than'", hindi: "मैं चाय ज़्यादा पसंद करता हूँ।" },
      { wrong: "She is married with a doctor.", right: "She is married to a doctor.", why: "married TO someone, not with", hindi: "उसकी शादी डॉक्टर से हुई।" },
      { wrong: "Where you are going?", right: "Where are you going?", why: "questions: verb before subject", hindi: "आप कहाँ जा रहे हैं?" },
      { wrong: "I am understanding.", right: "I understand.", why: "'understand' is stative", hindi: "मैं समझता हूँ।" },
      { wrong: "He is good in English.", right: "He is good at English.", why: "good AT a skill, not in", hindi: "वह अंग्रेज़ी में अच्छा है।" },
      { wrong: "Let us discuss about it.", right: "Let us discuss it.", why: "'discuss' takes no 'about'", hindi: "इस पर चर्चा करें।" },
      { wrong: "I am suffering from fever.", right: "I have a fever.", why: "'suffering' is too strong for common illness", hindi: "मुझे बुखार है।" },
      { wrong: "He gave me an advice.", right: "He gave me advice.", why: "'advice' is uncountable — no 'an'", hindi: "उसने मुझे सलाह दी।" },
      { wrong: "I am eating food since morning.", right: "I have been eating since morning.", why: "ongoing action needs present perfect continuous", hindi: "मैं सुबह से खा रहा हूँ।" },
      { wrong: "My hairs are black.", right: "My hair is black.", why: "'hair' on head is singular", hindi: "मेरे बाल काले हैं।" },
      { wrong: "I have a blue shirt and a red one.", right: "I have a blue shirt and a red one.", why: "this one is correct — good!", hindi: "मेरे पास नीली और लाल कमीज़ है।" },
      { wrong: "He is a M.P.", right: "He is an M.P.", why: "sound 'em' starts with vowel", hindi: "वह सांसद हैं।" },
      { wrong: "I went to my native.", right: "I went to my hometown.", why: "'native' alone is incomplete", hindi: "मैं अपने गाँव गया।" },
      { wrong: "She is a M.A.", right: "She is an M.A.", why: "'em' starts with vowel sound", hindi: "वह एम.ए. हैं।" },
      { wrong: "One of my friend came.", right: "One of my friends came.", why: "'one of' needs plural noun", hindi: "मेरा एक दोस्त आया।" },
      { wrong: "I didn't knew.", right: "I didn't know.", why: "after 'did', use base verb", hindi: "मुझे नहीं पता था।" },
      { wrong: "He is more intelligent than her.", right: "He is more intelligent than she (is).", why: "compare subjects, not objects", hindi: "वह उससे ज़्यादा बुद्धिमान है।" },
    ],
  },
  {
    id: "interview", emoji: "👔", title: "Interview Sentences", desc: "Sound professional instantly",
    items: [
      { wrong: "I passed out in 2022.", right: "I graduated in 2022.", why: "'passed out' = became unconscious!", hindi: "मैंने 2022 में स्नातक किया।" },
      { wrong: "Kindly revert back soon.", right: "Please reply soon.", why: "'revert back' is redundant", hindi: "कृपया जल्दी जवाब दें।" },
      { wrong: "I am fresher.", right: "I am a fresher.", why: "article 'a' is needed", hindi: "मैं नया स्नातक हूँ।" },
      { wrong: "He suggested me to join.", right: "He advised me to join.", why: "'suggest' cannot take object + to", hindi: "उसने मुझे जुड़ने की सलाह दी।" },
      { wrong: "I have five years experience.", right: "I have five years of experience.", why: "'of' is needed", hindi: "मुझे पाँच साल का अनुभव है।" },
      { wrong: "I am good at multi-tasking.", right: "I am good at multitasking.", why: "no hyphen needed", hindi: "मैं एक साथ कई काम कर सकता हूँ।" },
      { wrong: "My weakness is I work too hard.", right: "I tend to work very hard.", why: "sounds more natural", hindi: "मैं बहुत मेहनत करता हूँ।" },
      { wrong: "I am very much interested in this job.", right: "I am very interested in this job.", why: "'very much' is too strong here", hindi: "मुझे इस नौकरी में बहुत रुचि है।" },
      { wrong: "Tell me about yourself.", right: "I would be happy to share my background.", why: "responding to the question", hindi: "मैं अपना परिचय दूँगा।" },
      { wrong: "I want a good salary.", right: "I am looking for fair compensation.", why: "more professional", hindi: "मुझे उचित वेतन चाहिए।" },
      { wrong: "I don't have any weakness.", right: "I am working on improving my time management.", why: "shows self-awareness", hindi: "मैं अपनी समय-प्रबंधन सुधार रहा हूँ।" },
      { wrong: "I can do anything.", right: "I am adaptable and quick to learn.", why: "sounds more realistic", hindi: "मैं जल्दी सीखता हूँ।" },
      { wrong: "My previous boss was bad.", right: "I learned a lot from my previous role.", why: "stay positive", hindi: "मैंने पिछली नौकरी से बहुत सीखा।" },
      { wrong: "I am leaving because of low salary.", right: "I am seeking new growth opportunities.", why: "more professional reason", hindi: "मैं नए अवसर चाहता हूँ।" },
      { wrong: "Can I ask a doubt?", right: "May I ask a question?", why: "'doubt' = suspicion; 'question' = inquiry", hindi: "क्या मैं एक सवाल पूछ सकता हूँ?" },
      { wrong: "I will give my 100 percent.", right: "I will give my best effort.", why: "sounds more humble", hindi: "मैं अपना सर्वश्रेष्ठ दूँगा।" },
      { wrong: "I want to settle abroad.", right: "I am open to international opportunities.", why: "more professional", hindi: "मैं विदेश में अवसर के लिए तैयार हूँ।" },
      { wrong: "I do coding.", right: "I develop software applications.", why: "more precise", hindi: "मैं सॉफ्टवेयर बनाता हूँ।" },
      { wrong: "I am looking for a good package.", right: "I am looking for competitive compensation.", why: "'package' is informal", hindi: "मुझे उचित वेतन चाहिए।" },
      { wrong: "I am a quick learner.", right: "I pick up new skills quickly.", why: "more natural phrasing", hindi: "मैं जल्दी सीखता हूँ।" },
      { wrong: "I work well under pressure.", right: "I stay focused under tight deadlines.", why: "more specific", hindi: "मैं दबाव में भी ध्यान रखता हूँ।" },
      { wrong: "My hobby is watching movies.", right: "I enjoy watching films in my free time.", why: "more descriptive", hindi: "मुझे फ़िल्में देखना पसंद है।" },
      { wrong: "I live in Mumbai only.", right: "I live in Mumbai.", why: "'only' is redundant", hindi: "मैं मुंबई में रहता हूँ।" },
      { wrong: "I am from Delhi only.", right: "I am from Delhi.", why: "drop 'only'", hindi: "मैं दिल्ली से हूँ।" },
      { wrong: "When will I get the offer letter?", right: "Could you share the next steps?", why: "sounds more polite", hindi: "अगला कदम क्या है?" },
      { wrong: "My expected salary is 10 LPA.", right: "I am expecting compensation around 10 LPA, negotiable.", why: "shows flexibility", hindi: "मुझे 10 LPA चाहिए, बातचीत योग्य।" },
      { wrong: "I can join immediately.", right: "I am available to join at short notice.", why: "more professional", hindi: "मैं जल्दी जुड़ सकता हूँ।" },
      { wrong: "Do you have any doubts?", right: "Do you have any questions?", why: "recruiter uses 'questions'", hindi: "क्या आपके कोई सवाल हैं?" },
      { wrong: "I am very hardworking.", right: "I am committed to delivering results.", why: "shows outcomes, not just effort", hindi: "मैं परिणाम देने के लिए प्रतिबद्ध हूँ।" },
      { wrong: "I have done B.Tech.", right: "I hold a B.Tech degree.", why: "more formal", hindi: "मेरे पास बी.टेक की डिग्री है।" },
    ],
  },
  {
    id: "talk", emoji: "🗣️", title: "Daily Talk", desc: "Natural sentences for everyday life",
    items: [
      { wrong: "What is your good name?", right: "What is your name?", why: "'good name' is not English", hindi: "आपका नाम क्या है?" },
      { wrong: "Where you are going?", right: "Where are you going?", why: "question: verb before subject", hindi: "आप कहाँ जा रहे हैं?" },
      { wrong: "I will do it later time.", right: "I will do it later.", why: "'later time' is redundant", hindi: "मैं बाद में करूँगा।" },
      { wrong: "How are you feeling today?", right: "How are you today?", why: "simpler is better", hindi: "आज आप कैसे हैं?" },
      { wrong: "I am coming from Delhi.", right: "I am from Delhi.", why: "use 'from' for origin", hindi: "मैं दिल्ली से हूँ।" },
      { wrong: "Let's meet at evening.", right: "Let's meet in the evening.", why: "'in the' needed", hindi: "शाम को मिलते हैं।" },
      { wrong: "What time you will come?", right: "What time will you come?", why: "question: will before you", hindi: "आप कितने बजे आएँगे?" },
      { wrong: "I reached home safely.", right: "I got home safely.", why: "'got home' more natural", hindi: "मैं सुरक्षित घर पहुँचा।" },
      { wrong: "I will inform you.", right: "I will let you know.", why: "'let you know' is friendlier", hindi: "मैं आपको बताऊँगा।" },
      { wrong: "I am feeling very tired.", right: "I am really tired.", why: "'really' sounds more natural", hindi: "मैं बहुत थका हूँ।" },
      { wrong: "Please sit on the chair.", right: "Please have a seat.", why: "more polite", hindi: "कृपया बैठिए।" },
      { wrong: "Do you want to eat something?", right: "Would you like something to eat?", why: "more polite", hindi: "क्या आप कुछ खाना चाहेंगे?" },
      { wrong: "I am having two brothers.", right: "I have two brothers.", why: "'have' for relationships", hindi: "मेरे दो भाई हैं।" },
      { wrong: "She is my childhood friend only.", right: "She has been my friend since childhood.", why: "drop 'only'", hindi: "वह बचपन की दोस्त है।" },
      { wrong: "Let's go outside and eat.", right: "Let's eat out.", why: "more natural phrase", hindi: "बाहर खाते हैं।" },
      { wrong: "I am waiting since one hour.", right: "I have been waiting for an hour.", why: "use 'for' with duration", hindi: "मैं एक घंटे से इंतज़ार कर रहा हूँ।" },
      { wrong: "I will call you back soon.", right: "I'll call you back shortly.", why: "'shortly' sounds better", hindi: "मैं जल्दी वापस कॉल करूँगा।" },
      { wrong: "Please switch off your mobile.", right: "Please turn off your phone.", why: "'turn off' more universal", hindi: "कृपया फोन बंद करें।" },
      { wrong: "I will give you a lift.", right: "I can drop you off.", why: "more natural", hindi: "मैं आपको छोड़ दूँगा।" },
      { wrong: "I will pick you up at 5.", right: "I'll pick you up at 5.", why: "contraction sounds natural", hindi: "मैं 5 बजे लेने आऊँगा।" },
      { wrong: "Do one thing, call him.", right: "Why don't you call him?", why: "less bossy", hindi: "आप उसे कॉल क्यों नहीं करते?" },
      { wrong: "You must come to my house.", right: "Please come over to my place.", why: "'come over' is friendlier", hindi: "मेरे घर आइए।" },
      { wrong: "I am not getting you.", right: "I don't understand.", why: "clearer", hindi: "मुझे समझ नहीं आ रहा।" },
      { wrong: "I am not in mood.", right: "I am not in the mood.", why: "'the' is needed", hindi: "मेरा मूड नहीं है।" },
      { wrong: "Let's have some fun.", right: "Let's have some fun.", why: "this is correct!", hindi: "चलो मज़े करते हैं।" },
      { wrong: "I will meet you tomorrow.", right: "I'll see you tomorrow.", why: "'see you' is more casual", hindi: "कल मिलते हैं।" },
      { wrong: "What you want?", right: "What would you like?", why: "more polite", hindi: "आप क्या चाहेंगे?" },
      { wrong: "Give me one coffee.", right: "Can I have a coffee, please?", why: "polite request", hindi: "क्या मुझे एक कॉफी मिलेगी?" },
      { wrong: "I am not feeling good.", right: "I am not feeling well.", why: "'well' for health, 'good' for mood", hindi: "मैं अच्छा महसूस नहीं कर रहा।" },
      { wrong: "It's raining outside.", right: "It's raining outside.", why: "this is correct!", hindi: "बाहर बारिश हो रही है।" },
    ],
  },
  {
    id: "email", emoji: "📧", title: "Email & Messages", desc: "Write like a pro at work",
    items: [
      { wrong: "Hi sir, I am writing to inform.", right: "Dear Sir, I am writing to inform you that...", why: "'Dear' is standard in emails", hindi: "महोदय, मैं आपको सूचित करने के लिए लिख रहा हूँ।" },
      { wrong: "Please do the needful.", right: "Please take the necessary action.", why: "'do the needful' is old-fashioned", hindi: "कृपया आवश्यक कार्रवाई करें।" },
      { wrong: "As per our telephonic conversation.", right: "As discussed on the phone.", why: "modern, simpler", hindi: "जैसा कि फोन पर चर्चा हुई।" },
      { wrong: "Please find attached the file.", right: "Please find the file attached.", why: "better word order", hindi: "कृपया संलग्न फ़ाइल देखें।" },
      { wrong: "I am attaching herewith the document.", right: "I am attaching the document.", why: "'herewith' is old", hindi: "मैं दस्तावेज़ संलग्न कर रहा हूँ।" },
      { wrong: "Kindly acknowledge the receipt.", right: "Please confirm receipt.", why: "simpler", hindi: "कृपया प्राप्ति की पुष्टि करें।" },
      { wrong: "As per your request.", right: "As you requested.", why: "more direct", hindi: "जैसा आपने कहा।" },
      { wrong: "I will be there at 3 PM sharp.", right: "I will be there at 3 PM.", why: "'sharp' is unnecessary", hindi: "मैं 3 बजे पहुँचूँगा।" },
      { wrong: "Hope this email finds you well.", right: "Hope you're doing well.", why: "more natural", hindi: "आशा है आप ठीक होंगे।" },
      { wrong: "Looking forward to hear from you.", right: "Looking forward to hearing from you.", why: "'to' + -ing form", hindi: "आपके जवाब का इंतज़ार।" },
      { wrong: "Please let me know your convenient time.", right: "Please let me know a convenient time.", why: "'a' needed", hindi: "कृपया सुविधाजनक समय बताएं।" },
      { wrong: "I will revert back shortly.", right: "I will reply shortly.", why: "'revert back' redundant", hindi: "मैं जल्दी जवाब दूँगा।" },
      { wrong: "Please go through the document.", right: "Please review the document.", why: "'review' is clearer", hindi: "कृपया दस्तावेज़ देखें।" },
      { wrong: "The same has been done.", right: "It has been completed.", why: "'the same' is stiff", hindi: "यह पूरा हो गया।" },
      { wrong: "I request you to kindly approve.", right: "Could you please approve?", why: "more polite question form", hindi: "क्या आप कृपया स्वीकृत करेंगे?" },
      { wrong: "I am writing this email to tell you.", right: "I am writing to inform you.", why: "shorter and cleaner", hindi: "मैं आपको सूचित करने के लिए लिख रहा हूँ।" },
      { wrong: "Please excuse me for the delay.", right: "Apologies for the delay.", why: "more natural", hindi: "देरी के लिए माफ़ी।" },
      { wrong: "Due to some personal work.", right: "Due to a personal commitment.", why: "more professional", hindi: "व्यक्तिगत काम के कारण।" },
      { wrong: "I have some urgent work.", right: "Something urgent has come up.", why: "more natural", hindi: "कुछ ज़रूरी काम आ गया।" },
      { wrong: "Please treat this as urgent.", right: "This is time-sensitive.", why: "more professional", hindi: "यह समय-संवेदनशील है।" },
      { wrong: "I am on leave today.", right: "I am on leave today.", why: "this is correct!", hindi: "मैं आज छुट्टी पर हूँ।" },
      { wrong: "Thanks in advance.", right: "Thank you in advance.", why: "full words in formal emails", hindi: "अग्रिम धन्यवाद।" },
      { wrong: "Regards only.", right: "Best regards,", why: "full closing", hindi: "सादर।" },
      { wrong: "Your's sincerely.", right: "Yours sincerely,", why: "no apostrophe in 'yours'", hindi: "भवदीय।" },
      { wrong: "Attached herewith is the report.", right: "The report is attached.", why: "simpler structure", hindi: "रिपोर्ट संलग्न है।" },
      { wrong: "I will get back to you.", right: "I will get back to you shortly.", why: "add timing for clarity", hindi: "मैं जल्दी जवाब दूँगा।" },
      { wrong: "FYI — this is important.", right: "Please note — this is important.", why: "FYI is informal", hindi: "कृपया ध्यान दें — यह महत्वपूर्ण है।" },
      { wrong: "Please do the needful urgently.", right: "Please prioritize this.", why: "more modern", hindi: "कृपया इसे प्राथमिकता दें।" },
      { wrong: "Let me know if you have any queries.", right: "Let me know if you have any questions.", why: "'queries' is too formal", hindi: "कोई सवाल हो तो बताएं।" },
      { wrong: "We regret to inform you.", right: "We are sorry to inform you.", why: "softer tone", hindi: "हमें खेद है सूचित करना।" },
    ],
  },
  {
    id: "restaurant", emoji: "🍽️", title: "Restaurant & Ordering", desc: "Order confidently anywhere",
    items: [
      { wrong: "Give me one masala dosa.", right: "I'd like a masala dosa, please.", why: "polite request", hindi: "मुझे एक मसाला डोसा चाहिए।" },
      { wrong: "What is in this dish?", right: "What does this dish contain?", why: "more polite", hindi: "इसमें क्या है?" },
      { wrong: "Make it less spicy.", right: "Could you make it less spicy?", why: "polite question", hindi: "कम तीखा बनाएं।" },
      { wrong: "I want a table for two.", right: "A table for two, please.", why: "more natural", hindi: "दो के लिए टेबल चाहिए।" },
      { wrong: "The bill please.", right: "Could we have the bill, please?", why: "more polite", hindi: "बिल लाइए।" },
      { wrong: "Is this veg or non-veg?", right: "Is this vegetarian?", why: "clearer", hindi: "क्या यह शाकाहारी है?" },
      { wrong: "Give me water.", right: "Could I have some water, please?", why: "polite request", hindi: "कृपया पानी दीजिए।" },
      { wrong: "I will have same.", right: "I'll have the same.", why: "'the' is needed", hindi: "मुझे भी वही चाहिए।" },
      { wrong: "This is too salty.", right: "This is a bit too salty.", why: "softer complaint", hindi: "यह थोड़ा नमकीन है।" },
      { wrong: "I didn't order this.", right: "I didn't order this, I think.", why: "polite doubt", hindi: "शायद मैंने यह नहीं मंगाया।" },
      { wrong: "Give me menu.", right: "Could I see the menu, please?", why: "more polite", hindi: "कृपया मेन्यू दीजिए।" },
      { wrong: "This food is very nice.", right: "This food is delicious.", why: "'delicious' is more precise", hindi: "खाना स्वादिष्ट है।" },
      { wrong: "I am full.", right: "I'm full, thank you.", why: "add thanks for politeness", hindi: "मैं भर गया, धन्यवाद।" },
      { wrong: "How much time for food?", right: "How long will the food take?", why: "more natural", hindi: "खाने में कितना समय लगेगा?" },
      { wrong: "Do you have paneer?", right: "Do you serve paneer?", why: "'serve' for restaurants", hindi: "क्या आपके यहाँ पनीर मिलता है?" },
      { wrong: "Please make it quick.", right: "Could you hurry it up a bit?", why: "less rude", hindi: "थोड़ा जल्दी कीजिए।" },
      { wrong: "I want to book a table.", right: "I'd like to book a table.", why: "'would like' is politer", hindi: "मैं टेबल बुक करना चाहता हूँ।" },
      { wrong: "Bring the bill.", right: "Could we get the bill, please?", why: "polite question", hindi: "बिल लाइए।" },
      { wrong: "Is service charge included?", right: "Is service charge included?", why: "this is correct!", hindi: "क्या सर्विस चार्ज शामिल है?" },
      { wrong: "We want to pay by card.", right: "Can we pay by card?", why: "question form", hindi: "क्या हम कार्ड से भुगतान कर सकते हैं?" },
      { wrong: "Give me a takeaway.", right: "I'd like this to take away.", why: "more natural", hindi: "मुझे पैक कराकर चाहिए।" },
      { wrong: "One more spoon.", right: "Could I have another spoon, please?", why: "polite request", hindi: "एक और चम्मच दीजिए।" },
      { wrong: "The tea is cold.", right: "The tea is a bit cold, could I get a fresh cup?", why: "polite complaint", hindi: "चाय ठंडी है।" },
      { wrong: "This is not what I ordered.", right: "I think this isn't what I ordered.", why: "softer", hindi: "शायद यह वह नहीं जो मैंने मंगाया।" },
      { wrong: "I don't eat onion.", right: "I don't eat onions.", why: "plural", hindi: "मैं प्याज़ नहीं खाता।" },
      { wrong: "No sugar in my tea.", right: "No sugar in my tea, please.", why: "add 'please'", hindi: "चाय में चीनी मत डालिए।" },
      { wrong: "The food is tasty.", right: "The food is really good.", why: "'tasty' is less common", hindi: "खाना बहुत अच्छा है।" },
      { wrong: "Do you have free wifi?", right: "Do you have free wifi?", why: "this is correct!", hindi: "क्या आपके पास मुफ्त वाईफाई है?" },
      { wrong: "I am allergic to nuts.", right: "I am allergic to nuts.", why: "this is correct!", hindi: "मुझे मेवों से एलर्जी है।" },
      { wrong: "We are in a hurry.", right: "We're in a bit of a hurry.", why: "softer", hindi: "हमें थोड़ी जल्दी है।" },
    ],
  },
];