import { Pack } from "./dataA";

export const PACKS_C: Pack[] = [
  {
    id: "plans", emoji: "📅", title: "Making Plans", desc: "Fix meetups without confusion",
    items: [
      { wrong: "Let's go for a movie tomorrow.", right: "Let's go to a movie tomorrow.", why: "go TO a movie, not for", hindi: "कल फ़िल्म चलते हैं।" },
      { wrong: "We will meet at Sunday.", right: "We will meet on Sunday.", why: "ON for days", hindi: "रविवार को मिलते हैं।" },
      { wrong: "I am free at evening.", right: "I am free in the evening.", why: "IN the evening", hindi: "शाम को मैं फ्री हूँ।" },
      { wrong: "What time we will meet?", right: "What time shall we meet?", why: "question form", hindi: "कितने बजे मिलें?" },
      { wrong: "Let's prepone the meeting.", right: "Let's move the meeting earlier.", why: "'prepone' isn't standard English", hindi: "मीटिंग जल्दी करते हैं।" },
      { wrong: "I will confirm you tomorrow.", right: "I will confirm with you tomorrow.", why: "confirm WITH", hindi: "कल पक्का बताऊँगा।" },
      { wrong: "Are you coming or not?", right: "Will you be able to make it?", why: "politer", hindi: "क्या आप आ पाएँगे?" },
      { wrong: "I will drop the plan.", right: "I will cancel the plan.", why: "'drop' is unnatural", hindi: "मैं योजना रद्द करूँगा।" },
      { wrong: "Let's do the programme.", right: "Let's make a plan.", why: "'programme' is unnatural", hindi: "योजना बनाते हैं।" },
      { wrong: "I am having a programme tonight.", right: "I have plans tonight.", why: "'plans' not programme", hindi: "आज रात मेरा प्रोग्राम है।" },
      { wrong: "Where we will go?", right: "Where shall we go?", why: "question form", hindi: "हम कहाँ जाएँगे?" },
      { wrong: "I will pick you at 6.", right: "I will pick you up at 6.", why: "pick UP", hindi: "मैं 6 बजे लेने आऊँगा।" },
      { wrong: "Let's start at 9 sharp time.", right: "Let's start at 9 sharp.", why: "'sharp time' is redundant", hindi: "ठीक 9 बजे शुरू करते हैं।" },
      { wrong: "I will be late by 10 minutes.", right: "I'll be 10 minutes late.", why: "more natural", hindi: "मैं 10 मिनट देर से आऊँगा।" },
      { wrong: "Can we reschedule to next week?", right: "Can we move it to next week?", why: "more natural", hindi: "क्या अगले हफ्ते कर सकते हैं?" },
      { wrong: "I will not be available on that time.", right: "I won't be available at that time.", why: "AT that time", hindi: "उस समय मैं नहीं आ पाऊँगा।" },
      { wrong: "Let's fix the day.", right: "Let's decide on a day.", why: "'fix the day' is unnatural", hindi: "दिन पक्का करते हैं।" },
      { wrong: "I will come to your place.", right: "I'll come over to your place.", why: "come over", hindi: "मैं तुम्हारे घर आऊँगा।" },
      { wrong: "Shall we go by walk?", right: "Shall we walk?", why: "'by walk' is wrong", hindi: "क्या पैदल चलें?" },
      { wrong: "We will go in car.", right: "We'll go by car.", why: "BY car", hindi: "हम कार से जाएँगे।" },
      { wrong: "Let's meet at my home.", right: "Let's meet at my place.", why: "'place' is more natural", hindi: "मेरे घर मिलते हैं।" },
      { wrong: "I will give you a surprise.", right: "I've got a surprise for you.", why: "more natural", hindi: "मेरे पास तुम्हारे लिए सरप्राइज़ है।" },
      { wrong: "What is the programme for today?", right: "What's the plan for today?", why: "'plan' is natural", hindi: "आज का क्या प्रोग्राम है?" },
      { wrong: "I am doing a plan to go out.", right: "I'm planning to go out.", why: "'doing a plan' is wrong", hindi: "मैं बाहर जाने की योजना बना रहा हूँ।" },
      { wrong: "Let's cancel it.", right: "Let's call it off.", why: "phrasal is more natural", hindi: "इसे रद्द करते हैं।" },
      { wrong: "I will join you later.", right: "I'll catch up with you later.", why: "more natural", hindi: "मैं बाद में तुमसे मिलूँगा।" },
      { wrong: "Are you free on tomorrow?", right: "Are you free tomorrow?", why: "no preposition before tomorrow", hindi: "कल फ्री हो?" },
      { wrong: "Let's meet in the weekend.", right: "Let's meet on the weekend.", why: "ON the weekend", hindi: "वीकेंड पर मिलते हैं।" },
      { wrong: "I will inform you the time.", right: "I'll let you know the time.", why: "let know", hindi: "मैं समय बता दूँगा।" },
      { wrong: "We will have a party at my house.", right: "We're having a party at my place.", why: "more natural", hindi: "मेरे घर पार्टी होगी।" },
    ],
  },
  {
    id: "opinions", emoji: "💬", title: "Opinions & Agreement", desc: "Share views politely",
    items: [
      { wrong: "I am agreeing with you.", right: "I agree with you.", why: "'agree' is stative", hindi: "मैं आपसे सहमत हूँ।" },
      { wrong: "What is your opinion about this?", right: "What do you think about this?", why: "more natural", hindi: "आपकी राय क्या है?" },
      { wrong: "I am also thinking same.", right: "I feel the same way.", why: "more natural", hindi: "मेरा भी यही सोचना है।" },
      { wrong: "You are 100% correct.", right: "You're absolutely right.", why: "'right' is natural", hindi: "आप बिल्कुल सही हैं।" },
      { wrong: "I am not agreeing.", right: "I don't agree.", why: "'agree' is stative", hindi: "मैं सहमत नहीं हूँ।" },
      { wrong: "In my opinion, I think...", right: "In my opinion, ...", why: "redundant", hindi: "मेरी राय में..." },
      { wrong: "According to me, we should go.", right: "I think we should go.", why: "'according to me' is unnatural", hindi: "मुझे लगता है हमें जाना चाहिए।" },
      { wrong: "I am doubtful about this.", right: "I have doubts about this.", why: "more natural", hindi: "मुझे इस पर संदेह है।" },
      { wrong: "I am sure 100%.", right: "I'm absolutely sure.", why: "more natural", hindi: "मुझे पूरा भरोसा है।" },
      { wrong: "You are telling truth.", right: "You're telling the truth.", why: "'the' is needed", hindi: "आप सच कह रहे हैं।" },
      { wrong: "I feel it is not correct.", right: "I don't think that's right.", why: "more natural", hindi: "मुझे लगता है यह सही नहीं है।" },
      { wrong: "No, I am not agreeing at all.", right: "I completely disagree.", why: "cleaner", hindi: "मैं बिल्कुल असहमत हूँ।" },
      { wrong: "Your point is very much correct.", right: "You make a good point.", why: "more natural", hindi: "आपकी बात सही है।" },
      { wrong: "I am of the opinion that...", right: "I believe that...", why: "simpler", hindi: "मेरा मानना है कि..." },
      { wrong: "Let me give my suggestion.", right: "Let me make a suggestion.", why: "make a suggestion", hindi: "मैं एक सुझाव दूँ।" },
      { wrong: "I am suggesting you to try.", right: "I suggest you try.", why: "suggest + that", hindi: "मैं सुझाव दूँगा कि आप कोशिश करें।" },
      { wrong: "I am not knowing about that.", right: "I don't know about that.", why: "'know' is stative", hindi: "मुझे उसके बारे में नहीं पता।" },
      { wrong: "Both are correct only.", right: "Both are correct.", why: "drop 'only'", hindi: "दोनों सही हैं।" },
      { wrong: "I am having a different view.", right: "I see it differently.", why: "more natural", hindi: "मेरा नज़रिया अलग है।" },
      { wrong: "You are telling a lie.", right: "That's not true.", why: "softer", hindi: "यह सच नहीं है।" },
      { wrong: "I am having full confidence.", right: "I'm fully confident.", why: "more natural", hindi: "मुझे पूरा भरोसा है।" },
      { wrong: "That idea is not good.", right: "That idea doesn't sound right to me.", why: "softer", hindi: "वह विचार ठीक नहीं लगता।" },
      { wrong: "I am totally against it.", right: "I'm completely against it.", why: "completely", hindi: "मैं इसके पूरी तरह खिलाफ़ हूँ।" },
      { wrong: "I am supporting this idea.", right: "I support this idea.", why: "simple present", hindi: "मैं इस विचार का समर्थन करता हूँ।" },
      { wrong: "Let's discuss about it.", right: "Let's discuss it.", why: "no 'about'", hindi: "आइए इस पर चर्चा करें।" },
      { wrong: "I am thinking you are right.", right: "I think you're right.", why: "'think' is stative", hindi: "मुझे लगता है आप सही हैं।" },
      { wrong: "My view is different than yours.", right: "My view is different from yours.", why: "different FROM", hindi: "मेरी राय आपसे अलग है।" },
      { wrong: "I am not satisfying with this.", right: "I'm not satisfied with this.", why: "'satisfied'", hindi: "मैं इससे संतुष्ट नहीं हूँ।" },
      { wrong: "You have said it correctly.", right: "You said it perfectly.", why: "more natural", hindi: "आपने ठीक कहा।" },
      { wrong: "I am neutral in this matter.", right: "I'm neutral on this.", why: "ON this", hindi: "मैं इस मामले में तटस्थ हूँ।" },
    ],
  },
  {
    id: "work", emoji: "💼", title: "Workplace Talk", desc: "Sound professional at work",
    items: [
      { wrong: "I am doing my duty.", right: "I'm doing my job.", why: "'job' is natural", hindi: "मैं अपना काम कर रहा हूँ।" },
      { wrong: "He is my senior.", right: "He is senior to me.", why: "senior TO", hindi: "वह मुझसे सीनियर हैं।" },
      { wrong: "I am doing overtime today.", right: "I'm working overtime today.", why: "work overtime", hindi: "आज ओवरटाइम कर रहा हूँ।" },
      { wrong: "My boss scolded me.", right: "My boss gave me feedback.", why: "more professional", hindi: "बॉस ने डाँटा।" },
      { wrong: "I am submitting the report today.", right: "I'll submit the report today.", why: "simple future", hindi: "आज रिपोर्ट जमा करूँगा।" },
      { wrong: "Please do the needful.", right: "Please take the necessary action.", why: "old-fashioned", hindi: "कृपया आवश्यक कार्रवाई करें।" },
      { wrong: "I am having a meeting at 3.", right: "I have a meeting at 3.", why: "'have'", hindi: "3 बजे मीटिंग है।" },
      { wrong: "He is gone on leave.", right: "He is on leave.", why: "simpler", hindi: "वह छुट्टी पर हैं।" },
      { wrong: "I will revert back by evening.", right: "I'll get back to you by evening.", why: "get back", hindi: "शाम तक जवाब दूँगा।" },
      { wrong: "My colleague is transfered.", right: "My colleague was transferred.", why: "passive + spelling", hindi: "मेरा सहकर्मी ट्रांसफर हो गया।" },
      { wrong: "I am working here since 2 years.", right: "I have been working here for 2 years.", why: "present perfect + for", hindi: "मैं 2 साल से यहाँ काम कर रहा हूँ।" },
      { wrong: "Please give me a leave tomorrow.", right: "Could I take a day off tomorrow?", why: "take a day off", hindi: "कल छुट्टी चाहिए।" },
      { wrong: "I am attending the call.", right: "I'm joining the call.", why: "'join'", hindi: "मैं कॉल में जुड़ रहा हूँ।" },
      { wrong: "Send me the details on mail.", right: "Email me the details.", why: "by email", hindi: "मुझे विवरण ईमेल करें।" },
      { wrong: "I am not getting your mail.", right: "I'm not receiving your emails.", why: "'receive'", hindi: "मुझे आपका ईमेल नहीं मिल रहा।" },
      { wrong: "Please cc me in the mail.", right: "Please cc me on the email.", why: "ON the email", hindi: "मुझे सीसी में रखिए।" },
      { wrong: "I will do the follow-up.", right: "I'll follow up on this.", why: "verb form", hindi: "मैं फॉलो-अप करूँगा।" },
      { wrong: "My work is completed.", right: "I've finished my work.", why: "more natural", hindi: "मेरा काम पूरा हो गया।" },
      { wrong: "I am giving resignation.", right: "I'm handing in my resignation.", why: "handing in", hindi: "मैं इस्तीफा दे रहा हूँ।" },
      { wrong: "He got promotion.", right: "He got a promotion.", why: "'a' is needed", hindi: "उसे प्रमोशन मिला।" },
      { wrong: "I am doing the needful.", right: "I'm taking care of it.", why: "natural", hindi: "मैं देख रहा हूँ।" },
      { wrong: "Please inform the team.", right: "Please let the team know.", why: "let know", hindi: "टीम को बता दीजिए।" },
      { wrong: "I am doing work from home.", right: "I'm working from home.", why: "simpler", hindi: "आज घर से काम कर रहा हूँ।" },
      { wrong: "My laptop is giving problem.", right: "My laptop is having issues.", why: "natural", hindi: "लैपटॉप में समस्या है।" },
      { wrong: "I am facing problem with login.", right: "I'm having trouble logging in.", why: "natural", hindi: "लॉगिन में समस्या हो रही है।" },
      { wrong: "Please share the update.", right: "Could you share an update?", why: "polite", hindi: "कृपया अपडेट साझा करें।" },
      { wrong: "I am waiting for your reply.", right: "I look forward to your reply.", why: "professional", hindi: "आपके जवाब का इंतज़ार है।" },
      { wrong: "He is not coming to office.", right: "He isn't coming into the office.", why: "into the office", hindi: "वह ऑफिस नहीं आ रहे।" },
      { wrong: "I am taking half day today.", right: "I'm taking a half day today.", why: "'a half day'", hindi: "आज आधा दिन छुट्टी है।" },
      { wrong: "Please approve my leave.", right: "Could you approve my leave request?", why: "polite", hindi: "कृपया छुट्टी स्वीकृत करें।" },
    ],
  },
  {
    id: "family", emoji: "🏠", title: "Family Conversations", desc: "Talk about your people naturally",
    items: [
      { wrong: "What is mummy doing?", right: "What is Mom doing?", why: "'Mom' is natural in English", hindi: "मम्मी क्या कर रही हैं?" },
      { wrong: "I am going to my native place.", right: "I'm going to my hometown.", why: "'hometown'", hindi: "मैं अपने गाँव जा रहा हूँ।" },
      { wrong: "My brother is elder to me.", right: "My brother is older than me.", why: "older THAN", hindi: "मेरा भाई मुझसे बड़ा है।" },
      { wrong: "I am living at my parents house.", right: "I live with my parents.", why: "WITH", hindi: "मैं माता-पिता के साथ रहता हूँ।" },
      { wrong: "My sister is married last year.", right: "My sister got married last year.", why: "got married + past", hindi: "मेरी बहन की शादी पिछले साल हुई।" },
      { wrong: "We are four members in family.", right: "There are four of us in the family.", why: "natural", hindi: "हम परिवार में चार लोग हैं।" },
      { wrong: "My father is doing job.", right: "My father works.", why: "'works'", hindi: "मेरे पिता नौकरी करते हैं।" },
      { wrong: "I am eldest.", right: "I'm the eldest.", why: "'the' is needed", hindi: "मैं सबसे बड़ा हूँ।" },
      { wrong: "My cousin brother is coming.", right: "My cousin is coming.", why: "drop 'brother'", hindi: "मेरा चचेरा भाई आ रहा है।" },
      { wrong: "We will go to aunty's house.", right: "We're going to my aunt's house.", why: "aunt's", hindi: "हम चाची के घर जाएँगे।" },
      { wrong: "My mother is cooking the food.", right: "My mother is cooking.", why: "drop 'food'", hindi: "मम्मी खाना बना रही हैं।" },
      { wrong: "I am helping my father in his work.", right: "I'm helping my father with his work.", why: "WITH", hindi: "मैं पिता की मदद कर रहा हूँ।" },
      { wrong: "My grandparents are living in village.", right: "My grandparents live in a village.", why: "'a village'", hindi: "मेरे दादा-दादी गाँव में रहते हैं।" },
      { wrong: "I am missing my home.", right: "I miss home.", why: "'miss' is stative", hindi: "मुझे घर की याद आ रही है।" },
      { wrong: "My wife is doing teaching.", right: "My wife is a teacher.", why: "profession", hindi: "मेरी पत्नी शिक्षिका हैं।" },
      { wrong: "My husband is working in bank.", right: "My husband works at a bank.", why: "AT a bank", hindi: "मेरे पति बैंक में काम करते हैं।" },
      { wrong: "We are doing Diwali at home.", right: "We're celebrating Diwali at home.", why: "'celebrate'", hindi: "हम दिवाली घर पर मना रहे हैं।" },
      { wrong: "My son is studying in 5th class.", right: "My son is in the 5th grade.", why: "'grade'", hindi: "मेरा बेटा 5वीं कक्षा में है।" },
      { wrong: "My daughter is getting good marks.", right: "My daughter is getting good grades.", why: "'grades'", hindi: "मेरी बेटी अच्छे अंक ला रही है।" },
      { wrong: "I am caring my parents.", right: "I'm taking care of my parents.", why: "take care OF", hindi: "मैं माता-पिता की देखभाल कर रहा हूँ।" },
      { wrong: "My family members are supporting me.", right: "My family supports me.", why: "simpler", hindi: "मेरा परिवार मेरा समर्थन करता है।" },
      { wrong: "We are having a joint family.", right: "We live in a joint family.", why: "live in", hindi: "हम संयुक्त परिवार में रहते हैं।" },
      { wrong: "My uncle gave me a gift of watch.", right: "My uncle gave me a watch as a gift.", why: "natural", hindi: "चाचा ने मुझे घड़ी दी।" },
      { wrong: "I am respecting my elders.", right: "I respect my elders.", why: "'respect' is stative", hindi: "मैं बड़ों का सम्मान करता हूँ।" },
      { wrong: "My mother in law is very kind.", right: "My mother-in-law is very kind.", why: "hyphens", hindi: "मेरी सास बहुत दयालु हैं।" },
      { wrong: "We are going to my in-laws house.", right: "We're going to my in-laws' house.", why: "apostrophe", hindi: "हम ससुराल जा रहे हैं।" },
      { wrong: "My brother is giving exams.", right: "My brother is taking exams.", why: "take exams", hindi: "मेरा भाई परीक्षा दे रहा है।" },
      { wrong: "I am in middle of my siblings.", right: "I'm the middle child.", why: "natural", hindi: "मैं बीच वाला बच्चा हूँ।" },
      { wrong: "My family is feeling proud of me.", right: "My family is proud of me.", why: "drop 'feeling'", hindi: "मेरा परिवार मुझ पर गर्व करता है।" },
      { wrong: "We are loving each other.", right: "We love each other.", why: "'love' is stative", hindi: "हम एक-दूसरे से प्यार करते हैं।" },
    ],
  },
  {
    id: "celebrations", emoji: "🎉", title: "Celebrations & Wishes", desc: "Wish & celebrate in English",
    items: [
      { wrong: "Advance happy birthday!", right: "Happy birthday in advance!", why: "word order", hindi: "जन्मदिन की बधाई!" },
      { wrong: "Many many happy returns of the day.", right: "Many happy returns of the day!", why: "drop one 'many'", hindi: "जन्मदिन मुबारक!" },
      { wrong: "I am wishing you happy Diwali.", right: "I wish you a happy Diwali!", why: "wish + a", hindi: "दिवाली की शुभकामनाएँ!" },
      { wrong: "Congratulate you!", right: "Congratulations!", why: "noun form", hindi: "बधाई हो!" },
      { wrong: "I am congratulating you for your success.", right: "Congratulations on your success!", why: "ON success", hindi: "आपकी सफलता पर बधाई!" },
      { wrong: "I am wishing you all the best for new job.", right: "I wish you all the best in your new job.", why: "IN your job", hindi: "नई नौकरी के लिए शुभकामनाएँ!" },
      { wrong: "Happy married life!", right: "Wishing you a happy married life!", why: "complete", hindi: "वैवाहिक जीवन की बधाई!" },
      { wrong: "I am giving you a gift.", right: "Here's a little gift for you.", why: "natural", hindi: "यह तुम्हारे लिए उपहार है।" },
      { wrong: "Please come to my birthday function.", right: "Please come to my birthday party.", why: "'party'", hindi: "मेरे जन्मदिन की पार्टी में आइए।" },
      { wrong: "We are giving a party for my promotion.", right: "We're throwing a party for my promotion.", why: "throw a party", hindi: "हम प्रमोशन की पार्टी कर रहे हैं।" },
      { wrong: "I am inviting you for my wedding.", right: "I'd like to invite you to my wedding.", why: "invite TO", hindi: "मैं आपको शादी में आमंत्रित करता हूँ।" },
      { wrong: "I am blessing you both.", right: "I wish you both a lifetime of happiness.", why: "natural", hindi: "तुम दोनों को आशीर्वाद!" },
      { wrong: "Marriage anniversary wishes!", right: "Happy anniversary!", why: "simpler", hindi: "शादी की सालगिरह मुबारक!" },
      { wrong: "We will cut cake at 8.", right: "We'll cut the cake at 8.", why: "'the' is needed", hindi: "8 बजे केक काटेंगे।" },
      { wrong: "Don't come empty hand.", right: "Please don't come empty-handed.", why: "empty-handed", hindi: "खाली हाथ मत आइए।" },
      { wrong: "I am giving a party at my home.", right: "I'm hosting a party at my place.", why: "'host'", hindi: "मैं अपने घर पार्टी कर रहा हूँ।" },
      { wrong: "Wish you a safe journey.", right: "Have a safe journey!", why: "'have'", hindi: "यात्रा शुभ हो!" },
      { wrong: "I am wishing you good luck for exam.", right: "Good luck with your exam!", why: "WITH", hindi: "परीक्षा के लिए शुभकामनाएँ!" },
      { wrong: "I am wishing you bright future.", right: "I wish you a bright future.", why: "'a bright'", hindi: "उज्ज्वल भविष्य की शुभकामनाएँ!" },
      { wrong: "Congratulations for your wedding.", right: "Congratulations on your wedding!", why: "ON", hindi: "शादी की बधाई!" },
      { wrong: "I am celebrating for my success.", right: "I'm celebrating my success.", why: "no 'for'", hindi: "मैं अपनी सफलता मना रहा हूँ।" },
      { wrong: "Please join us in dinner.", right: "Please join us for dinner.", why: "FOR", hindi: "हमारे साथ रात्रिभोज में शामिल हों।" },
      { wrong: "We are organizing a get together function.", right: "We're having a get-together.", why: "simpler", hindi: "हम गेट-टुगेदर कर रहे हैं।" },
      { wrong: "I will send you wishes card.", right: "I'll send you a greeting card.", why: "'a card'", hindi: "मैं आपको कार्ड भेजूँगा।" },
      { wrong: "Bless you for the new year.", right: "Best wishes for the new year!", why: "natural", hindi: "नए साल की शुभकामनाएँ!" },
      { wrong: "Happy new year in advance.", right: "Wishing you a happy new year!", why: "complete", hindi: "नव वर्ष की बधाई!" },
      { wrong: "I am enjoying the festival very much.", right: "I'm really enjoying the festival.", why: "natural", hindi: "त्योहार बहुत अच्छा लग रहा है।" },
      { wrong: "Please grace the occasion.", right: "We'd be honored by your presence.", why: "modern", hindi: "कृपया पधारें।" },
      { wrong: "I am thanking you all.", right: "Thank you all!", why: "simpler", hindi: "आप सभी का धन्यवाद!" },
      { wrong: "Thank you for coming to my function.", right: "Thank you for coming!", why: "drop 'function'", hindi: "आने के लिए धन्यवाद!" },
    ],
  },
];