import { Pack } from "./dataA";

export const PACKS_D: Pack[] = [
  {
    id: "emergency", emoji: "🆘", title: "Emergency & Help", desc: "Stay clear in a crisis",
    items: [
      { wrong: "Help me please!", right: "Please help me!", why: "word order", hindi: "कृपया मदद करें!" },
      { wrong: "Call to police!", right: "Call the police!", why: "no 'to'", hindi: "पुलिस को बुलाओ!" },
      { wrong: "I am needing help.", right: "I need help.", why: "'need' is stative", hindi: "मुझे मदद चाहिए।" },
      { wrong: "There is accident happened.", right: "There has been an accident.", why: "correct form", hindi: "एक दुर्घटना हुई है।" },
      { wrong: "Please hurry up, it's emergency.", right: "Please hurry, it's an emergency.", why: "'an' is needed", hindi: "जल्दी कीजिए, आपातकाल है।" },
      { wrong: "I am lost my phone.", right: "I have lost my phone.", why: "present perfect", hindi: "मेरा फोन खो गया है।" },
      { wrong: "My bag is stolen.", right: "My bag was stolen.", why: "passive past", hindi: "मेरा बैग चोरी हो गया।" },
      { wrong: "Please do first aid to him.", right: "Please give him first aid.", why: "give first aid", hindi: "उसे प्राथमिक उपचार दीजिए।" },
      { wrong: "Take him to hospital.", right: "Take him to the hospital.", why: "'the' is needed", hindi: "उसे अस्पताल ले जाइए।" },
      { wrong: "I am feeling unsafe.", right: "I don't feel safe.", why: "more natural", hindi: "मुझे सुरक्षित महसूस नहीं हो रहा।" },
      { wrong: "Somebody please come and help.", right: "Can someone please help?", why: "question form", hindi: "क्या कोई मदद कर सकता है?" },
      { wrong: "The fire is started.", right: "A fire has started.", why: "correct form", hindi: "आग लग गई है।" },
      { wrong: "Please inform to my family.", right: "Please inform my family.", why: "no 'to'", hindi: "कृपया मेरे परिवार को सूचित करें।" },
      { wrong: "I am stuck in lift.", right: "I'm stuck in the lift.", why: "'the' is needed", hindi: "मैं लिफ्ट में फँस गया हूँ।" },
      { wrong: "My child is missing.", right: "My child is missing.", why: "this is correct!", hindi: "मेरा बच्चा गुम है।" },
      { wrong: "Please give me your phone, I will call.", right: "Could I borrow your phone, please?", why: "polite", hindi: "क्या आपका फोन ले सकता हूँ?" },
      { wrong: "I am injured.", right: "I'm hurt.", why: "more natural", hindi: "मुझे चोट लगी है।" },
      { wrong: "There is too much bleeding.", right: "He's bleeding a lot.", why: "more natural", hindi: "बहुत खून बह रहा है।" },
      { wrong: "Please stop the car.", right: "Please stop the car.", why: "this is correct!", hindi: "कृपया गाड़ी रोकीए।" },
      { wrong: "I am not able to breathe.", right: "I can't breathe.", why: "simpler", hindi: "मुझे सांस नहीं आ रही।" },
      { wrong: "Call ambulance quickly.", right: "Call an ambulance, quickly!", why: "'an' is needed", hindi: "एम्बुलेंस बुलाइए, जल्दी!" },
      { wrong: "He is fainted.", right: "He has fainted.", why: "present perfect", hindi: "वह बेहोश हो गया।" },
      { wrong: "Please don't panic.", right: "Please don't panic.", why: "this is correct!", hindi: "कृपया घबराइए मत।" },
      { wrong: "I am searching for my child.", right: "I'm looking for my child.", why: "look for", hindi: "मैं अपने बच्चे को ढूँढ रहा हूँ।" },
      { wrong: "The road is blocked.", right: "The road is blocked.", why: "this is correct!", hindi: "रास्ता बंद है।" },
      { wrong: "Please move aside.", right: "Please step aside.", why: "more natural", hindi: "कृपया हटिए।" },
      { wrong: "I am calling from accident spot.", right: "I'm calling from the accident site.", why: "'site'", hindi: "मैं दुर्घटना स्थल से बोल रहा हूँ।" },
      { wrong: "Water is entering in my house.", right: "Water is entering my house.", why: "no 'in'", hindi: "मेरे घर में पानी घुस रहा है।" },
      { wrong: "Please save me.", right: "Please help me!", why: "more natural", hindi: "कृपया मेरी मदद कीजिए!" },
      { wrong: "I am in danger.", right: "I'm in danger.", why: "this is correct!", hindi: "मैं खतरे में हूँ।" },
    ],
  },
  {
    id: "tech", emoji: "💻", title: "Tech Help", desc: "Explain tech problems clearly",
    items: [
      { wrong: "My phone is not switching on.", right: "My phone won't turn on.", why: "turn on", hindi: "मेरा फोन चालू नहीं हो रहा।" },
      { wrong: "Internet is not coming.", right: "The internet isn't working.", why: "'working'", hindi: "इंटरनेट नहीं चल रहा।" },
      { wrong: "My laptop is hanging.", right: "My laptop is freezing.", why: "'freezing'", hindi: "लैपटॉप अटक रहा है।" },
      { wrong: "Please restart the computer.", right: "Please restart the computer.", why: "this is correct!", hindi: "कृपया कंप्यूटर रीस्टार्ट करें।" },
      { wrong: "I forgot my password.", right: "I forgot my password.", why: "this is correct!", hindi: "मेरा पासवर्ड भूल गया।" },
      { wrong: "My screen is not working.", right: "My screen isn't working.", why: "this is correct!", hindi: "स्क्रीन काम नहीं कर रही।" },
      { wrong: "The app is crashing.", right: "The app keeps crashing.", why: "'keeps'", hindi: "ऐप क्रैश हो रहा है।" },
      { wrong: "I am not getting signal.", right: "I'm not getting a signal.", why: "'a' is needed", hindi: "सिग्नल नहीं मिल रहा।" },
      { wrong: "My battery is draining fast.", right: "My battery is draining fast.", why: "this is correct!", hindi: "बैटरी जल्दी खत्म हो रही है।" },
      { wrong: "Please update your software.", right: "Please update your software.", why: "this is correct!", hindi: "कृपया सॉफ्टवेयर अपडेट करें।" },
      { wrong: "The file is not opening.", right: "The file won't open.", why: "won't open", hindi: "फ़ाइल नहीं खुल रही।" },
      { wrong: "I deleted it by mistake.", right: "I deleted it by mistake.", why: "this is correct!", hindi: "गलती से डिलीट हो गया।" },
      { wrong: "My computer is very slow.", right: "My computer is really slow.", why: "'really'", hindi: "कंप्यूटर बहुत धीमा है।" },
      { wrong: "The printer is not taking print.", right: "The printer isn't printing.", why: "'printing'", hindi: "प्रिंटर प्रिंट नहीं कर रहा।" },
      { wrong: "Please connect to wifi.", right: "Please connect to the wifi.", why: "'the' is needed", hindi: "कृपया वाईफाई से जुड़िए।" },
      { wrong: "My phone is heating.", right: "My phone is getting hot.", why: "getting hot", hindi: "फोन गर्म हो रहा है।" },
      { wrong: "The video is buffering.", right: "The video is buffering.", why: "this is correct!", hindi: "वीडियो बफर हो रहा है।" },
      { wrong: "I am unable to login.", right: "I can't log in.", why: "'log in' is two words", hindi: "लॉगिन नहीं हो रहा।" },
      { wrong: "My account is locked.", right: "My account is locked.", why: "this is correct!", hindi: "मेरा अकाउंट लॉक है।" },
      { wrong: "The link is not working.", right: "The link isn't working.", why: "this is correct!", hindi: "लिंक काम नहीं कर रहा।" },
      { wrong: "Please scan the QR code.", right: "Please scan the QR code.", why: "this is correct!", hindi: "कृपया QR कोड स्कैन करें।" },
      { wrong: "My storage is full.", right: "My storage is full.", why: "this is correct!", hindi: "स्टोरेज भर गया है।" },
      { wrong: "The call is not connecting.", right: "The call won't connect.", why: "won't connect", hindi: "कॉल नहीं लग रही।" },
      { wrong: "I am not hearing you properly.", right: "I can't hear you properly.", why: "can't hear", hindi: "आप ठीक से सुनाई नहीं दे रहे।" },
      { wrong: "My mic is not working.", right: "My mic isn't working.", why: "this is correct!", hindi: "माइक काम नहीं कर रहा।" },
      { wrong: "Please share the location.", right: "Please share your location.", why: "'your'", hindi: "कृपया लोकेशन भेजिए।" },
      { wrong: "The OTP is not coming.", right: "The OTP isn't arriving.", why: "'arriving'", hindi: "OTP नहीं आ रहा।" },
      { wrong: "My phone is switched off automatically.", right: "My phone keeps switching off by itself.", why: "'keeps'", hindi: "फोन अपने आप बंद हो रहा है।" },
      { wrong: "I am getting error message.", right: "I'm getting an error message.", why: "'an' is needed", hindi: "एरर मैसेज आ रहा है।" },
      { wrong: "Please charge your phone.", right: "Please charge your phone.", why: "this is correct!", hindi: "कृपया फोन चार्ज कीजिए।" },
    ],
  },
  {
    id: "study", emoji: "📚", title: "Study & Exams", desc: "Talk about school confidently",
    items: [
      { wrong: "I am preparing for exam.", right: "I'm preparing for the exam.", why: "'the' is needed", hindi: "मैं परीक्षा की तैयारी कर रहा हूँ।" },
      { wrong: "I am giving exam tomorrow.", right: "I'm taking an exam tomorrow.", why: "take an exam", hindi: "कल मेरी परीक्षा है।" },
      { wrong: "I failed in English.", right: "I failed English.", why: "no 'in'", hindi: "मैं अंग्रेज़ी में फेल हुआ।" },
      { wrong: "I am passed.", right: "I passed.", why: "active voice", hindi: "मैं पास हो गया।" },
      { wrong: "I am getting first rank.", right: "I got the first rank.", why: "past tense", hindi: "मुझे पहला स्थान मिला।" },
      { wrong: "I am studying in 10th class.", right: "I'm in the 10th grade.", why: "'grade'", hindi: "मैं 10वीं कक्षा में हूँ।" },
      { wrong: "I am not understanding math.", right: "I don't understand math.", why: "'understand' is stative", hindi: "मुझे गणित समझ नहीं आता।" },
      { wrong: "Please explain me this topic.", right: "Please explain this topic to me.", why: "explain TO", hindi: "कृपया यह विषय समझाइए।" },
      { wrong: "I am memorizing the answers.", right: "I'm memorizing the answers.", why: "this is correct!", hindi: "मैं उत्तर रट रहा हूँ।" },
      { wrong: "I am getting good percentage.", right: "I got a good percentage.", why: "past + 'a'", hindi: "मुझे अच्छे अंक मिले।" },
      { wrong: "I am weak in science.", right: "I'm weak in science.", why: "this is correct!", hindi: "मैं विज्ञान में कमज़ोर हूँ।" },
      { wrong: "I am strong in maths.", right: "I'm good at math.", why: "good AT", hindi: "मैं गणित में अच्छा हूँ।" },
      { wrong: "I am revising my lessons.", right: "I'm reviewing my lessons.", why: "'reviewing'", hindi: "मैं अपने पाठ दोहरा रहा हूँ।" },
      { wrong: "I am solving the paper.", right: "I'm working on the paper.", why: "working on", hindi: "मैं पेपर हल कर रहा हूँ।" },
      { wrong: "I am writing exam now.", right: "I'm taking the exam now.", why: "'take'", hindi: "मैं अभी परीक्षा दे रहा हूँ।" },
      { wrong: "I am getting scholarship.", right: "I got a scholarship.", why: "past + 'a'", hindi: "मुझे छात्रवृत्ति मिली।" },
      { wrong: "I am attending tuition classes.", right: "I go to tutoring classes.", why: "'tutoring'", hindi: "मैं ट्यूशन जाता हूँ।" },
      { wrong: "I am completing my homework.", right: "I'm finishing my homework.", why: "'finishing'", hindi: "मैं होमवर्क पूरा कर रहा हूँ।" },
      { wrong: "I am learning English since 2 years.", right: "I have been learning English for 2 years.", why: "present perfect + for", hindi: "मैं 2 साल से अंग्रेज़ी सीख रहा हूँ।" },
      { wrong: "I am practicing speaking.", right: "I'm practicing speaking.", why: "this is correct!", hindi: "मैं बोलने का अभ्यास कर रहा हूँ।" },
      { wrong: "I am reading newspaper daily.", right: "I read the newspaper daily.", why: "simple present + 'the'", hindi: "मैं रोज़ अखबार पढ़ता हूँ।" },
      { wrong: "I am writing with pen.", right: "I'm writing with a pen.", why: "'a' is needed", hindi: "मैं पेन से लिख रहा हूँ।" },
      { wrong: "I am having a doubt in this question.", right: "I have a question about this.", why: "'question'", hindi: "मुझे इस प्रश्न पर संदेह है।" },
      { wrong: "I am scoring full marks.", right: "I scored full marks.", why: "past tense", hindi: "मुझे पूरे अंक मिले।" },
      { wrong: "I am topping in my class.", right: "I'm at the top of my class.", why: "at the top", hindi: "मैं कक्षा में टॉप कर रहा हूँ।" },
      { wrong: "I am bunking the class.", right: "I'm skipping class.", why: "'skipping'", hindi: "मैं क्लास बंक कर रहा हूँ।" },
      { wrong: "I am copying from my friend.", right: "I'm copying from my friend.", why: "this is correct!", hindi: "मैं दोस्त से नकल कर रहा हूँ।" },
      { wrong: "I am concentrating on studies.", right: "I'm focusing on my studies.", why: "'focusing'", hindi: "मैं पढ़ाई पर ध्यान दे रहा हूँ।" },
      { wrong: "I am getting distracted.", right: "I keep getting distracted.", why: "'keeps'", hindi: "मेरा ध्यान भटक रहा है।" },
      { wrong: "I am confident about exam.", right: "I'm confident about the exam.", why: "'the' is needed", hindi: "मुझे परीक्षा को लेकर आत्मविश्वास है।" },
    ],
  },
  {
    id: "travel", emoji: "✈️", title: "Travel & Hotel", desc: "Book & check in smoothly",
    items: [
      { wrong: "I am booking a room.", right: "I'd like to book a room.", why: "polite", hindi: "मुझे कमरा बुक करना है।" },
      { wrong: "How much is the room rent?", right: "How much is the room per night?", why: "per night", hindi: "कमरे का किराया कितना है?" },
      { wrong: "I want check-in.", right: "I'd like to check in, please.", why: "polite", hindi: "मुझे चेक-इन करना है।" },
      { wrong: "What time is check-out?", right: "What time is check-out?", why: "this is correct!", hindi: "चेक-आउट कितने बजे है?" },
      { wrong: "Is breakfast included?", right: "Is breakfast included?", why: "this is correct!", hindi: "क्या नाश्ता शामिल है?" },
      { wrong: "I am checking out tomorrow.", right: "I'm checking out tomorrow.", why: "this is correct!", hindi: "मैं कल चेक-आउट करूँगा।" },
      { wrong: "The AC is not working.", right: "The AC isn't working.", why: "this is correct!", hindi: "एसी काम नहीं कर रहा।" },
      { wrong: "Please change my room.", right: "Could I change rooms, please?", why: "polite", hindi: "कृपया मेरा कमरा बदलिए।" },
      { wrong: "I am having problem with hot water.", right: "There's no hot water in my room.", why: "more natural", hindi: "मेरे कमरे में गर्म पानी नहीं है।" },
      { wrong: "Where is the reception?", right: "Where is the reception?", why: "this is correct!", hindi: "रिसेप्शन कहाँ है?" },
      { wrong: "I am extending my stay.", right: "I'd like to extend my stay.", why: "polite", hindi: "मैं अपना प्रवास बढ़ाना चाहता हूँ।" },
      { wrong: "The bed is not clean.", right: "The bed isn't clean.", why: "this is correct!", hindi: "बिस्तर साफ़ नहीं है।" },
      { wrong: "Please give me extra blanket.", right: "Could I have an extra blanket?", why: "polite + 'an'", hindi: "एक और कंबल दीजिए।" },
      { wrong: "I am paying by cash.", right: "I'll pay in cash.", why: "in cash", hindi: "मैं नकद दूँगा।" },
      { wrong: "Is there parking facility?", right: "Is there parking available?", why: "'available'", hindi: "क्या पार्किंग है?" },
      { wrong: "I am arriving at night.", right: "I'll be arriving at night.", why: "future", hindi: "मैं रात में पहुँचूँगा।" },
      { wrong: "The train is late.", right: "The train is running late.", why: "running late", hindi: "ट्रेन लेट है।" },
      { wrong: "I am catching the flight at 6.", right: "My flight is at 6.", why: "more natural", hindi: "मेरी फ्लाइट 6 बजे है।" },
      { wrong: "I am missing my train.", right: "I'm going to miss my train.", why: "going to", hindi: "मेरी ट्रेन छूट जाएगी।" },
      { wrong: "Please drop my luggage here.", right: "Please leave my luggage here.", why: "'leave'", hindi: "कृपया मेरा सामान यहाँ रखिए।" },
      { wrong: "I am carrying heavy bag.", right: "I'm carrying a heavy bag.", why: "'a' is needed", hindi: "मैं भारी बैग उठा रहा हूँ।" },
      { wrong: "The bus is full.", right: "The bus is full.", why: "this is correct!", hindi: "बस भर गई है।" },
      { wrong: "I am getting down at next stop.", right: "I'm getting off at the next stop.", why: "get OFF", hindi: "अगले पड़ाव पर उतरूँगा।" },
      { wrong: "I am boarding the train.", right: "I'm boarding the train.", why: "this is correct!", hindi: "मैं ट्रेन में चढ़ रहा हूँ।" },
      { wrong: "Is this seat free?", right: "Is this seat taken?", why: "'taken'", hindi: "क्या यह सीट खाली है?" },
      { wrong: "I am reserving a window seat.", right: "I'd like a window seat, please.", why: "polite", hindi: "मुझे खिड़की वाली सीट चाहिए।" },
      { wrong: "The journey is very long.", right: "The journey is really long.", why: "'really'", hindi: "सफर बहुत लंबा है।" },
      { wrong: "I am reaching the hotel by 8.", right: "I'll reach the hotel by 8.", why: "future", hindi: "मैं 8 बजे तक होटल पहुँचूँगा।" },
      { wrong: "Please wake me at 5.", right: "Could you wake me at 5, please?", why: "polite", hindi: "कृपया मुझे 5 बजे उठाइए।" },
      { wrong: "I am enjoying the trip.", right: "I'm enjoying the trip.", why: "this is correct!", hindi: "मुझे यात्रा अच्छी लग रही है।" },
    ],
  },
  {
    id: "smalltalk", emoji: "☕", title: "Small Talk with Strangers", desc: "Chat politely with anyone",
    items: [
      { wrong: "What is your name?", right: "May I know your name?", why: "polite to a stranger", hindi: "क्या मैं आपका नाम जान सकता हूँ?" },
      { wrong: "You are from where?", right: "Where are you from?", why: "word order", hindi: "आप कहाँ से हैं?" },
      { wrong: "What you are doing?", right: "What do you do?", why: "asking about work", hindi: "आप क्या करते हैं?" },
      { wrong: "It is very hot today, no?", right: "It's really hot today, isn't it?", why: "tag question", hindi: "आज बहुत गर्मी है, है ना?" },
      { wrong: "Nice weather today.", right: "Lovely weather today!", why: "more natural", hindi: "आज मौसम अच्छा है!" },
      { wrong: "I am first time here.", right: "It's my first time here.", why: "correct form", hindi: "मैं पहली बार यहाँ हूँ।" },
      { wrong: "You are also waiting for bus?", right: "Are you also waiting for the bus?", why: "question form", hindi: "क्या आप भी बस का इंतज़ार कर रहे हैं?" },
      { wrong: "This place is very good.", right: "This place is really nice.", why: "'nice'", hindi: "यह जगह बहुत अच्छी है।" },
      { wrong: "I am liking this city.", right: "I love this city.", why: "'like' is stative", hindi: "मुझे यह शहर पसंद है।" },
      { wrong: "How long you are living here?", right: "How long have you lived here?", why: "present perfect", hindi: "आप यहाँ कितने समय से रह रहे हैं?" },
      { wrong: "You are looking familiar.", right: "You look familiar.", why: "look + adjective", hindi: "आप पहचान के लगते हैं।" },
      { wrong: "Have we met before?", right: "Have we met before?", why: "this is correct!", hindi: "क्या हम पहले मिले हैं?" },
      { wrong: "I am not remembering.", right: "I don't remember.", why: "'remember' is stative", hindi: "मुझे याद नहीं।" },
      { wrong: "Please excuse me.", right: "Excuse me.", why: "simpler", hindi: "माफ़ कीजिए।" },
      { wrong: "Sorry for disturbing.", right: "Sorry to bother you.", why: "'bother'", hindi: "परेशान करने के लिए माफ़ी।" },
      { wrong: "Can I sit here?", right: "May I sit here?", why: "polite", hindi: "क्या मैं यहाँ बैठ सकता हूँ?" },
      { wrong: "You are speaking English very good.", right: "You speak English very well.", why: "'well' (adverb)", hindi: "आप अंग्रेज़ी बहुत अच्छी बोलते हैं।" },
      { wrong: "I am also learning English.", right: "I'm learning English too.", why: "'too'", hindi: "मैं भी अंग्रेज़ी सीख रहा हूँ।" },
      { wrong: "It is raining a lot today.", right: "It's pouring today!", why: "'pouring'", hindi: "आज बहुत बारिश हो रही है!" },
      { wrong: "The traffic is too much.", right: "The traffic is terrible.", why: "'terrible'", hindi: "ट्रैफिक बहुत खराब है।" },
      { wrong: "I am in hurry.", right: "I'm in a hurry.", why: "'a' is needed", hindi: "मुझे जल्दी है।" },
      { wrong: "Take care.", right: "Take care!", why: "this is correct!", hindi: "अपना ख्याल रखिए!" },
      { wrong: "It was nice talking to you.", right: "It was nice talking to you.", why: "this is correct!", hindi: "आपसे बात करके अच्छा लगा।" },
      { wrong: "See you around.", right: "See you around!", why: "this is correct!", hindi: "फिर मिलेंगे!" },
      { wrong: "I am regular here.", right: "I come here often.", why: "'often'", hindi: "मैं यहाँ अक्सर आता हूँ।" },
      { wrong: "You are new here?", right: "Are you new here?", why: "question form", hindi: "क्या आप यहाँ नए हैं?" },
      { wrong: "I am knowing this area well.", right: "I know this area well.", why: "'know' is stative", hindi: "मैं इस इलाके को अच्छे से जानता हूँ।" },
      { wrong: "Let me help you with that.", right: "Let me help you with that.", why: "this is correct!", hindi: "लाइए, मैं मदद करता हूँ।" },
      { wrong: "Thanks for your help.", right: "Thanks for your help!", why: "this is correct!", hindi: "मदद के लिए धन्यवाद!" },
      { wrong: "Have a nice day.", right: "Have a nice day!", why: "this is correct!", hindi: "आपका दिन शुभ हो!" },
    ],
  },
];