import { Pack } from "./dataA";

export const PACKS_B: Pack[] = [
  {
    id: "shopping", emoji: "🛍️", title: "Shopping Conversations", desc: "Bargain & buy like a local",
    items: [
      { wrong: "How much cost?", right: "How much does this cost?", why: "need 'does' in question", hindi: "इसकी कीमत क्या है?" },
      { wrong: "Give me discount.", right: "Could you give me a discount?", why: "polite request", hindi: "क्या छूट मिलेगी?" },
      { wrong: "This is too much costly.", right: "This is too expensive.", why: "'expensive' is the adjective", hindi: "यह बहुत महंगा है।" },
      { wrong: "I want to try this.", right: "Can I try this on?", why: "'try on' for clothes", hindi: "क्या मैं इसे पहनकर देख सकता हूँ?" },
      { wrong: "Do you have small size?", right: "Do you have this in a smaller size?", why: "more natural", hindi: "क्या छोटा साइज़ है?" },
      { wrong: "I will take this one only.", right: "I'll take this one.", why: "drop 'only'", hindi: "मुझे यही चाहिए।" },
      { wrong: "The fitting is not good.", right: "It doesn't fit me well.", why: "more natural", hindi: "यह ठीक से नहीं बैठता।" },
      { wrong: "Give me bill.", right: "Could I have the bill, please?", why: "polite request", hindi: "बिल दीजिए।" },
      { wrong: "Do you take card?", right: "Do you accept cards?", why: "'accept' is correct", hindi: "क्या कार्ड लेते हैं?" },
      { wrong: "Can I return this?", right: "Can I return this if it doesn't fit?", why: "more specific", hindi: "क्या मैं इसे वापस कर सकता हूँ?" },
      { wrong: "Where is the trial room?", right: "Where is the fitting room?", why: "'fitting room' is standard", hindi: "ट्रायल रूम कहाँ है?" },
      { wrong: "This is out of my budget.", right: "This is over my budget.", why: "'over budget' is correct", hindi: "यह मेरे बजट से बाहर है।" },
      { wrong: "I am just looking only.", right: "I'm just looking, thanks.", why: "drop 'only'", hindi: "मैं सिर्फ़ देख रहा हूँ।" },
      { wrong: "Do you have this in black color?", right: "Do you have this in black?", why: "'color' is redundant", hindi: "क्या यह काले में है?" },
      { wrong: "I want to exchange this.", right: "I'd like to exchange this.", why: "'would like' is politer", hindi: "मैं इसे बदलना चाहता हूँ।" },
      { wrong: "The quality is not good.", right: "The quality isn't great.", why: "'great' is more natural", hindi: "गुणवत्ता अच्छी नहीं है।" },
      { wrong: "Is this on sale?", right: "Is this on sale?", why: "this is correct!", hindi: "क्या यह सेल पर है?" },
      { wrong: "Give me one plastic bag.", right: "Could I have a bag, please?", why: "polite request", hindi: "एक बैग दीजिए।" },
      { wrong: "This shirt is torn.", right: "This shirt has a tear in it.", why: "more precise", hindi: "इस कमीज़ में छेद है।" },
      { wrong: "I will pay by cash.", right: "I'll pay in cash.", why: "'in cash' is correct", hindi: "मैं नकद दूँगा।" },
      { wrong: "The price is fix.", right: "The price is fixed.", why: "'fixed' (past participle)", hindi: "कीमत फिक्स है।" },
      { wrong: "Can you pack this?", right: "Could you gift-wrap this?", why: "more specific", hindi: "क्या आप इसे गिफ्ट-रैप करेंगे?" },
      { wrong: "Do you have any offers?", right: "Are there any offers on this?", why: "more natural", hindi: "क्या इस पर कोई ऑफर है?" },
      { wrong: "I am not interested.", right: "No thanks, I'm just browsing.", why: "politer refusal", hindi: "नहीं, मैं बस देख रहा हूँ।" },
      { wrong: "This is too tight.", right: "This is a bit tight.", why: "softer complaint", hindi: "यह थोड़ा टाइट है।" },
      { wrong: "I want a refund.", right: "I'd like a refund, please.", why: "'would like' is politer", hindi: "मुझे रिफंड चाहिए।" },
      { wrong: "Give me warranty card.", right: "Could I have the warranty card?", why: "polite request", hindi: "वारंटी कार्ड दीजिए।" },
      { wrong: "This color is faded.", right: "The color has faded.", why: "more natural", hindi: "रंग फीका हो गया है।" },
      { wrong: "Do you have home delivery?", right: "Do you offer home delivery?", why: "'offer' is correct", hindi: "क्या होम डिलीवरी है?" },
      { wrong: "I will come again.", right: "I'll come back later.", why: "more natural", hindi: "मैं बाद में आऊँगा।" },
    ],
  },
  {
    id: "doctor", emoji: "🏥", title: "Doctor Visits", desc: "Explain your health clearly",
    items: [
      { wrong: "I am having headache.", right: "I have a headache.", why: "'have' for symptoms", hindi: "मुझे सिरदर्द है।" },
      { wrong: "I am suffering from cold.", right: "I have a cold.", why: "'suffering' is too strong", hindi: "मुझे ज़ुकाम है।" },
      { wrong: "My stomach is paining.", right: "I have a stomachache.", why: "'pain' isn't used as verb this way", hindi: "मेरे पेट में दर्द है।" },
      { wrong: "I am feeling giddiness.", right: "I am feeling dizzy.", why: "'dizzy' is the adjective", hindi: "मुझे चक्कर आ रहे हैं।" },
      { wrong: "Give me medicine.", right: "Could you prescribe something?", why: "politer and correct", hindi: "कृपया दवा लिखें।" },
      { wrong: "I am having fever since yesterday.", right: "I have had a fever since yesterday.", why: "present perfect for ongoing", hindi: "कल से बुखार है।" },
      { wrong: "My throat is scratching.", right: "My throat is sore.", why: "'sore' is correct", hindi: "गला खराब है।" },
      { wrong: "I am feeling weak.", right: "I feel weak.", why: "simpler is better", hindi: "कमज़ोरी लग रही है।" },
      { wrong: "I didn't sleep properly.", right: "I didn't sleep well.", why: "'well' for quality", hindi: "नींद अच्छी नहीं आई।" },
      { wrong: "I am vomiting since morning.", right: "I have been vomiting since morning.", why: "present perfect continuous", hindi: "सुबह से उल्टी हो रही है।" },
      { wrong: "My leg is swollen.", right: "My leg is swollen.", why: "this is correct!", hindi: "पैर सूजा हुआ है।" },
      { wrong: "I am having pain in chest.", right: "I have chest pain.", why: "more natural", hindi: "छाती में दर्द है।" },
      { wrong: "Give me injection.", right: "Do I need an injection?", why: "ask as question", hindi: "क्या इंजेक्शन चाहिए?" },
      { wrong: "I am allergic to dust.", right: "I am allergic to dust.", why: "this is correct!", hindi: "मुझे धूल से एलर्जी है।" },
      { wrong: "My back is paining.", right: "My back hurts.", why: "'hurts' is more natural", hindi: "पीठ दर्द कर रही है।" },
      { wrong: "I am taking medicine since 2 days.", right: "I have been taking medicine for 2 days.", why: "'for' with duration", hindi: "2 दिन से दवा ले रहा हूँ।" },
      { wrong: "I feel like vomiting.", right: "I feel nauseous.", why: "medical term", hindi: "मुझे उल्टी जैसा लग रहा है।" },
      { wrong: "My nose is blocked.", right: "I have a blocked nose.", why: "more natural", hindi: "नाक बंद है।" },
      { wrong: "I am having loose motions.", right: "I have diarrhea.", why: "medical term", hindi: "मुझे दस्त हैं।" },
      { wrong: "Give me appointment.", right: "Could I make an appointment?", why: "polite request", hindi: "क्या अपॉइंटमेंट मिलेगी?" },
      { wrong: "I am feeling better now.", right: "I'm feeling better now.", why: "this is correct!", hindi: "अब बेहतर लग रहा है।" },
      { wrong: "The medicine is not suiting me.", right: "The medicine isn't working.", why: "more natural", hindi: "दवा असर नहीं कर रही।" },
      { wrong: "I am having cough.", right: "I have a cough.", why: "'have' for symptoms", hindi: "मुझे खांसी है।" },
      { wrong: "My eyes are burning.", right: "My eyes are burning.", why: "this is correct!", hindi: "आँखें जल रही हैं।" },
      { wrong: "I am feeling tiredness.", right: "I feel tired.", why: "'tired' is adjective", hindi: "थकान लग रही है।" },
      { wrong: "Give me sick leave.", right: "Could I have a medical certificate?", why: "ask for certificate", hindi: "क्या मेडिकल सर्टिफिकेट मिलेगा?" },
      { wrong: "I am having acidity.", right: "I have acidity.", why: "'have' for conditions", hindi: "मुझे एसिडिटी है।" },
      { wrong: "My knee is paining.", right: "My knee hurts.", why: "'hurts' is natural", hindi: "घुटना दर्द कर रहा है।" },
      { wrong: "I am feeling breathless.", right: "I feel short of breath.", why: "more natural", hindi: "सांस फूल रही है।" },
      { wrong: "When should I come for checkup?", right: "When should I come for a follow-up?", why: "'follow-up' is standard", hindi: "अगली जांच कब?" },
    ],
  },
  {
    id: "phone", emoji: "📞", title: "Phone Conversations", desc: "Talk confidently on calls",
    items: [
      { wrong: "Hello, I am Ravi speaking.", right: "Hello, this is Ravi.", why: "'this is' on phone", hindi: "हैलो, मैं रवि बोल रहा हूँ।" },
      { wrong: "Who is speaking?", right: "Who's calling, please?", why: "more polite", hindi: "कौन बोल रहे हैं?" },
      { wrong: "Is Ravi there?", right: "May I speak to Ravi?", why: "more polite", hindi: "क्या मैं रवि से बात कर सकता हूँ?" },
      { wrong: "Hold on, I will call him.", right: "Hold on, I'll get him.", why: "more natural", hindi: "रुकिए, मैं उसे बुलाता हूँ।" },
      { wrong: "He is not in home.", right: "He isn't home right now.", why: "'at home' or just 'home'", hindi: "वह अभी घर पर नहीं है।" },
      { wrong: "Can I take a message?", right: "Can I take a message?", why: "this is correct!", hindi: "क्या मैं संदेश ले सकता हूँ?" },
      { wrong: "Please tell him I called.", right: "Please tell him I called.", why: "this is correct!", hindi: "उसे बताइएगा कि मैंने कॉल किया।" },
      { wrong: "I am calling from Delhi.", right: "I'm calling from Delhi.", why: "this is correct!", hindi: "मैं दिल्ली से कॉल कर रहा हूँ।" },
      { wrong: "Can you hear me?", right: "Can you hear me?", why: "this is correct!", hindi: "क्या आप सुन पा रहे हैं?" },
      { wrong: "Your voice is not coming.", right: "I can't hear you clearly.", why: "more natural", hindi: "आवाज़ साफ़ नहीं आ रही।" },
      { wrong: "The call is cutting.", right: "The call is breaking up.", why: "'breaking up' is correct", hindi: "कॉल कट रही है।" },
      { wrong: "I will call you back later.", right: "I'll call you back later.", why: "this is correct!", hindi: "मैं बाद में कॉल करूँगा।" },
      { wrong: "Please speak loudly.", right: "Could you speak up, please?", why: "more polite", hindi: "थोड़ा ज़ोर से बोलिए।" },
      { wrong: "I am in a meeting.", right: "I'm in a meeting.", why: "this is correct!", hindi: "मैं मीटिंग में हूँ।" },
      { wrong: "Can I call you later?", right: "Can I call you back later?", why: "'call back' is correct", hindi: "क्या मैं बाद में कॉल कर सकता हूँ?" },
      { wrong: "Your phone is switched off.", right: "Your phone is switched off.", why: "this is correct!", hindi: "आपका फोन बंद है।" },
      { wrong: "I am not getting your point.", right: "I don't understand what you mean.", why: "clearer", hindi: "मुझे समझ नहीं आ रहा।" },
      { wrong: "Please wait, I am checking.", right: "Please hold on, let me check.", why: "more natural", hindi: "रुकिए, मैं चेक करता हूँ।" },
      { wrong: "I will inform him.", right: "I'll let him know.", why: "'let him know' is friendlier", hindi: "मैं उसे बता दूँगा।" },
      { wrong: "Can you repeat that?", right: "Could you repeat that, please?", why: "more polite", hindi: "क्या आप दोहराएंगे?" },
      { wrong: "I am driving, I will call later.", right: "I'm driving, I'll call you back.", why: "more natural", hindi: "मैं गाड़ी चला रहा हूँ, बाद में कॉल करूँगा।" },
      { wrong: "Is this a good time to talk?", right: "Is this a good time to talk?", why: "this is correct!", hindi: "क्या बात करने का सही समय है?" },
      { wrong: "I am sorry, wrong number.", right: "Sorry, wrong number.", why: "simpler is better", hindi: "माफ़ कीजिए, गलत नंबर।" },
      { wrong: "Please speak slowly.", right: "Could you speak a bit slower?", why: "more polite", hindi: "थोड़ा धीरे बोलिए।" },
      { wrong: "I will text you.", right: "I'll text you.", why: "this is correct!", hindi: "मैं मैसेज करूँगा।" },
      { wrong: "Your voice is breaking.", right: "You're breaking up.", why: "more natural", hindi: "आवाज़ टूट रही है।" },
      { wrong: "Can I leave a message?", right: "Can I leave a message?", why: "this is correct!", hindi: "क्या मैं संदेश छोड़ सकता हूँ?" },
      { wrong: "I am not able to hear.", right: "I can't hear you.", why: "simpler", hindi: "मुझे सुनाई नहीं दे रहा।" },
      { wrong: "Please call me when you are free.", right: "Please call me when you're free.", why: "this is correct!", hindi: "फ्री हों तो कॉल कीजिए।" },
      { wrong: "I will send you the details.", right: "I'll send you the details.", why: "this is correct!", hindi: "मैं विवरण भेजूँगा।" },
    ],
  },
  {
    id: "directions", emoji: "🧭", title: "Asking Directions", desc: "Never get lost again",
    items: [
      { wrong: "Where is station?", right: "Where is the station?", why: "'the' is needed", hindi: "स्टेशन कहाँ है?" },
      { wrong: "How to go to mall?", right: "How do I get to the mall?", why: "more natural", hindi: "मॉल कैसे जाएँ?" },
      { wrong: "Is this the right way?", right: "Is this the right way?", why: "this is correct!", hindi: "क्या यह सही रास्ता है?" },
      { wrong: "How much far is it?", right: "How far is it?", why: "'much' is not needed", hindi: "कितनी दूर है?" },
      { wrong: "Can you show me the way?", right: "Could you show me the way?", why: "more polite", hindi: "क्या आप रास्ता बताएंगे?" },
      { wrong: "I am lost.", right: "I think I'm lost.", why: "softer", hindi: "शायद मैं रास्ता भटक गया।" },
      { wrong: "Where is the nearest hospital?", right: "Where is the nearest hospital?", why: "this is correct!", hindi: "सबसे नज़दीकी अस्पताल कहाँ है?" },
      { wrong: "Go straight and then left.", right: "Go straight, then turn left.", why: "'turn' is needed", hindi: "सीधे जाएँ, फिर बाएँ मुड़ें।" },
      { wrong: "It is near to my house.", right: "It's near my house.", why: "drop 'to'", hindi: "मेरे घर के पास है।" },
      { wrong: "How many minutes to reach?", right: "How long does it take to get there?", why: "more natural", hindi: "पहुँचने में कितना समय लगेगा?" },
      { wrong: "Is there any bus stop nearby?", right: "Is there a bus stop nearby?", why: "'a' is correct", hindi: "क्या पास में बस स्टॉप है?" },
      { wrong: "I am looking for ATM.", right: "I'm looking for an ATM.", why: "'an' is needed", hindi: "मैं ATM ढूँढ रहा हूँ।" },
      { wrong: "Which side I should go?", right: "Which way should I go?", why: "'way' not 'side'", hindi: "किस तरफ़ जाऊँ?" },
      { wrong: "Is it walkable distance?", right: "Is it within walking distance?", why: "more natural phrase", hindi: "क्या पैदल जा सकते हैं?" },
      { wrong: "Take the second left.", right: "Take the second left.", why: "this is correct!", hindi: "दूसरी बाईं तरफ़ मुड़ें।" },
      { wrong: "It is opposite to the bank.", right: "It's opposite the bank.", why: "drop 'to'", hindi: "बैंक के सामने है।" },
      { wrong: "Can you drop me at station?", right: "Could you drop me at the station?", why: "more polite", hindi: "क्या आप मुझे स्टेशन छोड़ेंगे?" },
      { wrong: "I am going to market.", right: "I'm going to the market.", why: "'the' is needed", hindi: "मैं बाज़ार जा रहा हूँ।" },
      { wrong: "Is this the way to airport?", right: "Is this the way to the airport?", why: "'the' needed", hindi: "क्या यह एयरपोर्ट का रास्ता है?" },
      { wrong: "How many kilometers from here?", right: "How many kilometers is it from here?", why: "add 'is it'", hindi: "यहाँ से कितने किलोमीटर?" },
      { wrong: "I am coming from south side.", right: "I'm coming from the south.", why: "'the south' is correct", hindi: "मैं दक्षिण से आ रहा हूँ।" },
      { wrong: "Please guide me.", right: "Could you help me find...", why: "more specific", hindi: "क्या आप मदद करेंगे?" },
      { wrong: "It is next to the school.", right: "It's next to the school.", why: "this is correct!", hindi: "स्कूल के बगल में है।" },
      { wrong: "I am not knowing the way.", right: "I don't know the way.", why: "'know' is stative, no -ing", hindi: "मुझे रास्ता नहीं पता।" },
      { wrong: "Is there any shortcut?", right: "Is there a shortcut?", why: "'a' not 'any'", hindi: "क्या कोई शॉर्टकट है?" },
      { wrong: "I am going to wrong direction.", right: "I'm going the wrong way.", why: "more natural", hindi: "मैं गलत दिशा में जा रहा हूँ।" },
      { wrong: "Where can I get a taxi?", right: "Where can I get a taxi?", why: "this is correct!", hindi: "टैक्सी कहाँ मिलेगी?" },
      { wrong: "Is it on the right side?", right: "Is it on the right?", why: "'side' is redundant", hindi: "क्या दाईं तरफ़ है?" },
      { wrong: "I am near to your location.", right: "I'm near your location.", why: "drop 'to'", hindi: "मैं आपके पास हूँ।" },
      { wrong: "Please tell me how to reach.", right: "Could you tell me how to get there?", why: "more complete", hindi: "कैसे पहुँचूँ, बताइए।" },
    ],
  },
  {
    id: "polite", emoji: "🙏", title: "Requests & Politeness", desc: "Sound polite in every situation",
    items: [
      { wrong: "Give me water.", right: "Could I have some water, please?", why: "polite request", hindi: "कृपया पानी दीजिए।" },
      { wrong: "Open the window.", right: "Could you open the window?", why: "polite question", hindi: "क्या आप खिड़की खोलेंगे?" },
      { wrong: "Tell me the answer.", right: "Could you tell me the answer?", why: "polite question", hindi: "क्या आप उत्तर बताएंगे?" },
      { wrong: "I want to ask something.", right: "May I ask you something?", why: "more polite", hindi: "क्या मैं कुछ पूछ सकता हूँ?" },
      { wrong: "Wait for me.", right: "Could you wait for me?", why: "polite question", hindi: "क्या आप मेरा इंतज़ार करेंगे?" },
      { wrong: "Help me.", right: "Could you help me, please?", why: "more polite", hindi: "क्या आप मदद करेंगे?" },
      { wrong: "Sit down.", right: "Please have a seat.", why: "more polite", hindi: "कृपया बैठिए।" },
      { wrong: "Come here.", right: "Could you come here, please?", why: "less commanding", hindi: "क्या आप यहाँ आएंगे?" },
      { wrong: "Shut up.", right: "Could you please be quiet?", why: "much politer", hindi: "कृपया चुप रहिए।" },
      { wrong: "I don't want this.", right: "No thank you, I'm fine.", why: "politer refusal", hindi: "नहीं, धन्यवाद।" },
      { wrong: "Move from there.", right: "Could you move, please?", why: "polite request", hindi: "क्या आप हटेंगे?" },
      { wrong: "Give me your pen.", right: "May I borrow your pen?", why: "'borrow' is correct", hindi: "क्या आपका पेन लूँ?" },
      { wrong: "Don't do that.", right: "Please don't do that.", why: "add 'please'", hindi: "कृपया ऐसा मत कीजिए।" },
      { wrong: "You are wrong.", right: "I think there might be a mistake.", why: "softer", hindi: "शायद कोई गलती है।" },
      { wrong: "I disagree.", right: "I see it differently.", why: "softer disagreement", hindi: "मेरा नज़रिया अलग है।" },
      { wrong: "You must do this.", right: "I suggest you do this.", why: "less bossy", hindi: "मैं सुझाव दूँगा कि आप यह करें।" },
      { wrong: "Give me a chance.", right: "Could you give me a chance?", why: "polite question", hindi: "क्या मुझे मौका मिलेगा?" },
      { wrong: "I am sorry for late.", right: "I'm sorry for being late.", why: "'being' needed", hindi: "देरी के लिए माफ़ी।" },
      { wrong: "Excuse me, what you said?", right: "Excuse me, what did you say?", why: "question needs 'did'", hindi: "आपने क्या कहा?" },
      { wrong: "Can I interrupt?", right: "May I interrupt for a moment?", why: "more polite", hindi: "क्या मैं एक पल के लिए टोक सकता हूँ?" },
      { wrong: "Please do this work.", right: "Could you please handle this?", why: "more polite", hindi: "क्या आप यह काम करेंगे?" },
      { wrong: "I need your help.", right: "I could use your help.", why: "softer request", hindi: "मुझे आपकी मदद चाहिए।" },
      { wrong: "You should come.", right: "You should come if you can.", why: "less demanding", hindi: "आ सको तो आइए।" },
      { wrong: "I am busy now.", right: "I'm a bit busy right now.", why: "softer", hindi: "अभी थोड़ा व्यस्त हूँ।" },
      { wrong: "Don't disturb me.", right: "Could you give me a moment?", why: "politer", hindi: "क्या थोड़ा समय देंगे?" },
      { wrong: "I want to talk to you.", right: "Could we talk for a moment?", why: "polite question", hindi: "क्या हम बात कर सकते हैं?" },
      { wrong: "Please listen to me.", right: "Could you please listen?", why: "politer", hindi: "कृपया सुनिए।" },
      { wrong: "I am not understanding.", right: "I don't understand.", why: "'understand' is stative", hindi: "मुझे समझ नहीं आ रहा।" },
      { wrong: "Can you do me a favor?", right: "Could you do me a favor?", why: "'could' is politer", hindi: "क्या आप एक काम करेंगे?" },
      { wrong: "Please be on time.", right: "Please try to be on time.", why: "softer", hindi: "कृपया समय पर आइए।" },
    ],
  },
];